#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sinh bộ tài liệu Gói bán hàng v1.0 (MD + Word chuyên nghiệp)."""
from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES_TOOLS = Path(__file__).resolve().parents[2] / "01. Modules" / "_tools"
sys.path.insert(0, str(MODULES_TOOLS))

from build_srs_docx_pro import build, extract_meta_from_md  # noqa: E402

TODAY = date.today().strftime("%d/%m/%Y")

# code, name, sell_alone, hard_deps, soft_deps, buyer, value_pitch
SKU = [
    ("SYS", "Hệ thống nền tảng", "Không — luôn kèm", "—", "—", "Mọi khách", "Auth, RBAC, license, org, audit, bus"),
    ("HRM", "Quản trị nhân sự", "Có", "SYS", "WF, FIN, LMS, AST", "HCNS / People Ops", "Hồ sơ–công–phép–lương–nghỉ việc"),
    ("LMS", "Đào tạo", "Có", "SYS", "HRM, CRM, FIN", "Đào tạo / Compliance", "Khóa học, thi, chứng chỉ, lộ trình"),
    ("CRM", "CRM & Bán hàng", "Có", "SYS", "INV, LOG, FIN, WF, PRT", "Sales / CSKH", "Lead→Opportunity→SO→công nợ"),
    ("POS", "POS bán lẻ", "Có", "SYS", "INV, FIN, CRM", "Retail Ops", "Ca bán, thanh toán, tồn quầy"),
    ("PUR", "Mua hàng", "Có", "SYS", "INV, FIN, WF", "Procurement", "PR→PO→nhận hàng→AP"),
    ("INV", "Kho & Tồn kho", "Có", "SYS", "PUR, LOG, POS, MFG, FIN", "Warehouse / Supply", "Master hàng, tồn, nhập xuất"),
    ("LOG", "Giao vận", "Có", "SYS, INV", "CRM, FIN, PRT", "Logistics", "Lệnh giao, tracking, đối soát"),
    ("MFG", "Sản xuất", "Có", "SYS, INV", "PUR, FIN, HRM, CRM", "Production", "BOM, lệnh SX, NVL/TP"),
    ("FSM", "Dịch vụ kỹ thuật", "Có", "SYS", "CRM, INV, FIN, PRT", "Field Service", "Ticket, lịch kỹ thuật, linh kiện"),
    ("PJM", "Quản lý dự án", "Có", "SYS", "CRM, INV, FIN, HRM, WF", "PMO / Delivery", "Dự án, task, ngân sách, quyết toán"),
    ("FIN", "Tài chính – Kế toán", "Có", "SYS", "CRM, PUR, INV, POS, HRM, AST", "Kế toán / CFO", "GL, AR/AP, sổ, khóa kỳ"),
    ("AST", "Quản lý tài sản", "Có", "SYS", "FIN, HRM, PUR", "Admin / Asset", "Tài sản, khấu hao, bàn giao"),
    ("WF", "Công việc & Phê duyệt", "Có (hoặc kèm SYS)", "SYS", "Mọi module có duyệt", "Governance", "Quy trình duyệt tập trung"),
    ("BI", "Báo cáo & BI", "Có", "SYS", "Dataset theo license nguồn", "Management", "Dashboard, dataset có kiểm soát"),
    ("PRT", "Cổng khách hàng", "Có", "SYS", "CRM, LOG, FIN, FSM, PUR", "CSKH / Self-service", "Portal KH: đơn, công nợ, ticket"),
]


def header(doc_code: str, title: str, subtitle: str) -> list[str]:
    return [
        f"# {doc_code} — {title}",
        "",
        f"> **{subtitle}**",
        "> *Product Packaging & Commercial Catalog* — ERP bán theo module.",
        f"> Phiên bản **1.0** · Ngày {TODAY} · Trạng thái: **Chờ duyệt Presales / Solution**.",
        "> Generic — không gắn khách/ngành cứng; giá tiền theo bảng giá nội bộ.",
        "",
        "---",
        "",
        "## 0. Thông tin tài liệu",
        "",
        "| Thuộc tính | Giá trị |",
        "|---|---|",
        f"| Mã tài liệu | `{doc_code}` |",
        f"| Tên | {title} |",
        "| Phiên bản | 1.0 |",
        f"| Ngày | {TODAY} |",
        "| Phân loại | Gói bán hàng (Presales / BA / Delivery) |",
        "| Định dạng bàn giao | Microsoft Word (`.docx`) |",
        "| Đầu vào | SRS module v1.1 · INT-02 · DDD license |",
        "",
        "| Ver | Ngày | Mô tả | Trạng thái |",
        "|---|---|---|---|",
        f"| 1.0 | {TODAY} | Khởi tạo bộ Gói bán hàng | Chờ duyệt |",
        "",
        "---",
        "",
    ]


def write(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {path.name} ({len(lines)} lines)")


# =============================================================================
# PKG-01
# =============================================================================
def doc_01() -> list[str]:
    a = header(
        "PKG-01-v1.0",
        "Chiến lược & nguyên tắc đóng gói bán",
        "Packaging Strategy & Commercial Rules",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "### 1.1. Mục đích",
        "Chốt **cách sản phẩm ERP được đóng gói và bán**: module đơn lẻ (SKU), gói giải pháp (bundle), "
        "vai trò bắt buộc của SYS, và ranh giới giữa “chạy được” với “có giá trị E2E”.",
        "",
        "### 1.2. Đối tượng đọc",
        "- Presales / Sales Engineer",
        "- BA / Product Owner",
        "- Solution Architect",
        "- Delivery / Project Manager",
        "",
        "### 1.3. Ngoài phạm vi",
        "- Giá niêm yết chi tiết theo thị trường (thuộc bảng giá nội bộ / hợp đồng).",
        "- Thiết kế kỹ thuật event (thuộc INT) và schema DB (thuộc DDD).",
        "",
        "---",
        "",
        "## 2. Mô hình sản phẩm",
        "",
        "```text",
        "                    ┌──────────────────────────┐",
        "                    │   Gói giải pháp (Bundle) │",
        "                    │  = tập SKU module + quy  │",
        "                    │    tắc phụ thuộc Must    │",
        "                    └────────────┬─────────────┘",
        "                                 │ gồm",
        "              ┌──────────────────┼──────────────────┐",
        "              ▼                  ▼                  ▼",
        "         SKU Module         SKU Module         SKU SYS",
        "        (HRM/CRM/…)        (INV/FIN/…)      (luôn kèm)",
        "              │                  │                  │",
        "              └────────────┬─────┴──────────────────┘",
        "                           ▼",
        "                 License tenant (bật/tắt module",
        "                 + quota user / chi nhánh / …)",
        "```",
        "",
        "| Tầng | Định nghĩa | Ví dụ |",
        "|---|---|---|",
        "| **SKU Module** | Đơn vị bán nhỏ nhất (trừ SYS) | `CRM`, `INV` |",
        "| **Bundle** | Tập SKU ghép sẵn theo hành trình / ngành | Gói Bán hàng & phân phối |",
        "| **License** | Hợp đồng kỹ thuật trên tenant | `sys.license` + `license_module` |",
        "| **Add-on** | SKU bổ sung sau go-live | Thêm `PRT`, `BI` |",
        "",
        "---",
        "",
        "## 3. Nguyên tắc đóng gói (bắt buộc tuân thủ)",
        "",
        "| # | Nguyên tắc | Mô tả |",
        "|---|---|---|",
        "| R1 | SYS luôn kèm | Mọi báo giá / hợp đồng đều có SYS; không bán module nghiệp vụ “trần”. |",
        "| R2 | Hard dependency trong Must | Module có phụ thuộc cứng (vd LOG→INV) phải có trong Phase 1. |",
        "| R3 | Soft ≠ hứa E2E | Thiếu soft dependency vẫn chạy module, nhưng **không cam kết** journey đầy đủ. |",
        "| R4 | Một master một chủ | Ví dụ Item thuộc INV, Customer thuộc CRM — ghi rõ khi bán gói. |",
        "| R5 | License gate | Tắt module ⇒ ẩn menu + chặn API; dữ liệu giữ theo chính sách lưu trữ. |",
        "| R6 | Upsell không phá dữ liệu | Bật thêm module = enable license + cấu hình; không migration phá. |",
        "| R7 | Downsell có cảnh báo | Tắt module phải kiểm tra hard dependents còn active. |",
        "| R8 | Generic trước, ngành sau | Ngành (F&B, phân phối…) = **template cấu hình**, không SKU riêng trừ khi Product chốt. |",
        "| R9 | WF & BI là tăng tốc | WF/BI bán độc lập được nhưng giá trị tăng khi có module nguồn. |",
        "| R10 | Truy vết tài liệu | Mỗi bundle map INT-04 journey + SRS module liên quan. |",
        "",
        "---",
        "",
        "## 4. Phân loại phụ thuộc thương mại",
        "",
        "| Loại | Ký hiệu | Ý nghĩa với khách | Xử lý trên báo giá |",
        "|---|---|---|---|",
        "| Bắt buộc nền | **SYS** | Không thể thiếu | Luôn liệt kê |",
        "| Hard | **Must** | Module không triển khai/không vận hành đúng thiếu thành phần này | Bắt buộc cùng Phase |",
        "| Soft E2E | **Should** | Thiếu thì mất một phần hành trình | Phase 1 hoặc Phase 2 ghi rõ |",
        "| Nice-to-have | **Could** | Tiện ích / portal / BI nâng cao | Option |",
        "",
        "Ánh xạ kỹ thuật chi tiết: **INT-02**. Tài liệu PKG dùng ngôn ngữ Must/Should/Could cho Presales.",
        "",
        "---",
        "",
        "## 5. Ai quyết định gì",
        "",
        "| Vai trò | Quyết định |",
        "|---|---|",
        "| Presales | Chọn bundle / SKU phù hợp discovery |",
        "| BA | Xác nhận journey Must vs Should theo nghiệp vụ khách |",
        "| Solution | Xác nhận hard dependency & tích hợp |",
        "| Commercial | Báo giá, hạn mức, thời hạn license |",
        "| Delivery | Scope Phase 1 = đúng những gì đã ký |",
        "",
        "---",
        "",
        "## 6. Quan hệ với bộ tài liệu khác",
        "",
        "| Nội dung | Tài liệu |",
        "|---|---|",
        "| Chức năng từng module | SRS-XXX-v1.1 |",
        "| Phụ thuộc kỹ thuật | INT-02 |",
        "| Journey E2E | INT-04 |",
        "| Bảng license CSDL | DDD-02 / DDD-MASTER (`sys.license*`) |",
        "| Catalog SKU | PKG-02 |",
        "| Bundle | PKG-03 |",
        "| License & quota | PKG-04 |",
        "| Playbook bán/triển khai | PKG-05 |",
        "",
        "---",
        "",
        "*Hết PKG-01-v1.0.*",
        "",
    ]
    return a


# =============================================================================
# PKG-02
# =============================================================================
def doc_02() -> list[str]:
    a = header(
        "PKG-02-v1.0",
        "Catalog SKU module",
        "Sellable Module Catalog (SKU Sheets)",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "Danh mục **16 SKU module** — đơn vị bán nhỏ nhất (SYS là SKU nền, không bán độc lập).",
        "",
        "---",
        "",
        "## 2. Bảng tổng hợp SKU",
        "",
        "| Mã | Tên | Bán riêng | Hard (Must) | Soft (Should) | Người mua chính | Giá trị 1 dòng |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in SKU:
        a.append(
            f"| `{row[0]}` | {row[1]} | {row[2]} | {row[3]} | {row[4]} | {row[5]} | {row[6]} |"
        )
    a += [
        "",
        "---",
        "",
        "## 3. Chi tiết từng SKU",
        "",
    ]

    details = {
        "SYS": (
            "Nền tảng bắt buộc: đăng nhập, RBAC + data scope 4 tầng, org/department/job level, "
            "license, menu, file, thông báo, audit, outbox/inbox.",
            ["Không tắt khi còn module khác active", "Quota user/tenant áp dụng tại đây"],
            ["Mọi gói"],
        ),
        "HRM": (
            "Vòng đời nhân sự: hồ sơ, hợp đồng, chấm công/phép, lương (khung), điều chuyển, nghỉ việc.",
            ["Cần SYS", "Nên kèm WF nếu duyệt phép/tuyển tập trung", "FIN nếu post chi phí lương"],
            ["Gói Nhân sự số", "Enterprise full"],
        ),
        "LMS": (
            "Đào tạo nội bộ / compliance: chương trình, lớp, bài thi, chứng chỉ, lộ trình theo vị trí.",
            ["Chạy độc lập trên SYS", "Gán NV theo vị trí tốt hơn khi có HRM"],
            ["Gói Nhân sự số", "Compliance"],
        ),
        "CRM": (
            "Pipeline bán hàng B2B/B2C: lead, cơ hội, báo giá, đơn bán, CSKH.",
            ["Giao hàng & tồn cần INV+LOG", "Công nợ cần FIN", "Portal cần PRT"],
            ["Gói Bán hàng & phân phối", "Dịch vụ & dự án"],
        ),
        "POS": (
            "Bán tại quầy: ca, giỏ hàng, thanh toán, khuyến mãi tại điểm bán.",
            ["Trừ tồn realtime nên có INV", "Đối soát quỹ/doanh thu nên có FIN"],
            ["Gói Bán lẻ"],
        ),
        "PUR": (
            "Mua hàng: nhu cầu, PR, PO, theo dõi NCC, nhận hàng gắn kho.",
            ["GRN/tồn cần INV", "Công nợ NCC cần FIN", "Duyệt PR/PO nên có WF"],
            ["Gói Mua–Kho–SX", "Procure-to-Pay"],
        ),
        "INV": (
            "Master hàng hóa, kho, tồn, nhập/xuất/điều chuyển, kiểm kê.",
            ["Hard cho LOG/MFG", "Trục trung tâm chuỗi cung ứng"],
            ["Hầu hết gói vận hành hàng hóa"],
        ),
        "LOG": (
            "Giao vận: lệnh giao, tuyến, trạng thái giao, đối soát vận chuyển.",
            ["**Must có INV**", "Theo dõi đơn/KH tốt hơn với CRM", "Portal tracking với PRT"],
            ["Gói Bán hàng & phân phối"],
        ),
        "MFG": (
            "Sản xuất: BOM, lệnh SX, xuất NVL, nhập TP, báo cáo sản lượng.",
            ["**Must có INV**", "Giá thành/FIN và mua NVL/PUR nên kèm"],
            ["Gói Mua–Kho–SX"],
        ),
        "FSM": (
            "Dịch vụ hiện trường: ticket, lịch kỹ thuật viên, vật tư hiện trường.",
            ["CRM cho hợp đồng KH", "INV cho linh kiện", "PRT cho self-service"],
            ["Gói Dịch vụ & dự án"],
        ),
        "PJM": (
            "Quản lý dự án: WBS/task, tiến độ, ngân sách, quyết toán.",
            ["Doanh thu/chi phí với FIN+CRM", "Vật tư với INV"],
            ["Gói Dịch vụ & dự án"],
        ),
        "FIN": (
            "Kế toán: danh mục TK, chứng từ, AR/AP, sổ cái, khóa kỳ, báo cáo tài chính khung.",
            ["Là hub post từ nhiều module", "Không bắt buộc Day-1 mọi SME — nhưng cần cho E2E tiền"],
            ["Mọi gói có dòng tiền / sổ sách"],
        ),
        "AST": (
            "Tài sản cố định / CCDC: danh mục, bàn giao, khấu hao, thanh lý.",
            ["Khấu hao/FIN", "Thu hồi khi nghỉ việc/HRM"],
            ["Gói Nhân sự số", "Enterprise"],
        ),
        "WF": (
            "Engine phê duyệt tập trung: định nghĩa quy trình, task, ủy quyền.",
            ["Không bắt buộc nếu module có duyệt nội bộ đơn giản", "Khuyến nghị khi nhiều chứng từ Must approve"],
            ["Mọi gói governance"],
        ),
        "BI": (
            "Lớp báo cáo/dashboard; dataset chỉ mở theo license module nguồn.",
            ["Không thay thế báo cáo vận hành trong từng module", "Bán kèm khi cần C-level view"],
            ["Add-on hầu hết gói"],
        ),
        "PRT": (
            "Cổng khách hàng / đối tác: xem đơn, công nợ, ticket, tài liệu.",
            ["Phụ thuộc dữ liệu CRM/LOG/FIN/FSM", "Bảo mật portal role riêng"],
            ["Gói Bán hàng", "Dịch vụ"],
        ),
    }

    for code, name, *_ in SKU:
        pitch, notes, bundles = details[code]
        a += [
            f"### 3.{code}. `{code}` — {name}",
            "",
            f"**Giá trị bán:** {pitch}",
            "",
            "**Ghi chú đóng gói:**",
        ]
        for n in notes:
            a.append(f"- {n}")
        a.append("")
        a.append("**Hay nằm trong bundle:** " + ", ".join(bundles))
        a.append("")

    a += [
        "---",
        "",
        "## 4. Quy tắc đặt hàng SKU",
        "",
        "1. Luôn có dòng `SYS` trên báo giá.",
        "2. Nếu chọn `LOG` hoặc `MFG` → bắt buộc có `INV` cùng Phase.",
        "3. Mỗi SKU Soft nên có cột Phase (1/2) trên báo giá.",
        "4. Không đổi tên mã module trên hợp đồng (`HRM`, `CRM`…) — giữ ổn định license.",
        "",
        "---",
        "",
        "*Hết PKG-02-v1.0.*",
        "",
    ]
    return a


# =============================================================================
# PKG-03
# =============================================================================
def doc_03() -> list[str]:
    a = header(
        "PKG-03-v1.0",
        "Gói giải pháp thương mại",
        "Commercial Solution Bundles",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "Các **bundle** ghép sẵn để Presales đề xuất nhanh. Bundle = SYS + tập SKU Must + khuyến nghị Should. "
        "Có thể cắt bớt Should sang Phase 2 nếu khách chấp nhận giảm E2E.",
        "",
        "---",
        "",
        "## 2. Ký hiệu trong bảng bundle",
        "",
        "| Ký hiệu | Nghĩa |",
        "|---|---|",
        "| ● | Must — có trong báo giá Phase 1 |",
        "| ○ | Should — khuyến nghị Phase 1 hoặc ghi Phase 2 |",
        "| ◐ | Chọn 1 trong nhóm (FSM **hoặc** PJM, hoặc cả hai) |",
        "| — | Không thuộc bundle |",
        "",
        "---",
        "",
        "## 3. Ma trận Bundle × Module",
        "",
        "| Bundle \\ Module | SYS | HRM | LMS | CRM | POS | PUR | INV | LOG | MFG | FSM | PJM | FIN | AST | WF | BI | PRT |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
        "| B1 Nhân sự số | ● | ● | ○ | — | — | — | — | — | — | — | — | ○ | ○ | ○ | ○ | — |",
        "| B2 Bán hàng & phân phối | ● | — | — | ● | — | — | ● | ● | — | — | — | ● | — | ○ | ○ | ○ |",
        "| B3 Bán lẻ | ● | — | — | ○ | ● | — | ● | — | — | — | — | ● | — | — | ○ | — |",
        "| B4 Mua – Kho – SX | ● | ○ | — | ○ | — | ● | ● | ○ | ● | — | — | ● | — | ○ | ○ | — |",
        "| B5 Procure-to-Pay (không SX) | ● | — | — | — | — | ● | ● | — | — | — | — | ● | — | ○ | ○ | ○ |",
        "| B6 Dịch vụ & dự án | ● | ○ | — | ● | — | — | ○ | — | — | ◐ | ◐ | ● | — | ○ | ○ | ○ |",
        "| B7 Tài chính lõi | ● | ○ | — | ○ | ○ | ○ | ○ | ○ | — | — | — | ● | ○ | ○ | ○ | — |",
        "| B8 Enterprise starter | ● | ● | ○ | ● | ○ | ● | ● | ○ | ○ | ○ | ○ | ● | ○ | ● | ○ | ○ |",
        "",
        "---",
        "",
        "## 4. Mô tả từng bundle",
        "",
        "### 4.1. B1 — Nhân sự số",
        "",
        "| Hạng mục | Nội dung |",
        "|---|---|",
        "| Mục tiêu khách | Số hóa HSNS, công–phép, onboarding |",
        "| Must | SYS, HRM |",
        "| Should | WF (duyệt), LMS (đào tạo), FIN (chi phí lương), AST (thu hồi TS) |",
        "| Journey INT | E2E-05 Hire to Retire |",
        "| Không cam kết nếu thiếu | Post sổ lương (thiếu FIN); duyệt đa cấp (thiếu WF) |",
        "",
        "### 4.2. B2 — Bán hàng & phân phối",
        "",
        "| Hạng mục | Nội dung |",
        "|---|---|",
        "| Mục tiêu khách | Báo giá → đơn → xuất kho → giao → công nợ |",
        "| Must | SYS, CRM, INV, LOG, FIN |",
        "| Should | WF (chiết khấu/hạn mức), PRT, BI |",
        "| Journey INT | E2E-01 Lead to Cash |",
        "| Rủi ro cắt gói | Bỏ LOG → không giao vận; bỏ FIN → không AR chuẩn |",
        "",
        "### 4.3. B3 — Bán lẻ",
        "",
        "| Hạng mục | Nội dung |",
        "|---|---|",
        "| Mục tiêu khách | Bán quầy, tồn realtime, đối soát ca |",
        "| Must | SYS, POS, INV, FIN |",
        "| Should | CRM (loyalty/KM), BI |",
        "| Journey INT | E2E-03 POS Shift |",
        "",
        "### 4.4. B4 — Mua – Kho – Sản xuất",
        "",
        "| Hạng mục | Nội dung |",
        "|---|---|",
        "| Mục tiêu khách | NVL → SX → TP → giá thành khung |",
        "| Must | SYS, PUR, INV, MFG, FIN |",
        "| Should | WF, LOG, HRM (nhân công), CRM (đơn làm SX theo đơn) |",
        "| Journey INT | E2E-04 Make + một phần E2E-02 |",
        "",
        "### 4.5. B5 — Procure-to-Pay",
        "",
        "| Hạng mục | Nội dung |",
        "|---|---|",
        "| Mục tiêu khách | Mua hàng đến thanh toán NCC (không SX) |",
        "| Must | SYS, PUR, INV, FIN |",
        "| Should | WF, PRT (NCC portal — nếu product cho phép), BI |",
        "| Journey INT | E2E-02 |",
        "",
        "### 4.6. B6 — Dịch vụ & dự án",
        "",
        "| Hạng mục | Nội dung |",
        "|---|---|",
        "| Mục tiêu khách | Ticket hiện trường và/hoặc dự án có doanh thu–chi phí |",
        "| Must | SYS, CRM, FIN + (FSM và/hoặc PJM) |",
        "| Should | INV, WF, PRT, HRM, BI |",
        "| Journey INT | E2E-06 / E2E-07 |",
        "",
        "### 4.7. B7 — Tài chính lõi",
        "",
        "| Hạng mục | Nội dung |",
        "|---|---|",
        "| Mục tiêu khách | Sổ sách, AR/AP, khóa kỳ; nhận chứng từ từ module nguồn dần |",
        "| Must | SYS, FIN |",
        "| Should | Các module phát sinh chứng từ theo lộ trình; AST; WF; BI |",
        "| Journey INT | E2E-08 (+ nguồn tùy Phase) |",
        "| Lưu ý | Không bán FIN như “ERP đầy đủ” nếu thiếu module nguồn |",
        "",
        "### 4.8. B8 — Enterprise starter",
        "",
        "| Hạng mục | Nội dung |",
        "|---|---|",
        "| Mục tiêu khách | Nền tảng rộng, rollout theo wave |",
        "| Must | SYS, HRM, CRM, PUR, INV, FIN, WF |",
        "| Should / Wave 2 | POS, LOG, MFG, FSM, PJM, LMS, AST, BI, PRT |",
        "| Cách bán | Ký khung Enterprise + phụ lục wave; license bật theo wave |",
        "",
        "---",
        "",
        "## 5. Bundle theo quy mô (gợi ý)",
        "",
        "| Quy mô | Gợi ý bắt đầu | Tránh |",
        "|---|---|---|",
        "| SME nhỏ (<50 user) | 1 bundle lõi (B1 hoặc B3 hoặc B5) + SYS | B8 full ngay Day-1 |",
        "| SME vừa | 1–2 bundle giao nhau (vd B2+B5) | Mua rời thiếu INV khi có LOG |",
        "| Mid-market | B8 wave 1 + wave 2 theo roadmap | Hứa toàn bộ E2E khi Phase 1 thiếu Soft |",
        "",
        "---",
        "",
        "## 6. Template ngành (không phải SKU)",
        "",
        "| Template | Bundle gốc | Cấu hình thêm (không tạo module mới) |",
        "|---|---|---|",
        "| Phân phối | B2 | Nhóm hàng, chính sách giá, đa kho |",
        "| Bán lẻ chuỗi | B3 | Nhiều store, ca, KM |",
        "| Sản xuất rời rạc | B4 | BOM, kho NVL/TP |",
        "| Dịch vụ kỹ thuật | B6 (FSM) | SLA, kỹ năng KT |",
        "| Nhân sự tập đoàn | B1 | Nhiều pháp nhân/org_unit |",
        "",
        "> Ngành chỉ là **gói cấu hình + training**; mã license vẫn là module chuẩn.",
        "",
        "---",
        "",
        "## 7. Quy tắc chỉnh bundle cho khách",
        "",
        "1. Giữ nguyên Must; chỉ đàm phán Should.",
        "2. Mọi cắt Soft phải ghi **“không bao gồm”** trên phụ lục phạm vi.",
        "3. Không đổi mã bundle trên hợp đồng nếu nội dung Must đã đổi — tạo biến thể (`B2-Lite`) có bảng module rõ.",
        "4. Map lại INT-04 journey bị ảnh hưởng.",
        "",
        "---",
        "",
        "*Hết PKG-03-v1.0.*",
        "",
    ]
    return a


# =============================================================================
# PKG-04
# =============================================================================
def doc_04() -> list[str]:
    a = header(
        "PKG-04-v1.0",
        "License · quota · thương mại",
        "Licensing, Quotas & Commercial Terms",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "Quy định **cách license kỹ thuật phản ánh hợp đồng thương mại**: module bật/tắt, hạn mức, "
        "gia hạn, upsell/downsell. Ánh xạ CSDL: `sys.license`, `sys.license_module` (DDD-02).",
        "",
        "---",
        "",
        "## 2. Mô hình license",
        "",
        "```text",
        " Hợp đồng thương mại",
        "        │",
        "        ▼",
        " sys.license (plan, hiệu lực, max_users, status)",
        "        │",
        "        ├── license_module: SYS (always)",
        "        ├── license_module: CRM = enabled",
        "        ├── license_module: INV = enabled",
        "        └── …",
        "                │",
        "                ▼",
        "         Menu + API gateway kiểm tra",
        "```",
        "",
        "| Thuộc tính | Ý nghĩa thương mại |",
        "|---|---|",
        "| `plan_code` | Mã gói thương mại (SME / Standard / Enterprise / custom) |",
        "| `valid_from` / `valid_to` | Thời hạn thuê bao |",
        "| `max_users` | Hạn mức user active |",
        "| `license_module.is_enabled` | Module có trong hợp đồng Phase hiện tại |",
        "| `quota_json` | Hạn mức riêng (chi nhánh, store, API call…) — tùy plan |",
        "",
        "---",
        "",
        "## 3. Metric tính phí (khung — chốt bảng giá nội bộ)",
        "",
        "| Metric | Áp dụng điển hình | Ghi chú |",
        "|---|---|---|",
        "| Named user / active user | Hầu hết module | Đồng bộ `max_users` |",
        "| Module pack | Theo SKU / bundle | Đơn vị báo giá chính |",
        "| Chi nhánh / pháp nhân | org_unit loại Company/Branch | Optional add-on |",
        "| Điểm bán (store) | POS | Optional |",
        "| Concurrent device / POS terminal | POS | Optional |",
        "| API volume | Tích hợp nặng | Optional qua `api_key` policy |",
        "| Portal external user | PRT | Có thể tách quota |",
        "",
        "> Tài liệu này **không** ấn định đơn giá. Presales lấy số từ bảng giá / deal desk.",
        "",
        "---",
        "",
        "## 4. Gói plan khung (gợi ý đặt tên)",
        "",
        "| Plan | Thành phần gợi ý | Đối tượng |",
        "|---|---|---|",
        "| `PLAN_SME_HR` | ≈ Bundle B1 | SME nhân sự |",
        "| `PLAN_SME_RETAIL` | ≈ Bundle B3 | Cửa hàng / chuỗi nhỏ |",
        "| `PLAN_DISTRIBUTION` | ≈ Bundle B2 | Phân phối |",
        "| `PLAN_MANUFACTURING` | ≈ Bundle B4 | SX vừa |",
        "| `PLAN_FIN_CORE` | ≈ Bundle B7 | Kế toán lõi |",
        "| `PLAN_ENTERPRISE` | ≈ Bundle B8 + wave | Mid-market |",
        "| `PLAN_CUSTOM` | SKU lựa chọn | Deal riêng |",
        "",
        "`plan_code` trên license nên khớp một trong các mã trên (hoặc mã custom có phụ lục).",
        "",
        "---",
        "",
        "## 5. Upsell / Downsell / Gia hạn",
        "",
        "### 5.1. Upsell (bật thêm module)",
        "1. Ký phụ lục / SOW.",
        "2. Cập nhật `license_module` = enabled.",
        "3. Seed permission/sequence/menu module (job SYS).",
        "4. Delivery cấu hình master tối thiểu + training.",
        "5. Không xóa/không migrate phá dữ liệu cũ.",
        "",
        "### 5.2. Downsell (tắt module)",
        "1. Kiểm tra hard dependents còn bật không (INT-02 / PKG-02).",
        "2. Nếu còn → **chặn downsell** hoặc bắt tắt cả chuỗi phụ thuộc.",
        "3. Set `is_enabled = false`; UI/API module bị chặn.",
        "4. Dữ liệu giữ; export nếu hợp đồng yêu cầu.",
        "5. Audit + thông báo admin.",
        "",
        "### 5.3. Gia hạn / hết hạn",
        "| Trạng thái | Hành vi gợi ý (chốt khi triển khai) |",
        "|---|---|",
        "| Sắp hết hạn (T-30…T-7) | Cảnh báo admin |",
        "| Hết hạn | Read-only hoặc block login theo chính sách plan |",
        "| SYS hết hạn | Áp dụng toàn tenant |",
        "",
        "---",
        "",
        "## 6. Điều khoản thương mại khung (checklist hợp đồng)",
        "",
        "1. Danh sách module Must Phase 1 (mã SKU).",
        "2. Module Should Phase 2 (nếu có) + điều kiện kích hoạt.",
        "3. Thời hạn, số user, số chi nhánh/store (nếu áp dụng).",
        "4. Môi trường: Production (+ UAT?).",
        "5. Chính sách dữ liệu khi chấm dứt: giữ / export / xóa sau N ngày.",
        "6. Phụ thuộc cứng đã được khách xác nhận (ký).",
        "7. Phạm vi **không bao gồm** (soft đã cắt).",
        "8. SLA hỗ trợ (tham chiếu hợp đồng dịch vụ — ngoài PKG).",
        "",
        "---",
        "",
        "## 7. Ánh xạ vận hành kỹ thuật",
        "",
        "| Sự kiện thương mại | Hành vi hệ thống |",
        "|---|---|",
        "| Ký mới | Tạo tenant + license + admin đầu tiên |",
        "| Bật module | Enable license_module; hiện menu |",
        "| Tắt module | Chặn API/UI; subscriber degrade (INT-05) |",
        "| Tăng user | Tăng `max_users`; chặn tạo user khi vượt |",
        "| Đổi plan | Cập nhật plan_code + module set |",
        "",
        "---",
        "",
        "## 8. Truy vết",
        "",
        "| Liên quan | Tài liệu |",
        "|---|---|",
        "| Nguyên tắc đóng gói | PKG-01 |",
        "| SKU | PKG-02 |",
        "| Bundle | PKG-03 |",
        "| Tắt license kỹ thuật | INT-02 §5, INT-05 |",
        "| Bảng DB | DDD-02 / DDD-MASTER |",
        "",
        "---",
        "",
        "*Hết PKG-04-v1.0.*",
        "",
    ]
    return a


# =============================================================================
# PKG-05
# =============================================================================
def doc_05() -> list[str]:
    a = header(
        "PKG-05-v1.0",
        "Playbook Presales → Delivery",
        "Sales & Delivery Playbook for Packaged ERP",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "Playbook vận hành từ **discovery → báo giá → ký → kickoff → nghiệm thu Phase 1** theo đúng gói đã bán, "
        "tránh lệch scope giữa Sales và Delivery.",
        "",
        "---",
        "",
        "## 2. Luồng tổng thể",
        "",
        "```text",
        " Discovery → Chọn Bundle/SKU → Xác nhận Must/Should",
        "     → Demo đúng phạm vi → Báo giá / phụ lục",
        "     → Ký HĐ → Kickoff Delivery",
        "     → Cấu hình & UAT theo Phase 1",
        "     → Go-live → Chăm sóc / Upsell Phase 2",
        "```",
        "",
        "---",
        "",
        "## 3. Checklist Presales (trước báo giá)",
        "",
        "| # | Hạng mục | Kết quả cần có |",
        "|---|---|---|",
        "| 1 | Ngành / mô hình kinh doanh | Template ngành (PKG-03 §6) |",
        "| 2 | Hành trình Must | Map INT-04 (E2E-xx) |",
        "| 3 | Bundle đề xuất | B1…B8 hoặc CUSTOM |",
        "| 4 | Hard dependency | Đủ INV nếu có LOG/MFG… |",
        "| 5 | Soft cắt bỏ | Ghi “không bao gồm” |",
        "| 6 | Quy mô user / CN / store | Metric PKG-04 |",
        "| 7 | Cần portal / BI Day-1? | Quyết định PRT/BI |",
        "| 8 | Duyệt tập trung? | WF Phase 1 hay không |",
        "| 9 | Master dữ liệu | Ai sở hữu KH/Hàng/NV |",
        "| 10 | Wave rollout | Enterprise mới dùng B8 |",
        "",
        "---",
        "",
        "## 4. Checklist Demo",
        "",
        "1. Demo **đúng module trong báo giá** — không demo Soft đã cắt như là đã mua.",
        "2. Nêu rõ bước nào cần module Should (vd giao hàng cần LOG).",
        "3. Login bằng role thật (không chỉ admin bypass).",
        "4. Chỉ menu theo license giả lập gói đang bán.",
        "5. Kết thúc demo: chốt danh sách Must/Should với khách (biên bản ngắn).",
        "",
        "---",
        "",
        "## 5. Hồ sơ bàn giao Sales → Delivery",
        "",
        "| Tài liệu | Bắt buộc |",
        "|---|---|",
        "| Phụ lục module Phase 1 (mã SKU) | Yes |",
        "| Phụ lục Phase 2 / option | Nếu có |",
        "| Bundle code / plan_code | Yes |",
        "| Danh sách “không bao gồm” | Yes |",
        "| Biên bản hard dependency | Yes |",
        "| Kỳ vọng journey E2E | Yes (mã INT-04) |",
        "| Ước lượng user / CN | Yes |",
        "| Đầu mối khách (IT/KT/Ops) | Yes |",
        "",
        "---",
        "",
        "## 6. Kickoff kỹ thuật (Delivery)",
        "",
        "1. Tạo/gán tenant + license đúng phụ lục.",
        "2. Enable đúng `license_module`.",
        "3. Khởi tạo org_unit, department, job_level, admin, role mẫu gói.",
        "4. Import master tối thiểu theo module Must.",
        "5. Cấu hình WF (nếu có), sequence, setting.",
        "6. UAT theo kịch bản journey Phase 1 — **không** UAT Soft đã cắt.",
        "7. Đào tạo theo vai trò trong phạm vi gói.",
        "8. Go-live checklist: INT-05 § go-live tích hợp (nếu đa module).",
        "",
        "---",
        "",
        "## 7. Tiêu chí nghiệm thu gói Phase 1",
        "",
        "| # | Tiêu chí |",
        "|---|---|",
        "| 1 | Đủ module Must trên license & menu |",
        "| 2 | Không còn phụ thuộc cứng thiếu |",
        "| 3 | Journey Must chạy UAT đạt (theo biên bản) |",
        "| 4 | Phân quyền mẫu (Role/Permission/Department/JobLevel) hoạt động |",
        "| 5 | Tắt thử 1 soft module (nếu có) không làm sập Must path |",
        "| 6 | Khách ký biên bản nghiệm thu phạm vi Phase 1 |",
        "",
        "---",
        "",
        "## 8. After go-live / Upsell",
        "",
        "| Tín hiệu | Đề xuất add-on |",
        "|---|---|",
        "| KH hỏi tracking đơn / công nợ self-service | PRT |",
        "| Cần dashboard C-level | BI |",
        "| Duyệt chồng chéo nhiều chứng từ | WF |",
        "| Có xuất kho giao khách | LOG (+ đủ INV) |",
        "| Mở nhà máy | MFG |",
        "| Chuỗi cửa hàng | POS |",
        "",
        "Quy trình upsell tuân PKG-04 §5.1.",
        "",
        "---",
        "",
        "## 9. Rủi ro thường gặp & cách tránh",
        "",
        "| Rủi ro | Cách tránh |",
        "|---|---|",
        "| Bán thiếu INV khi có LOG/MFG | Gate bắt buộc trên báo giá (PKG-02) |",
        "| Demo vượt phạm vi → khách tưởng đã mua | Script demo theo license giả lập |",
        "| Delivery làm Soft “cho đủ” ngoài HĐ | Scope freeze theo phụ lục |",
        "| Downsell phá E2E đang chạy | Kiểm hard dependents (PKG-04) |",
        "| Hai nguồn master (KH/Hàng) | Chốt owner theo INT-01 / kickoff |",
        "",
        "---",
        "",
        "## 10. Truy vết",
        "",
        "| Liên quan | Tài liệu |",
        "|---|---|",
        "| Chiến lược | PKG-01 |",
        "| SKU / Bundle / License | PKG-02…04 |",
        "| Phụ thuộc & journey | INT-02, INT-04 |",
        "| SRS chức năng | `../01. Modules` |",
        "",
        "---",
        "",
        "*Hết PKG-05-v1.0.*",
        "",
    ]
    return a


def export_docx(md_path: Path) -> None:
    out = md_path.with_suffix(".docx")
    meta = extract_meta_from_md(md_path)
    # extract_meta looks for SRS-XXX — override for PKG
    stem = md_path.stem  # PKG-01_...
    code = stem.split("_")[0]  # PKG-01
    meta.update(
        {
            "org": "ERP MODULAR PRODUCT",
            "doc_family_en": "PRODUCT PACKAGING DOCUMENT",
            "doc_family_vi": "TÀI LIỆU GÓI BÁN HÀNG / ĐÓNG GÓI SẢN PHẨM",
            "doc_code": f"{code}-v1.0",
            "module_code": "PKG",
            "module_label": "Bộ tài liệu",
            "module_name": "Gói bán hàng",
            "version": "1.0",
            "status": "Chờ duyệt — Gói bán hàng / Presales",
            "classification": "Nội bộ dự án — Presales / BA / Delivery",
            "footer_note": "Tài liệu đóng gói thương mại — dùng trước báo giá và kickoff triển khai.",
            "subtitle": "Product Packaging & Commercial Catalog — Modular ERP",
            "history": [
                ["1.0", TODAY, "Presales / BA", "Khởi tạo bộ Gói bán hàng", "Chờ duyệt"],
            ],
        }
    )
    # Title from H1
    text = md_path.read_text(encoding="utf-8")
    import re

    m = re.search(r"^#\s+.+?—\s+(.+)$", text, re.M)
    if m:
        meta["title"] = m.group(1).strip()
    build(md_path, out, meta=meta)


def main() -> None:
    docs = [
        ("PKG-01_Chien_luoc_nguyen_tac_dong_goi.md", doc_01),
        ("PKG-02_Catalog_SKU_module.md", doc_02),
        ("PKG-03_Goi_giai_phap_thuong_mai.md", doc_03),
        ("PKG-04_License_quota_thuong_mai.md", doc_04),
        ("PKG-05_Playbook_Presales_Delivery.md", doc_05),
    ]
    for name, fn in docs:
        path = ROOT / name
        write(path, fn())
        export_docx(path)
    print("All PKG docs done.")


if __name__ == "__main__":
    main()
