# -*- coding: utf-8 -*-
"""Cây chức năng ERP generic — bán theo module."""

TREE = {
    "SYS": [
        ("01", "Xác thực & phiên làm việc", [
            ("Đăng nhập hệ thống", "Username/email/SĐT + password auth", "Bắt buộc"),
            ("Đăng xuất", "Revoke session token", "Bắt buộc"),
            ("Đổi mật khẩu", "Change password with old password check", "Bắt buộc"),
            ("Quên mật khẩu – gửi OTP/link", "Reset via email/SMS", "Bắt buộc"),
            ("Đặt lại mật khẩu sau OTP", "Set new password after verification", "Bắt buộc"),
            ("Chính sách độ mạnh mật khẩu", "Length, complexity, history", "Bắt buộc"),
            ("Khóa tài khoản sau N lần sai", "Brute-force protection", "Bắt buộc"),
            ("Xác thực 2 bước (2FA)", "TOTP / SMS OTP", "Cao"),
            ("Đăng nhập SSO / OAuth", "Google, Microsoft, OIDC", "Trung bình"),
            ("Quản lý phiên đang hoạt động", "Active sessions, device list, revoke", "Cao"),
            ("Giới hạn số phiên đồng thời", "Concurrent session limit", "Cao"),
            ("Ghi nhớ thiết bị tin cậy", "Trusted device, skip 2FA", "Thấp"),
        ]),
        ("02", "Người dùng", [
            ("Tạo người dùng", "Create user account", "Bắt buộc"),
            ("Cập nhật thông tin người dùng", "Name, phone, email, avatar", "Bắt buộc"),
            ("Khóa / mở khóa người dùng", "Disable/enable login", "Bắt buộc"),
            ("Xóa mềm người dùng", "Soft delete user", "Bắt buộc"),
            ("Gán người dùng vào chi nhánh", "Default org unit", "Bắt buộc"),
            ("Reset mật khẩu bởi Admin", "Admin password reset with audit", "Bắt buộc"),
            ("Mời người dùng qua email", "Invitation link", "Cao"),
            ("Import danh sách người dùng Excel", "Bulk user creation", "Cao"),
            ("Tìm kiếm / lọc người dùng", "By role, branch, status", "Bắt buộc"),
            ("Xuất danh sách người dùng", "Export user list", "Cao"),
        ]),
        ("03", "Vai trò & phân quyền", [
            ("Tạo / sửa / ngưng vai trò (Role)", "Role master data", "Bắt buộc"),
            ("Sao chép vai trò", "Clone role with permissions", "Cao"),
            ("Quản lý danh mục quyền (Permission)", "Permission catalog", "Bắt buộc"),
            ("Gán quyền vào vai trò", "Role-Permission matrix", "Bắt buộc"),
            ("Gán người dùng vào vai trò", "Multi-role assignment", "Bắt buộc"),
            ("Phân quyền dữ liệu theo chi nhánh", "Org-level data scope", "Bắt buộc"),
            ("Phân quyền dữ liệu theo kho / điểm", "Location data scope", "Bắt buộc"),
            ("Phân quyền theo phòng ban", "Department data scope", "Cao"),
            ("Quyền theo trường nhạy cảm", "Field-level security", "Cao"),
            ("Xem ma trận phân quyền tổng hợp", "Permission report", "Cao"),
            ("Nhật ký thay đổi phân quyền", "Permission audit log", "Bắt buộc"),
        ]),
        ("04", "Tổ chức & đa chi nhánh", [
            ("Quản lý công ty / tenant", "Tenant info management", "Bắt buộc"),
            ("Quản lý pháp nhân / công ty con", "Multi-company", "Cao"),
            ("Quản lý chi nhánh", "Branch hierarchy", "Bắt buộc"),
            ("Quản lý điểm bán / cửa hàng", "Store/outlet master", "Bắt buộc"),
            ("Quản lý phòng ban", "Department org chart", "Bắt buộc"),
            ("Quản lý chức danh", "Job title master", "Bắt buộc"),
            ("Sơ đồ tổ chức trực quan", "Visual org chart", "Cao"),
            ("Cấu hình múi giờ / ngôn ngữ / tiền tệ", "Localization settings", "Bắt buộc"),
            ("Cấu hình định dạng ngày số", "Date/number format", "Cao"),
            ("Quản lý địa chỉ / tỉnh thành", "Location master data", "Bắt buộc"),
        ]),
        ("05", "License & module bán hàng", [
            ("Khai báo module trong hệ thống", "Module catalog", "Bắt buộc"),
            ("Bật / tắt module theo tenant", "License enforcement", "Bắt buộc"),
            ("Quản lý gói license", "License packages", "Bắt buộc"),
            ("Giới hạn số user / chi nhánh theo gói", "Quota management", "Bắt buộc"),
            ("Cảnh báo / gia hạn license", "License expiry alerts", "Bắt buộc"),
            ("Menu động theo module + quyền", "Dynamic menu rendering", "Bắt buộc"),
            ("Ẩn API module chưa mua", "License-based API access", "Bắt buộc"),
        ]),
        ("06", "Cấu hình hệ thống", [
            ("Tham số cấu hình toàn cục", "Global key-value settings", "Bắt buộc"),
            ("Cấu hình theo chi nhánh", "Branch-level override", "Cao"),
            ("Danh mục dùng chung", "UOM, currency, status codes", "Bắt buộc"),
            ("Mẫu số chứng từ", "Document numbering rules", "Bắt buộc"),
            ("Sinh mã tự động", "Sequence generator", "Bắt buộc"),
            ("Cấu hình mẫu email / SMS", "Notification templates", "Bắt buộc"),
            ("Cấu hình lịch làm việc", "Working calendar, holidays", "Cao"),
            ("Quản lý phiên bản cấu hình", "Configuration versioning", "Trung bình"),
        ]),
        ("07", "Thông báo", [
            ("Thông báo in-app", "Notification center", "Bắt buộc"),
            ("Gửi email hệ thống", "SMTP/gateway integration", "Bắt buộc"),
            ("Gửi SMS / messaging", "SMS/messaging gateway", "Cao"),
            ("Push notification mobile", "FCM/APNs push", "Cao"),
            ("Cấu hình sự kiện kích hoạt", "Event-to-channel mapping", "Bắt buộc"),
            ("Tùy chọn thông báo cá nhân", "User notification preferences", "Trung bình"),
            ("Nhật ký gửi thông báo", "Notification delivery log", "Cao"),
        ]),
        ("08", "File & tài liệu", [
            ("Upload file", "File upload with restrictions", "Bắt buộc"),
            ("Tải xuống / xem trước file", "Download/preview", "Bắt buộc"),
            ("Quản lý thư mục tài liệu", "Folder structure", "Cao"),
            ("Phân quyền file theo đối tượng", "File-level permissions", "Cao"),
            ("Xóa mềm / khôi phục file", "Soft delete/trash", "Cao"),
            ("Quét virus / bảo mật file", "Security scanning", "Trung bình"),
        ]),
        ("09", "Import / Export", [
            ("Import Excel/CSV theo mẫu", "Template-based import", "Bắt buộc"),
            ("Tải file mẫu import", "Download templates", "Bắt buộc"),
            ("Export Excel", "Filtered data export", "Bắt buộc"),
            ("Export PDF", "Document/report PDF", "Bắt buộc"),
            ("Lịch sử job import/export", "Job tracking", "Cao"),
            ("Xuất dữ liệu hàng loạt", "Bulk data export", "Trung bình"),
        ]),
        ("10", "Audit & bảo mật", [
            ("Nhật ký thao tác người dùng", "CRUD audit trail", "Bắt buộc"),
            ("Nhật ký đăng nhập / thất bại", "Login security log", "Bắt buộc"),
            ("Xem chi tiết thay đổi field", "Field-level audit", "Cao"),
            ("Xuất audit log", "Export for compliance", "Cao"),
            ("Quản lý IP allow/deny", "Network access policy", "Thấp"),
            ("Chính sách hết hạn phiên", "Session timeout", "Bắt buộc"),
        ]),
        ("11", "Tích hợp nền tảng", [
            ("Quản lý API Key", "API key management", "Cao"),
            ("Quản lý Webhook outbound", "Outbound event webhooks", "Cao"),
            ("Nhật ký gọi API / webhook", "API/webhook logs", "Cao"),
            ("Hàng đợi sự kiện liên module", "Internal event bus", "Bắt buộc"),
            ("Kết nối email gateway", "Email provider setup", "Bắt buộc"),
            ("Kết nối SMS gateway", "SMS provider setup", "Cao"),
            ("Cấu hình tích hợp bên ngoài", "External connector registry", "Cao"),
        ]),
        ("12", "Đa ngôn ngữ & giao diện", [
            ("Quản lý gói ngôn ngữ", "Language packs", "Cao"),
            ("Đổi ngôn ngữ giao diện", "User locale settings", "Cao"),
            ("Tùy chỉnh theme / logo", "Tenant branding", "Trung bình"),
            ("Trang chủ theo vai trò", "Role-based landing", "Trung bình"),
        ]),
        ("13", "Nhắn tin realtime", [
            ("Tạo hội thoại 1-1", "Direct conversation", "Bắt buộc"),
            ("Tạo hội thoại nhóm", "Group conversation", "Cao"),
            ("Gửi tin nhắn realtime", "Send chat message", "Bắt buộc"),
            ("Nhận tin nhắn realtime (SignalR)", "Receive via SignalR", "Bắt buộc"),
            ("Xem lịch sử hội thoại", "Conversation history", "Bắt buộc"),
            ("Đánh dấu đã đọc / badge chưa đọc", "Read receipt & unread badge", "Bắt buộc"),
            ("Đính kèm file trong tin nhắn", "Message attachments", "Cao"),
            ("Thu hồi tin nhắn", "Recall message", "Cao"),
            ("Tìm kiếm tin nhắn", "Search messages", "Trung bình"),
            ("Tắt thông báo hội thoại", "Mute conversation", "Trung bình"),
        ]),
    ],
    "HRM": [
        ("01", "Cơ cấu tổ chức nhân sự", [
            ("Tạo sơ đồ tổ chức công ty", "Company org structure", "Bắt buộc"),
            ("Quản lý khối vận hành", "Operating divisions", "Bắt buộc"),
            ("Quản lý khối sản xuất", "Manufacturing divisions", "Bắt buộc"),
            ("Quản lý danh mục điểm bán", "Sales location master", "Bắt buộc"),
            ("Quản lý bộ phận trong đơn vị", "Department within unit", "Cao"),
            ("Khai báo giờ làm việc theo đơn vị", "Working hours by unit", "Bắt buộc"),
            ("Quản lý chức danh nhân sự", "Position titles", "Bắt buộc"),
            ("Quản lý vị trí công việc", "Job positions", "Cao"),
            ("Quản lý loại nhân sự", "Employee types", "Bắt buộc"),
            ("Quản lý cấp bậc / level", "Grade/level master", "Cao"),
            ("Định nghĩa trung tâm chi phí NS", "HR cost centers", "Cao"),
        ]),
        ("02", "Hồ sơ nhân sự", [
            ("Sinh mã nhân sự tự động", "Auto employee ID", "Bắt buộc"),
            ("Tạo hồ sơ nhân sự mới", "Create employee record", "Bắt buộc"),
            ("Cập nhật thông tin cá nhân", "Personal info update", "Bắt buộc"),
            ("NV tự cập nhật hồ sơ", "Self-service profile", "Cao"),
            ("Upload ảnh đại diện", "Profile photo", "Trung bình"),
            ("Upload giấy tờ tùy thân", "ID documents", "Bắt buộc"),
            ("Gắn nhân sự vào đơn vị chính", "Primary org assignment", "Bắt buộc"),
            ("Gắn nhân sự vào bộ phận", "Department assignment", "Bắt buộc"),
            ("Gắn chức danh / level", "Position & grade", "Bắt buộc"),
            ("Gắn loại nhân sự", "Employee classification", "Bắt buộc"),
            ("Gắn nhiều nhãn hồ sơ", "Employee tags", "Cao"),
            ("Quản lý người thân / liên hệ khẩn", "Emergency contacts", "Cao"),
            ("Quản lý trình độ / kỹ năng", "Skills & qualifications", "Trung bình"),
            ("Tìm kiếm nhân sự đa tiêu chí", "Advanced employee search", "Bắt buộc"),
            ("Xuất danh sách nhân sự Excel", "Export employee list", "Bắt buộc"),
            ("Khóa hồ sơ đã nghỉ", "Lock terminated records", "Bắt buộc"),
            ("Xem hồ sơ theo quyền", "Field-level security", "Bắt buộc"),
        ]),
        ("03", "Trạng thái & biến động nhân sự", [
            ("Chuyển trạng thái Thử việc", "Probation status", "Bắt buộc"),
            ("Chuyển trạng thái Chính thức", "Regular status", "Bắt buộc"),
            ("Chuyển trạng thái Tạm nghỉ", "Temporary leave", "Cao"),
            ("Chuyển trạng thái Nghỉ việc", "Termination", "Bắt buộc"),
            ("Lịch sử thay đổi trạng thái", "Status timeline", "Bắt buộc"),
            ("Điều chuyển đơn vị / bộ phận", "Internal transfer", "Bắt buộc"),
            ("Thăng chức / đổi chức danh", "Promotion/demotion", "Bắt buộc"),
            ("Cảnh báo sắp hết hạn thử việc", "Probation end reminder", "Bắt buộc"),
            ("Báo cáo biến động nhân sự", "Headcount movement report", "Cao"),
        ]),
        ("04", "Hợp đồng lao động", [
            ("Tạo hợp đồng lao động", "Create employment contract", "Bắt buộc"),
            ("Tạo phụ lục hợp đồng", "Contract addendum", "Bắt buộc"),
            ("Upload bản scan hợp đồng", "Contract file attachment", "Bắt buộc"),
            ("Gia hạn hợp đồng", "Contract renewal", "Bắt buộc"),
            ("Thanh lý / chấm dứt hợp đồng", "Contract termination", "Bắt buộc"),
            ("Cảnh báo hết hạn hợp đồng", "Contract expiry alert", "Bắt buộc"),
            ("In / xuất mẫu hợp đồng", "Contract template", "Cao"),
            ("Quản lý lương hợp đồng", "Contract salary", "Bắt buộc"),
            ("Lịch sử hợp đồng theo nhân sự", "Contract history", "Bắt buộc"),
        ]),
        ("05", "Tuyển dụng – nhu cầu", [
            ("Tạo phiếu đề xuất tuyển dụng", "Recruitment requisition", "Bắt buộc"),
            ("Chọn vị trí & số lượng cần tuyển", "Headcount request", "Bắt buộc"),
            ("Nhập lý do tuyển dụng", "Recruitment reason", "Bắt buộc"),
            ("Gửi phiếu đề xuất đi duyệt", "Submit for approval", "Bắt buộc"),
            ("Duyệt / từ chối đề xuất", "Approval workflow", "Bắt buộc"),
            ("Xem lịch sử duyệt đề xuất", "Approval history", "Cao"),
            ("Đóng / hủy phiếu đề xuất", "Close requisition", "Cao"),
        ]),
        ("06", "Tuyển dụng – đăng tin & ứng viên", [
            ("Tạo tin tuyển từ phiếu đã duyệt", "Job posting", "Bắt buộc"),
            ("Ghi nhận kênh đăng tuyển", "Recruitment channel log", "Cao"),
            ("Nhập hồ sơ ứng viên", "Candidate entry", "Bắt buộc"),
            ("Upload file CV", "CV attachment", "Bắt buộc"),
            ("Import ứng viên hàng loạt", "Bulk candidate import", "Trung bình"),
            ("Sơ loại ứng viên", "Candidate screening", "Bắt buộc"),
            ("Chuyển ứng viên cho đơn vị đánh giá", "Assign to hiring manager", "Bắt buộc"),
            ("Form đánh giá ứng viên", "Interview scorecard", "Bắt buộc"),
            ("Từ chối / chấp nhận ứng viên", "Hiring decision", "Bắt buộc"),
            ("Pipeline trạng thái ứng viên", "Recruitment pipeline", "Bắt buộc"),
            ("Lịch sử chăm sóc ứng viên", "Candidate communication log", "Cao"),
            ("Báo cáo hiệu quả kênh tuyển", "Source effectiveness", "Cao"),
        ]),
        ("07", "Onboarding", [
            ("Cấu hình thời hạn onboarding", "Onboarding period setup", "Bắt buộc"),
            ("Cấu hình thời hạn thử việc", "Probation period setup", "Bắt buộc"),
            ("Tạo hồ sơ nhân viên mới từ ứng viên", "New hire from candidate", "Bắt buộc"),
            ("Gán người hướng dẫn", "Assign buddy/mentor", "Cao"),
            ("Checklist onboarding", "Onboarding tasks", "Bắt buộc"),
            ("Upload chứng chỉ / giấy tờ", "Required documents", "Bắt buộc"),
            ("Đánh giá kết thúc thử việc", "Probation evaluation", "Bắt buộc"),
            ("Chuyển thử việc thành chính thức", "Confirmation", "Bắt buộc"),
            ("Cảnh báo hết hạn thử việc", "Probation end alert", "Bắt buộc"),
        ]),
        ("08", "Định biên", [
            ("Khai báo định biên theo đơn vị", "Headcount plan by unit", "Bắt buộc"),
            ("Khai báo định biên theo ca", "Headcount by shift", "Bắt buộc"),
            ("Khai báo định biên theo bộ phận", "Headcount by department", "Cao"),
            ("So sánh thực tế vs định biên", "Headcount gap analysis", "Bắt buộc"),
            ("Cảnh báo thiếu người", "Understaffing alert", "Bắt buộc"),
            ("Duyệt thay đổi định biên", "Headcount change approval", "Cao"),
        ]),
        ("09", "Ca làm việc", [
            ("Tạo mẫu ca làm việc", "Shift templates", "Bắt buộc"),
            ("Xếp lịch ca nhân viên", "Shift scheduling", "Bắt buộc"),
            ("Xếp lịch ca theo tuần / tháng", "Calendar view", "Bắt buộc"),
            ("Đổi ca giữa nhân viên", "Shift swap", "Cao"),
            ("Hủy lịch ca", "Cancel shift assignment", "Bắt buộc"),
            ("Xem lịch ca theo đơn vị", "Manager shift view", "Bắt buộc"),
            ("Xem lịch ca cá nhân trên APP", "Employee shift view", "Bắt buộc"),
            ("Import lịch ca Excel", "Bulk shift import", "Trung bình"),
            ("Sao chép lịch ca", "Copy shift schedule", "Cao"),
            ("Khóa sổ lịch ca theo kỳ", "Lock shift roster", "Cao"),
            ("In / xuất lịch ca", "Export shift schedule", "Cao"),
        ]),
        ("10", "Điều động nhân sự", [
            ("Tạo lệnh điều động", "Secondment order", "Cao"),
            ("Đề xuất nhu cầu điều động", "Secondment request", "Cao"),
            ("Nhận lệnh điều động trên APP", "Accept assignment", "Cao"),
            ("Theo dõi nhân sự điều động", "Secondment tracking", "Cao"),
            ("Gắn nhãn công điều động khi chấm", "Secondment attendance tag", "Cao"),
            ("Báo cáo giờ / chi phí điều động", "Secondment cost report", "Cao"),
        ]),
        ("11", "Cấu hình chấm công", [
            ("Cấu hình chấm vân tay / sinh trắc", "Biometric settings", "Bắt buộc"),
            ("Cấu hình chấm APP điện thoại", "Mobile punch settings", "Bắt buộc"),
            ("Cấu hình chấm QR / mã nhân sự", "QR code punch", "Cao"),
            ("Đăng ký thiết bị chấm", "Time clock registration", "Bắt buộc"),
            ("Cấu hình geo-fence điểm chấm", "GPS-based attendance", "Cao"),
            ("Cấu hình quy tắc đi trễ", "Late arrival rules", "Bắt buộc"),
            ("Cấu hình mức trừ công khi trễ", "Late penalty rules", "Bắt buộc"),
            ("Cấu hình quên check-out", "Missing checkout handling", "Bắt buộc"),
            ("Cấu hình thời hạn xin điều chỉnh", "Adjustment request window", "Bắt buộc"),
            ("Cấu hình làm thêm giờ (OT)", "Overtime rules", "Cao"),
            ("Cấu hình ca đêm / ngày lễ", "Special shift rates", "Cao"),
        ]),
        ("12", "Thực hiện chấm công", [
            ("Check-in đầu ca", "Clock in", "Bắt buộc"),
            ("Check-out cuối ca", "Clock out", "Bắt buộc"),
            ("Xem lịch sử chấm cá nhân", "My attendance", "Bắt buộc"),
            ("Bảng chấm công theo đơn vị", "Unit timesheet", "Bắt buộc"),
            ("Bảng chấm công toàn công ty", "Company timesheet", "Bắt buộc"),
            ("Cảnh báo thiếu chấm realtime", "Missing punch alert", "Cao"),
            ("Tự tính phút đi trễ", "Auto late calculation", "Bắt buộc"),
            ("Tự trừ công do đi trễ", "Auto attendance deduction", "Bắt buộc"),
            ("Đánh dấu quên chấm", "Missing punch flag", "Bắt buộc"),
            ("Đồng bộ dữ liệu từ máy chấm", "Time clock sync", "Bắt buộc"),
            ("Xử lý công OT tự động", "OT auto recognition", "Cao"),
        ]),
        ("13", "Điều chỉnh & khóa công", [
            ("Tạo phiếu xin điều chỉnh công", "Attendance adjustment request", "Bắt buộc"),
            ("Đính kèm lý do / bằng chứng", "Evidence attachment", "Bắt buộc"),
            ("Duyệt / từ chối điều chỉnh", "Approve adjustment", "Bắt buộc"),
            ("Ghi nhận vi phạm đi trễ", "Violation log", "Cao"),
            ("Lập bảng phạt", "Penalty calculation", "Cao"),
            ("Áp dụng phạt vào kỳ lương", "Link penalty to payroll", "Cao"),
            ("Khóa bảng công theo kỳ", "Lock timesheet period", "Bắt buộc"),
            ("Mở khóa bảng công có kiểm soát", "Unlock with approval", "Bắt buộc"),
            ("Xác nhận bảng công", "Timesheet acknowledgment", "Cao"),
        ]),
        ("14", "Nghỉ phép & vắng mặt", [
            ("Danh mục loại nghỉ", "Leave types", "Bắt buộc"),
            ("Cấu hình quỹ phép theo loại NS", "Leave balance rules", "Bắt buộc"),
            ("Cấp phát / điều chỉnh quỹ phép", "Grant leave days", "Bắt buộc"),
            ("Tạo đơn xin nghỉ", "Leave request", "Bắt buộc"),
            ("Duyệt đơn nghỉ đa cấp", "Leave approval workflow", "Bắt buộc"),
            ("Hủy đơn nghỉ", "Cancel leave", "Cao"),
            ("Xem quỹ phép còn lại", "Leave balance view", "Bắt buộc"),
            ("Lịch nghỉ theo đơn vị", "Team leave calendar", "Cao"),
            ("Import nghỉ lễ / ngày nghỉ", "Holiday calendar", "Bắt buộc"),
            ("Báo cáo nghỉ / quỹ phép", "Leave report", "Cao"),
        ]),
        ("15", "Kỷ luật & khen thưởng", [
            ("Ghi nhận quyết định khen thưởng", "Reward record", "Cao"),
            ("Ghi nhận quyết định kỷ luật", "Discipline record", "Cao"),
            ("Đính kèm quyết định", "Decision document", "Cao"),
            ("Ảnh hưởng lương / phụ cấp", "Link to payroll", "Cao"),
            ("Báo cáo khen thưởng – kỷ luật", "Reward/discipline report", "Trung bình"),
        ]),
        ("16", "Offboarding / nghỉ việc", [
            ("Tạo đơn nghỉ việc", "Resignation form", "Bắt buộc"),
            ("Cấu hình / kiểm tra báo trước", "Notice period", "Bắt buộc"),
            ("Duyệt đơn nghỉ việc", "Exit approval", "Bắt buộc"),
            ("Checklist bàn giao", "Handover checklist", "Bắt buộc"),
            ("Thu hồi quyền hệ thống", "Disable system access", "Bắt buộc"),
            ("Quyết toán phép / lương nghỉ việc", "Final pay calculation", "Bắt buộc"),
            ("Phỏng vấn nghỉ việc", "Exit interview", "Trung bình"),
            ("Báo cáo nghỉ việc / lý do", "Turnover analysis", "Cao"),
        ]),
        ("17", "Cấu hình lương & phụ cấp", [
            ("Tạo thang bậc lương", "Salary grade structure", "Bắt buộc"),
            ("Gán bậc lương theo nhân sự", "Salary assignment", "Bắt buộc"),
            ("Gán bậc theo trạng thái", "Salary by status", "Bắt buộc"),
            ("Đơn giá giờ / ngày nhân viên", "Hourly/daily rate", "Bắt buộc"),
            ("Quản lý lương thực tế chi trả", "Actual pay rate", "Bắt buộc"),
            ("Danh mục phụ cấp", "Allowance master", "Bắt buộc"),
            ("Rule phụ cấp theo ca", "Shift allowance rules", "Bắt buộc"),
            ("Rule phụ cấp đặc thù", "Special allowance rules", "Cao"),
            ("Cấu hình bảo hiểm", "Insurance rates", "Bắt buộc"),
            ("Cấu hình thuế TNCN", "Personal income tax", "Bắt buộc"),
            ("Cấu hình tạm ứng / khấu trừ", "Deduction types", "Bắt buộc"),
        ]),
        ("18", "Tính lương & chi trả", [
            ("Tạo kỳ lương", "Payroll period", "Bắt buộc"),
            ("Tổng hợp công vào kỳ lương", "Import attendance", "Bắt buộc"),
            ("Tính lương tự động theo rule", "Payroll calculation engine", "Bắt buộc"),
            ("Nhập thưởng / phụ cấp phát sinh", "Manual additions", "Bắt buộc"),
            ("Nhập khấu trừ / tạm ứng", "Manual deductions", "Bắt buộc"),
            ("Xem / chỉnh bảng lương chi tiết", "Payslip review", "Bắt buộc"),
            ("Xác nhận bảng lương", "Payroll approval", "Bắt buộc"),
            ("Khóa kỳ lương", "Lock payroll period", "Bắt buộc"),
            ("Phiếu lương cá nhân (APP)", "Employee payslip view", "Bắt buộc"),
            ("Xuất bảng lương tổng hợp", "Payroll summary export", "Bắt buộc"),
            ("Xuất file chi lương ngân hàng", "Bank transfer file", "Bắt buộc"),
            ("Đồng bộ bút toán lương sang FIN", "GL posting", "Cao"),
            ("Báo cáo chi phí lương theo đơn vị", "Labor cost by unit", "Bắt buộc"),
            ("So sánh lương kỳ này / kỳ trước", "Period variance", "Cao"),
        ]),
        ("19", "Đánh giá hiệu suất", [
            ("Mẫu đánh giá KPI / năng lực", "Performance review template", "Trung bình"),
            ("Tạo kỳ đánh giá", "Review cycle", "Trung bình"),
            ("Quản lý đánh giá nhân viên", "Manager review", "Trung bình"),
            ("Nhân viên tự đánh giá", "Self assessment", "Thấp"),
            ("Tổng hợp kết quả đánh giá", "Review results", "Trung bình"),
        ]),
        ("20", "Báo cáo & dashboard HRM", [
            ("Dashboard headcount & biến động", "HR overview dashboard", "Bắt buộc"),
            ("Báo cáo công / OT / đi trễ", "Attendance KPIs", "Bắt buộc"),
            ("Báo cáo tuyển dụng funnel", "Recruitment funnel", "Cao"),
            ("Báo cáo quỹ phép", "Leave balance report", "Cao"),
            ("Báo cáo chi phí nhân sự", "HR cost dashboard", "Bắt buộc"),
            ("Báo cáo định biên vs thực tế", "Headcount gap report", "Cao"),
        ]),
    ],
    "LMS": [
        ("01", "Danh mục nội dung đào tạo", [
            ("Danh mục chương trình đào tạo", "Training program catalog", "Bắt buộc"),
            ("Danh mục khóa học", "Course catalog", "Bắt buộc"),
            ("Phân loại khóa (online/offline/blended)", "Delivery mode", "Bắt buộc"),
            ("Quản lý chương / bài học", "Curriculum structure", "Bắt buộc"),
            ("Upload video bài giảng", "Video content", "Bắt buộc"),
            ("Upload tài liệu PDF / slide", "Learning materials", "Bắt buộc"),
            ("Gắn tag kỹ năng / vị trí", "Skill tagging", "Cao"),
            ("Phiên bản nội dung khóa học", "Content versioning", "Cao"),
            ("Ẩn / xuất bản khóa học", "Course publish control", "Bắt buộc"),
        ]),
        ("02", "Ngân hàng câu hỏi & đề thi", [
            ("Tạo ngân hàng câu hỏi", "Question bank", "Bắt buộc"),
            ("Phân loại câu hỏi theo độ khó", "Question taxonomy", "Cao"),
            ("Tạo đề thi cố định", "Fixed exam", "Bắt buộc"),
            ("Tạo đề thi random", "Random exam generation", "Cao"),
            ("Cấu hình điểm đạt / số lần thi", "Passing criteria", "Bắt buộc"),
            ("Thời gian làm bài & chống gian lận", "Exam timer & proctoring", "Cao"),
        ]),
        ("03", "Lớp Offline", [
            ("Mở lớp đào tạo offline", "Create training class", "Bắt buộc"),
            ("Gán giảng viên / địa điểm / lịch", "Schedule class", "Bắt buộc"),
            ("Tuyển sinh / ghi danh học viên", "Class enrollment", "Bắt buộc"),
            ("Điểm danh buổi học", "Class attendance", "Bắt buộc"),
            ("Ghi nhận học phí", "Training fee tracking", "Cao"),
            ("Đánh giá thực hành tại lớp", "Practical assessment", "Cao"),
            ("Đóng lớp & tổng kết", "Class completion", "Bắt buộc"),
        ]),
        ("04", "Mentoring", [
            ("Gán mentor cho học viên", "Mentor assignment", "Bắt buộc"),
            ("Checklist kèm cặp", "Mentoring checklist", "Cao"),
            ("Mentor ghi nhận tiến độ", "Progress tracking", "Cao"),
            ("Đánh giá mentor / học viên", "Two-way feedback", "Trung bình"),
            ("Báo cáo hiệu quả mentoring", "Mentoring effectiveness", "Cao"),
        ]),
        ("05", "Học Online – học viên", [
            ("Đăng ký tài khoản học viên", "Learner registration", "Bắt buộc"),
            ("Đăng nhập / quên mật khẩu", "Learner authentication", "Bắt buộc"),
            ("Danh sách & chi tiết khóa", "Course catalog view", "Bắt buộc"),
            ("Mua khóa / thanh toán online", "Course checkout", "Bắt buộc"),
            ("Kích hoạt bằng mã voucher", "Activation code", "Cao"),
            ("Tự mở khóa sau thanh toán", "Auto enrollment", "Bắt buộc"),
            ("Xem video / tài liệu", "Content consumption", "Bắt buộc"),
            ("Đánh dấu hoàn thành bài học", "Mark lesson complete", "Bắt buộc"),
            ("Tiếp tục học dở", "Resume learning", "Bắt buộc"),
            ("Theo dõi % tiến độ khóa", "Progress tracking", "Bắt buộc"),
            ("Nhắc học tiếp", "Learning reminders", "Cao"),
            ("Diễn đàn / bình luận", "Discussion forum", "Thấp"),
        ]),
        ("06", "Thi & chứng chỉ", [
            ("Làm quiz cuối chương", "Chapter quiz", "Bắt buộc"),
            ("Thi cuối khóa", "Final exam", "Bắt buộc"),
            ("Chấm điểm tự động", "Auto grading", "Bắt buộc"),
            ("Xem kết quả & đáp án", "Result review", "Cao"),
            ("Điều kiện cấp chứng chỉ", "Certificate criteria", "Bắt buộc"),
            ("Cấp chứng chỉ điện tử", "E-certificate issuance", "Bắt buộc"),
            ("Mã xác thực chứng chỉ", "Certificate verification", "Cao"),
            ("Thu hồi chứng chỉ", "Certificate revocation", "Trung bình"),
            ("Đồng bộ chứng chỉ sang HRM", "Sync to employee profile", "Cao"),
        ]),
        ("07", "Giảng viên & quản trị LMS", [
            ("Hồ sơ giảng viên", "Instructor profile", "Bắt buộc"),
            ("Phân quyền giảng viên", "Instructor permissions", "Bắt buộc"),
            ("Theo dõi danh sách học viên", "Student roster", "Bắt buộc"),
            ("Phản hồi bài tập", "Assignment feedback", "Cao"),
            ("Thống kê doanh thu theo khóa", "Course revenue", "Cao"),
            ("Chống chia sẻ tài khoản", "Device limit enforcement", "Cao"),
            ("Chặn tải video", "Video download protection", "Trung bình"),
        ]),
        ("08", "Khảo sát & xác nhận", [
            ("Tạo khảo sát hiểu bài", "Post-training survey", "Cao"),
            ("Khảo sát tuân thủ", "Compliance survey", "Cao"),
            ("Xác nhận đã đọc nội quy", "Policy acknowledgment", "Bắt buộc"),
            ("Bắt buộc hoàn thành trước ca", "Training gate before work", "Cao"),
            ("Báo cáo tỷ lệ xác nhận", "Compliance rate", "Cao"),
        ]),
        ("09", "Lộ trình đào tạo", [
            ("Gán lộ trình theo chức danh", "Learning path by role", "Cao"),
            ("Tự gán khóa bắt buộc khi nhận việc", "Auto-assign on hire", "Cao"),
            ("Theo dõi hoàn thành lộ trình", "Path completion tracking", "Cao"),
            ("Cảnh báo quá hạn đào tạo", "Overdue training alert", "Cao"),
        ]),
        ("10", "Báo cáo LMS", [
            ("Dashboard tiến độ đào tạo", "LMS dashboard", "Bắt buộc"),
            ("Báo cáo hoàn thành theo đơn vị", "Completion by org", "Bắt buộc"),
            ("Báo cáo điểm thi / tỷ lệ đạt", "Exam analytics", "Cao"),
            ("Báo cáo học viên bỏ dở", "Dropout analysis", "Cao"),
            ("Báo cáo hiệu quả khóa", "Course engagement", "Trung bình"),
            ("Xuất báo cáo đào tạo", "Export training report", "Bắt buộc"),
        ]),
        ("11", "AI hỗ trợ học tập", [
            ("Gợi ý khóa học tiếp theo", "Course recommendation", "Thấp"),
            ("Tóm tắt bài học bằng AI", "AI content summary", "Thấp"),
            ("AI tạo quiz từ nội dung", "AI quiz generation", "Thấp"),
            ("Trợ lý hỏi đáp", "AI learning assistant", "Thấp"),
        ]),
    ],
    "CRM": [
        ("01", "Master khách hàng", [
            ("Tạo khách hàng cá nhân", "Individual customer", "Bắt buộc"),
            ("Tạo khách hàng doanh nghiệp", "Corporate account", "Bắt buộc"),
            ("Cập nhật thông tin khách hàng", "Update customer info", "Bắt buộc"),
            ("Kiểm tra trùng SĐT / MST", "Duplicate detection", "Bắt buộc"),
            ("Gộp khách hàng trùng", "Merge accounts", "Bắt buộc"),
            ("Phân loại tệp khách hàng", "Customer segmentation", "Bắt buộc"),
            ("Đánh giá tiềm năng", "Potential scoring", "Cao"),
            ("Gán người phụ trách", "Account ownership", "Bắt buộc"),
            ("Bàn giao khách hàng", "Account transfer", "Bắt buộc"),
            ("Hồ sơ khách 360°", "360° customer view", "Bắt buộc"),
            ("Danh sách người liên hệ", "Contact management", "Bắt buộc"),
            ("Lịch sử thay đổi dữ liệu", "Field audit trail", "Cao"),
            ("Ngưng sử dụng / blacklist", "Inactive/block customer", "Cao"),
            ("Import / export khách hàng", "Customer data import/export", "Bắt buộc"),
            ("Tìm kiếm khách đa tiêu chí", "Advanced customer search", "Bắt buộc"),
        ]),
        ("02", "Marketing – chiến dịch", [
            ("Tạo campaign marketing", "Create campaign", "Bắt buộc"),
            ("Quản lý nhóm quảng cáo", "Ad group management", "Cao"),
            ("Gắn sản phẩm / đối tượng mục tiêu", "Targeting setup", "Cao"),
            ("Ghi nhận chi phí quảng cáo", "Campaign cost tracking", "Bắt buộc"),
            ("Gắn ngân sách & theo dõi", "Budget tracking", "Cao"),
            ("Đánh giá hậu chiến dịch", "Campaign performance review", "Cao"),
            ("Nhân bản campaign", "Clone campaign", "Trung bình"),
            ("Đóng campaign", "Close campaign", "Bắt buộc"),
        ]),
        ("03", "Marketing – nguồn & đo lường", [
            ("Danh mục nguồn lead", "Lead source taxonomy", "Bắt buộc"),
            ("Đồng bộ lead mạng xã hội", "Social media lead sync", "Cao"),
            ("Đồng bộ lead website / landing", "Website form integration", "Bắt buộc"),
            ("Đồng bộ kênh khác", "Multi-channel lead capture", "Cao"),
            ("Attribution nguồn khách", "Source attribution", "Cao"),
            ("Tính CPL / CAC / ROAS / ROI", "Marketing metrics", "Bắt buộc"),
            ("Funnel marketing đến doanh thu", "Full marketing funnel", "Cao"),
            ("Dashboard marketing", "Marketing dashboard", "Bắt buộc"),
        ]),
        ("04", "Khuyến mại & voucher", [
            ("Tạo chương trình khuyến mại", "Promotion setup", "Bắt buộc"),
            ("Cấu hình điều kiện khuyến mại", "Promotion rules", "Bắt buộc"),
            ("Sinh mã voucher", "Voucher generation", "Bắt buộc"),
            ("Giới hạn lượt dùng voucher", "Usage limit control", "Bắt buộc"),
            ("Đồng bộ khuyến mại sang POS", "POS promotion sync", "Cao"),
            ("Áp dụng khuyến mại trên báo giá", "Quote/order promotion", "Bắt buộc"),
            ("Báo cáo sử dụng voucher", "Voucher redemption report", "Cao"),
        ]),
        ("05", "Omnichannel & chatbot", [
            ("Hộp thư tập trung đa kênh", "Unified inbox", "Cao"),
            ("Tiếp nhận hội thoại mới", "Conversation intake", "Cao"),
            ("Phân phối hội thoại theo rule", "Conversation routing", "Cao"),
            ("Chuyển hội thoại giữa agent", "Transfer conversation", "Cao"),
            ("SLA phản hồi & cảnh báo", "Response SLA tracking", "Cao"),
            ("Chatbot kịch bản", "Conversation bot flow", "Trung bình"),
            ("Chatbot thu thập lead", "Lead capture bot", "Cao"),
            ("Chuyển bot sang agent", "Bot-to-human handoff", "Cao"),
            ("Lưu lịch sử chat", "Conversation history", "Bắt buộc"),
            ("Đánh giá CSAT", "Customer satisfaction", "Trung bình"),
        ]),
        ("06", "Lead", [
            ("Tạo lead thủ công", "Manual lead entry", "Bắt buộc"),
            ("Tiếp nhận lead tự động", "Auto lead capture", "Bắt buộc"),
            ("Phân bổ lead cho sales", "Lead assignment", "Bắt buộc"),
            ("Lead scoring", "Lead scoring model", "Cao"),
            ("Cập nhật trạng thái pipeline", "Lead stage tracking", "Bắt buộc"),
            ("Task follow-up lead", "Lead activity task", "Bắt buộc"),
            ("Nhắc việc follow-up", "Follow-up reminder", "Bắt buộc"),
            ("Nhật ký chăm sóc lead", "Lead activity log", "Bắt buộc"),
            ("Chuyển lead thành cơ hội", "Lead qualification", "Bắt buộc"),
            ("Đánh dấu lead mất", "Mark lead as lost", "Bắt buộc"),
            ("Gộp lead trùng", "Merge duplicate leads", "Cao"),
            ("Import lead Excel", "Bulk lead import", "Bắt buộc"),
            ("Báo cáo chuyển đổi lead", "Lead conversion report", "Bắt buộc"),
        ]),
        ("07", "Cơ hội bán hàng", [
            ("Tạo cơ hội từ lead/khách", "Create opportunity", "Bắt buộc"),
            ("Pipeline cơ hội theo giai đoạn", "Opportunity stages", "Bắt buộc"),
            ("Dự báo doanh thu", "Revenue forecast", "Cao"),
            ("Gắn sản phẩm / giá trị ước tính", "Opportunity lines", "Bắt buộc"),
            ("Đối thủ / ghi chú đàm phán", "Competitor notes", "Trung bình"),
            ("Chuyển cơ hội sang báo giá", "Create quote from opportunity", "Bắt buộc"),
            ("Đóng thắng / thua", "Close won/lost", "Bắt buộc"),
            ("Báo cáo win-rate", "Win rate analytics", "Cao"),
        ]),
        ("08", "Báo giá", [
            ("Tạo báo giá từ cơ hội", "Create quote", "Bắt buộc"),
            ("Thêm dòng sản phẩm / dịch vụ", "Quote line items", "Bắt buộc"),
            ("Áp chính sách giá / bảng giá", "Price list application", "Bắt buộc"),
            ("Xin duyệt chiết khấu", "Discount approval", "Bắt buộc"),
            ("Gửi báo giá PDF/email", "Send quote to customer", "Bắt buộc"),
            ("Phiên bản báo giá", "Quote versioning", "Cao"),
            ("Hết hạn báo giá tự động", "Quote expiry", "Cao"),
            ("Chuyển báo giá thành đơn", "Quote to order", "Bắt buộc"),
            ("In mẫu báo giá", "Quote template printing", "Cao"),
        ]),
        ("09", "Sales Online / đơn hàng", [
            ("Tạo đơn hàng từ báo giá", "Create order", "Bắt buộc"),
            ("Tiếp nhận đơn từ kênh online", "E-commerce order intake", "Cao"),
            ("Cập nhật trạng thái đơn", "Order workflow", "Bắt buộc"),
            ("Giữ tồn khi duyệt đơn", "Stock reservation", "Bắt buộc"),
            ("Tách / gộp đơn", "Split/merge orders", "Trung bình"),
            ("Hủy đơn có kiểm soát", "Order cancellation", "Bắt buộc"),
            ("Trả hàng / điều chỉnh đơn", "Return/adjustment", "Cao"),
            ("Gắn hợp đồng", "Link contract", "Cao"),
            ("Theo dõi thanh toán", "Payment tracking", "Bắt buộc"),
            ("Đẩy đơn sang kho / giao vận", "Fulfillment handoff", "Bắt buộc"),
        ]),
        ("10", "Sales Offline / Route sales", [
            ("Phân vùng / tuyến bán hàng", "Territory/route planning", "Cao"),
            ("Phân loại tần suất visit", "Visit frequency planning", "Cao"),
            ("Lập kế hoạch visit", "Visit schedule", "Cao"),
            ("Check-in / check-out GPS", "Field visit tracking", "Cao"),
            ("Ghi nhận mục đích – kết quả visit", "Visit report", "Cao"),
            ("Ghi nhận nhu cầu khách hàng", "Customer need capture", "Cao"),
            ("Đặt hàng tại điểm thăm", "Order at visit", "Cao"),
            ("Xem lịch sử visit", "Visit history", "Cao"),
            ("AI gợi ý việc ưu tiên", "AI daily coaching", "Thấp"),
            ("Dashboard doanh số field", "Field sales dashboard", "Cao"),
        ]),
        ("11", "Sales Admin", [
            ("Hàng đợi đơn cần xử lý", "Order processing queue", "Bắt buộc"),
            ("Kiểm tra tồn / xác nhận giữ hàng", "Stock availability check", "Bắt buộc"),
            ("Soạn lệnh xuất / giao", "Prepare fulfillment", "Bắt buộc"),
            ("Đối soát chứng từ đơn", "Document reconciliation", "Cao"),
            ("Xử lý khiếu nại đơn hàng", "Order complaint handling", "Cao"),
            ("Theo dõi đơn chậm xử lý", "Aging orders tracking", "Bắt buộc"),
            ("Báo cáo năng suất Sales Admin", "Admin productivity", "Trung bình"),
        ]),
        ("12", "Hợp đồng & chính sách bán", [
            ("Quản lý hợp đồng bán", "Sales contract management", "Cao"),
            ("Đính kèm file hợp đồng", "Contract attachments", "Cao"),
            ("Theo dõi hiệu lực / tái tục", "Contract renewal tracking", "Cao"),
            ("Chính sách giá theo nhóm KH", "Customer pricing policy", "Bắt buộc"),
            ("Chính sách công nợ / hạn mức", "Credit limit policy", "Bắt buộc"),
            ("Chặn bán khi vượt công nợ", "Credit block enforcement", "Cao"),
        ]),
        ("13", "Chăm sóc khách hàng", [
            ("Tạo ticket hỗ trợ", "Support ticket creation", "Bắt buộc"),
            ("Phân loại khiếu nại / yêu cầu", "Ticket categorization", "Bắt buộc"),
            ("Chuyển ticket sang FSM", "Escalate to field service", "Cao"),
            ("Lịch chăm sóc / nhắc tái mua", "Care schedule & reminders", "Cao"),
            ("Chương trình loyalty", "Loyalty program", "Trung bình"),
            ("Tích điểm / đổi quà", "Points & rewards", "Trung bình"),
            ("Khảo sát hài lòng", "CSAT/NPS surveys", "Trung bình"),
            ("Báo cáo retention / tái mua", "Customer retention", "Cao"),
        ]),
        ("14", "Hoa hồng & KPI sales", [
            ("Cấu hình rule hoa hồng", "Commission rules setup", "Cao"),
            ("Tính hoa hồng theo kỳ", "Commission calculation", "Cao"),
            ("Duyệt bảng hoa hồng", "Commission approval", "Cao"),
            ("Đồng bộ hoa hồng sang HRM/FIN", "Commission posting", "Cao"),
            ("KPI doanh số theo nhân viên", "Sales KPI tracking", "Bắt buộc"),
            ("Bảng xếp hạng sales", "Sales leaderboard", "Trung bình"),
        ]),
        ("15", "Báo cáo CRM", [
            ("Dashboard Ban lãnh đạo sales", "Executive sales dashboard", "Bắt buộc"),
            ("Báo cáo pipeline & forecast", "Pipeline report", "Bắt buộc"),
            ("Báo cáo theo nguồn / campaign", "Source performance", "Bắt buộc"),
            ("Báo cáo theo nhân viên / vùng", "Multi-dimensional sales", "Bắt buộc"),
            ("Báo cáo công nợ bán", "AR view from CRM", "Cao"),
            ("Xuất báo cáo định kỳ", "Scheduled report export", "Cao"),
        ]),
    ],
    "POS": [
        ("01", "Cấu hình điểm bán & thiết bị", [
            ("Khai báo điểm bán POS", "POS location setup", "Bắt buộc"),
            ("Khai báo quầy / máy POS", "Terminal configuration", "Bắt buộc"),
            ("Cấu hình máy in hóa đơn", "Receipt printer setup", "Bắt buộc"),
            ("Cấu hình máy in bếp/khu vực", "Kitchen printer setup", "Cao"),
            ("Cấu hình ngăn kéo tiền", "Cash drawer setup", "Cao"),
            ("Cấu hình thiết bị quét mã", "Barcode scanner setup", "Cao"),
            ("Phân quyền thu ngân trên POS", "POS user roles", "Bắt buộc"),
            ("Chế độ offline tạm", "Offline mode", "Thấp"),
        ]),
        ("02", "Catalog bán hàng", [
            ("Danh mục nhóm sản phẩm", "Product categories", "Bắt buộc"),
            ("Danh mục sản phẩm bán", "Sellable items", "Bắt buộc"),
            ("Thuộc tính sản phẩm", "Product variants/modifiers", "Cao"),
            ("BOM / định mức nguyên liệu", "Product recipe", "Bắt buộc"),
            ("Ảnh sản phẩm / thứ tự hiển thị", "Product display", "Cao"),
            ("Ngưng bán sản phẩm tạm thời", "86 item", "Bắt buộc"),
            ("Đồng bộ catalog từ back-office", "Catalog sync", "Bắt buộc"),
        ]),
        ("03", "Bảng giá & thuế", [
            ("Bảng giá theo điểm bán", "Location price list", "Bắt buộc"),
            ("Giá theo khung giờ", "Time-based pricing", "Cao"),
            ("Giá theo ngày trong tuần", "Day-based pricing", "Trung bình"),
            ("Cấu hình thuế GTGT", "Tax configuration", "Bắt buộc"),
            ("Làm tròn tiền", "Rounding rules", "Cao"),
        ]),
        ("04", "Khuyến mại tại quầy", [
            ("Áp dụng chương trình khuyến mại", "Apply promotions", "Bắt buộc"),
            ("Nhập mã voucher", "Voucher redemption", "Bắt buộc"),
            ("Khuyến mại theo combo", "Combo/bundle pricing", "Cao"),
            ("Giảm giá tay có quyền", "Manual discount with approval", "Bắt buộc"),
            ("Báo cáo khuyến mại", "Promotion usage report", "Cao"),
        ]),
        ("05", "Giao dịch bán hàng", [
            ("Mở đơn / chọn khu vực", "New transaction", "Bắt buộc"),
            ("Thêm / sửa / xóa sản phẩm", "Line item management", "Bắt buộc"),
            ("Tách bill / gộp bill", "Split/merge bills", "Cao"),
            ("Chuyển đơn giữa quầy", "Transfer order", "Cao"),
            ("Ghi chú đơn hàng", "Order notes", "Cao"),
            ("Gửi lệnh khu vực chế biến", "Send to kitchen/preparation", "Cao"),
            ("Tạm tính / giữ đơn", "Hold transaction", "Bắt buộc"),
            ("Thanh toán tiền mặt", "Cash payment", "Bắt buộc"),
            ("Thanh toán chuyển khoản / QR", "Bank transfer/QR payment", "Bắt buộc"),
            ("Thanh toán thẻ / ví điện tử", "Card/e-wallet payment", "Bắt buộc"),
            ("Thanh toán hỗn hợp", "Split payment", "Cao"),
            ("In hóa đơn", "Print receipt", "Bắt buộc"),
            ("Hủy sản phẩm", "Void item", "Bắt buộc"),
            ("Hủy cả bill", "Void transaction", "Bắt buộc"),
            ("Trả hàng / hoàn tiền", "Refund transaction", "Bắt buộc"),
            ("Gợi ý bán kèm", "Upsell suggestions", "Thấp"),
        ]),
        ("06", "Ca thu ngân & quỹ", [
            ("Mở ca thu ngân", "Open shift", "Bắt buộc"),
            ("Nhập tiền đầu ca", "Starting float", "Bắt buộc"),
            ("Nộp tiền / rút tiền ca", "Cash in/out", "Cao"),
            ("Xem doanh thu trong ca", "Shift sales realtime", "Bắt buộc"),
            ("Đóng ca & đếm quỹ", "Close shift & count", "Bắt buộc"),
            ("Đối soát lệch quỹ", "Cash variance", "Bắt buộc"),
            ("In báo cáo ca", "Shift report", "Bắt buộc"),
            ("Duyệt xác nhận ca", "Shift approval", "Cao"),
        ]),
        ("07", "Khách hàng & loyalty", [
            ("Gắn khách hàng vào đơn", "Customer identification", "Cao"),
            ("Tích điểm loyalty", "Earn loyalty points", "Trung bình"),
            ("Đổi điểm / ưu đãi", "Redeem rewards", "Trung bình"),
            ("Tra cứu lịch sử mua", "Purchase history", "Cao"),
        ]),
        ("08", "Đồng bộ tồn & back-office", [
            ("Trừ tồn theo BOM khi bán", "Auto inventory depletion", "Bắt buộc"),
            ("Cảnh báo hết / sắp hết", "Low stock alert", "Bắt buộc"),
            ("Tạo đề nghị nhập hàng", "Stock requisition", "Cao"),
            ("Nhận hàng từ kho trung tâm", "Receiving at location", "Cao"),
            ("Kiểm kê nhanh", "Quick stocktake", "Cao"),
            ("Đồng bộ doanh thu ca sang FIN", "Sales posting to GL", "Bắt buộc"),
            ("Đồng bộ đơn sang CRM", "CRM sync", "Trung bình"),
        ]),
        ("09", "Báo cáo POS", [
            ("Doanh thu theo giờ / ngày / ca", "Sales by time", "Bắt buộc"),
            ("Doanh thu theo sản phẩm", "Product mix", "Bắt buộc"),
            ("Doanh thu theo thu ngân", "Cashier performance", "Bắt buộc"),
            ("Tỷ lệ hủy / giảm giá", "Void & discount analysis", "Bắt buộc"),
            ("Cost lý thuyết vs thực tế", "Recipe vs usage variance", "Cao"),
            ("Top sản phẩm bán chạy", "Bestsellers", "Cao"),
            ("So sánh điểm bán", "Location comparison", "Cao"),
            ("Xuất báo cáo POS", "Export POS reports", "Bắt buộc"),
        ]),
        ("10", "Vận hành chuỗi", [
            ("Giám sát doanh thu chuỗi realtime", "Chain-wide monitoring", "Cao"),
            ("Phân phối catalog / giá / khuyến mại", "Push configuration", "Bắt buộc"),
            ("Chuẩn hóa catalog toàn chuỗi", "Master catalog", "Bắt buộc"),
            ("Cấu hình target doanh thu", "Sales target by location", "Cao"),
        ]),
    ],
    "PUR": [
        ("01", "Danh mục nhà cung cấp", [
            ("Tạo / cập nhật nhà cung cấp", "Vendor master", "Bắt buộc"),
            ("Phân loại nhóm nhà cung cấp", "Vendor classification", "Cao"),
            ("Người liên hệ & điều khoản", "Contact & payment terms", "Bắt buộc"),
            ("Lead time & MOQ", "Supply parameters", "Cao"),
            ("Đánh giá chất lượng nhà cung cấp", "Vendor scorecard", "Cao"),
            ("Blacklist / ngưng dùng", "Block vendor", "Cao"),
            ("Import danh sách nhà cung cấp", "Vendor import", "Trung bình"),
            ("Hồ sơ pháp lý", "Vendor documents", "Cao"),
        ]),
        ("02", "Nguồn cung & giá mua", [
            ("Gắn sản phẩm – nhà cung cấp", "Item-vendor linkage", "Bắt buộc"),
            ("Bảng giá mua theo nhà cung cấp", "Purchase price list", "Bắt buộc"),
            ("Hiệu lực bảng giá mua", "Price validity period", "Cao"),
            ("Lịch sử giá mua", "Price history", "Cao"),
            ("Cảnh báo tăng giá bất thường", "Price spike alert", "Trung bình"),
        ]),
        ("03", "Yêu cầu mua hàng (PR)", [
            ("Tạo PR từ đơn vị", "Purchase requisition", "Bắt buộc"),
            ("Tạo PR từ cảnh báo tồn min", "Auto PR from reorder point", "Cao"),
            ("Gộp nhiều nhu cầu thành PR", "PR consolidation", "Cao"),
            ("Luồng duyệt PR", "PR approval workflow", "Bắt buộc"),
            ("Từ chối / trả lại PR", "Reject/return PR", "Bắt buộc"),
            ("Theo dõi trạng thái PR", "PR status tracking", "Bắt buộc"),
            ("Hủy PR", "Cancel PR", "Cao"),
        ]),
        ("04", "Báo giá & chọn nhà cung cấp (RFQ)", [
            ("Tạo RFQ gửi nhiều nhà cung cấp", "RFQ creation", "Cao"),
            ("Nhập báo giá từ nhà cung cấp", "Vendor quotations", "Cao"),
            ("So sánh giá / điều kiện", "Quote comparison", "Cao"),
            ("Chọn nhà cung cấp thắng", "Award vendor", "Cao"),
            ("Chuyển RFQ thành PO", "RFQ to PO", "Cao"),
        ]),
        ("05", "Đơn mua hàng (PO)", [
            ("Tạo PO từ PR/RFQ", "Create PO", "Bắt buộc"),
            ("Duyệt PO theo hạn mức", "PO approval workflow", "Bắt buộc"),
            ("Gửi PO cho nhà cung cấp", "Send PO to vendor", "Bắt buộc"),
            ("Xác nhận PO từ nhà cung cấp", "Vendor acknowledgment", "Cao"),
            ("Sửa PO phiên bản", "PO revision", "Bắt buộc"),
            ("Theo dõi nhận hàng từng phần", "Partial receipt tracking", "Bắt buộc"),
            ("Đóng / hủy PO", "Close/cancel PO", "Bắt buộc"),
            ("In / xuất PO", "Print PO", "Bắt buộc"),
        ]),
        ("06", "Nhận hàng & trả nhà cung cấp", [
            ("Tạo phiếu nhận hàng theo PO", "Goods receipt", "Bắt buộc"),
            ("Nhận hàng lệch số lượng / chất lượng", "Variance receipt", "Bắt buộc"),
            ("Từ chối lô hàng không đạt", "Reject lot", "Cao"),
            ("Đẩy nhập kho sang INV", "Post to inventory", "Bắt buộc"),
            ("Trả hàng nhà cung cấp", "Return to vendor", "Cao"),
            ("Biên bản giao nhận", "Receiving report", "Cao"),
        ]),
        ("07", "Hóa đơn mua & đối soát", [
            ("Nhập hóa đơn nhà cung cấp", "Vendor invoice entry", "Bắt buộc"),
            ("Đối soát 3 chiều PO–GRN–Invoice", "3-way matching", "Bắt buộc"),
            ("Xử lý chênh lệch", "Match exception handling", "Cao"),
            ("Đẩy công nợ sang FIN AP", "Post to AP", "Bắt buộc"),
            ("Tạm ứng nhà cung cấp", "Vendor prepayment", "Cao"),
        ]),
        ("08", "Hợp đồng mua & khung giá", [
            ("Hợp đồng mua khung", "Blanket purchase agreement", "Cao"),
            ("Theo dõi sản lượng / giá trị còn lại", "Call-off tracking", "Cao"),
            ("Cảnh báo hết hạn hợp đồng", "Contract expiry alert", "Cao"),
        ]),
        ("09", "Báo cáo mua hàng", [
            ("Báo cáo mua theo nhà cung cấp / SP", "Spend analysis", "Bắt buộc"),
            ("Báo cáo đúng hạn giao hàng", "OTIF report", "Cao"),
            ("Báo cáo tiết kiệm từ RFQ", "Savings report", "Trung bình"),
            ("Open PR / Open PO aging", "Procurement backlog", "Bắt buộc"),
            ("Xuất báo cáo mua hàng", "Export purchase reports", "Bắt buộc"),
        ]),
    ],
    "INV": [
        ("01", "Danh mục sản phẩm", [
            ("Tạo / sửa SKU sản phẩm", "Item master", "Bắt buộc"),
            ("Phân nhóm hàng / ngành hàng", "Category hierarchy", "Bắt buộc"),
            ("Đơn vị tính & quy đổi", "UOM & conversion", "Bắt buộc"),
            ("Thuộc tính hàng (lô, serial, HSD)", "Tracking attributes", "Bắt buộc"),
            ("Giá vốn / phương pháp tính giá", "Costing method", "Bắt buộc"),
            ("Ảnh & mô tả sản phẩm", "Product media", "Trung bình"),
            ("Ngưng sử dụng SKU", "Discontinue item", "Bắt buộc"),
            ("Import / export danh mục SP", "Item master import/export", "Bắt buộc"),
            ("Barcode / QR theo sản phẩm", "Barcode management", "Cao"),
            ("Định mức tồn min/max/reorder", "Reorder parameters", "Bắt buộc"),
        ]),
        ("02", "Cấu hình kho & vị trí", [
            ("Tạo kho", "Warehouse master", "Bắt buộc"),
            ("Loại kho", "Warehouse type", "Bắt buộc"),
            ("Vị trí / kệ / bin", "Bin location", "Cao"),
            ("Gán thủ kho / quyền", "Warehouse access control", "Bắt buộc"),
            ("Cấu hình FEFO / FIFO", "Lot issue strategy", "Bắt buộc"),
            ("Cho phép tồn âm hay không", "Negative stock policy", "Bắt buộc"),
        ]),
        ("03", "Nhập kho", [
            ("Nhập từ mua hàng", "Purchase receipt", "Bắt buộc"),
            ("Nhập từ sản xuất", "Production receipt", "Bắt buộc"),
            ("Nhập điều chỉnh / kiểm kê", "Adjustment receipt", "Bắt buộc"),
            ("Nhập chuyển đến", "Transfer-in receipt", "Bắt buộc"),
            ("Nhập trả từ khách", "Sales return receipt", "Cao"),
            ("Nhập theo lô / HSD / serial", "Lot/serial receipt", "Bắt buộc"),
            ("In tem lô / serial", "Label printing", "Cao"),
        ]),
        ("04", "Xuất kho", [
            ("Xuất bán / giao hàng", "Sales issue", "Bắt buộc"),
            ("Xuất sản xuất", "Production issue", "Bắt buộc"),
            ("Xuất nội bộ / tiêu hao", "Internal consumption", "Bắt buộc"),
            ("Xuất cho dịch vụ kỹ thuật", "Service issue", "Cao"),
            ("Xuất cho dự án", "Project issue", "Cao"),
            ("Xuất theo FEFO tự động", "Auto lot picking", "Bắt buộc"),
            ("Xuất điều chỉnh", "Adjustment issue", "Bắt buộc"),
        ]),
        ("05", "Chuyển kho", [
            ("Tạo phiếu chuyển kho", "Transfer order", "Bắt buộc"),
            ("Duyệt chuyển kho", "Transfer approval", "Cao"),
            ("Xuất bên gửi / nhập bên nhận", "Two-step transfer", "Bắt buộc"),
            ("Chuyển kho một bước", "One-step transfer", "Cao"),
            ("Theo dõi hàng đang chuyển", "In-transit inventory", "Bắt buộc"),
            ("Chuyển từ kho trung tâm", "Replenish locations", "Bắt buộc"),
        ]),
        ("06", "Giữ hàng & tồn khả dụng", [
            ("Giữ hàng theo đơn đã duyệt", "Stock reservation", "Bắt buộc"),
            ("Giải phóng giữ hàng", "Release reservation", "Bắt buộc"),
            ("Xem tồn thực tế", "On-hand inventory", "Bắt buộc"),
            ("Xem tồn khả dụng", "Available inventory", "Bắt buộc"),
            ("Xem tồn đang giữ / đang chuyển", "Reserved & in-transit", "Bắt buộc"),
            ("Cảnh báo không đủ tồn", "ATP check", "Bắt buộc"),
        ]),
        ("07", "Lô – HSD – Serial", [
            ("Theo dõi tồn theo lô", "Lot balance", "Bắt buộc"),
            ("Cảnh báo cận date / quá date", "Expiry alert", "Bắt buộc"),
            ("Chặn xuất hàng quá HSD", "Block expired issue", "Bắt buộc"),
            ("Theo dõi serial", "Serial tracking", "Cao"),
            ("Truy vết lô xuôi/ngược", "Lot traceability", "Cao"),
            ("Báo cáo hàng sắp hết hạn", "Near-expiry report", "Bắt buộc"),
        ]),
        ("08", "Kiểm kê", [
            ("Tạo phiếu kiểm kê", "Stocktake session", "Bắt buộc"),
            ("Nhập số đếm thực tế", "Count entry", "Bắt buộc"),
            ("Kiểm kê theo vị trí / nhóm", "Cycle count", "Cao"),
            ("Đối chiếu lệch kiểm kê", "Count variance", "Bắt buộc"),
            ("Duyệt điều chỉnh sau kiểm kê", "Post adjustment", "Bắt buộc"),
            ("Khóa giao dịch khi đang kiểm kê", "Freeze transactions", "Cao"),
            ("Báo cáo kết quả kiểm kê", "Count report", "Bắt buộc"),
        ]),
        ("09", "Yêu cầu xuất / đề nghị hàng", [
            ("Đề nghị xuất nội bộ", "Material request", "Cao"),
            ("Đề nghị cấp hàng", "Store requisition", "Cao"),
            ("Duyệt đề nghị", "Approve requisition", "Cao"),
            ("Chuyển đề nghị thành phiếu xuất", "Convert to issue", "Cao"),
        ]),
        ("10", "Giá trị kho & kế toán kho", [
            ("Xem giá trị tồn", "Stock valuation", "Bắt buộc"),
            ("Tính lại giá vốn", "Cost recalculation", "Bắt buộc"),
            ("Đẩy bút toán kho sang FIN", "Inventory GL posting", "Bắt buộc"),
            ("Báo cáo giá trị tồn", "Inventory value report", "Bắt buộc"),
        ]),
        ("11", "Báo cáo kho", [
            ("Xuất nhập tồn theo kỳ", "Stock movement report", "Bắt buộc"),
            ("Thẻ kho / lịch sử sản phẩm", "Item ledger", "Bắt buộc"),
            ("Hàng chậm luân chuyển", "Slow-moving analysis", "Cao"),
            ("Hàng dưới min / trên max", "Reorder report", "Bắt buộc"),
            ("Báo cáo xuất theo mục đích", "Issue by purpose", "Cao"),
            ("Dashboard tồn & cảnh báo", "Inventory dashboard", "Bắt buộc"),
            ("Xuất báo cáo kho Excel", "Export inventory reports", "Bắt buộc"),
        ]),
    ],
    "LOG": [
        ("01", "Cấu hình giao vận", [
            ("Danh mục đơn vị vận chuyển", "Carrier master", "Bắt buộc"),
            ("Danh mục tài xế / xe", "Fleet master", "Cao"),
            ("Bảng giá cước vận chuyển", "Freight rates", "Cao"),
            ("Cấu hình khu vực giao", "Delivery zone", "Cao"),
            ("Cấu hình ca giao hàng", "Delivery shift", "Trung bình"),
        ]),
        ("02", "Lệnh giao hàng", [
            ("Tạo lệnh giao từ đơn hàng", "Create delivery order", "Bắt buộc"),
            ("Gộp nhiều đơn thành chuyến", "Route trip planning", "Cao"),
            ("Tách lệnh giao nhiều đợt", "Partial delivery", "Bắt buộc"),
            ("Pick list / soạn hàng", "Picking list", "Bắt buộc"),
            ("Xác nhận xuất hàng giao", "Ship confirmation", "Bắt buộc"),
            ("In vận đơn / phiếu giao", "Shipping documents", "Bắt buộc"),
            ("Hủy / hoàn lệnh giao", "Cancel/return delivery", "Bắt buộc"),
        ]),
        ("03", "Điều phối & theo dõi", [
            ("Phân công tài xế / đơn vị vận chuyển", "Assign carrier", "Bắt buộc"),
            ("Cập nhật trạng thái vận đơn", "Shipment status update", "Bắt buộc"),
            ("Tracking mã vận đơn", "Tracking integration", "Trung bình"),
            ("Chứng từ ký nhận (POD)", "Proof of delivery", "Cao"),
            ("Ghi nhận giao thất bại", "Failed delivery log", "Bắt buộc"),
            ("Hẹn giao lại", "Redelivery scheduling", "Cao"),
            ("Theo dõi realtime trên bản đồ", "GPS tracking", "Thấp"),
        ]),
        ("04", "COD", [
            ("Đánh dấu đơn thu COD", "COD flag", "Bắt buộc"),
            ("Ghi nhận số tiền COD", "COD amount", "Bắt buộc"),
            ("Xác nhận đã thu COD", "COD collection confirm", "Bắt buộc"),
            ("Bàn giao tiền COD", "COD handover", "Bắt buộc"),
            ("Đối soát 3 chiều COD", "COD reconciliation", "Bắt buộc"),
            ("Cảnh báo COD quá hạn", "COD aging alert", "Bắt buộc"),
            ("Xử lý lệch COD", "COD variance handling", "Cao"),
        ]),
        ("05", "Hoàn hàng & giao lại", [
            ("Tạo phiếu hoàn về kho", "Return to warehouse", "Bắt buộc"),
            ("Kiểm đếm hàng hoàn", "Return count", "Bắt buộc"),
            ("Nhập kho hàng hoàn", "Return receipt", "Bắt buộc"),
            ("Chi phí phát sinh hoàn", "Return cost", "Trung bình"),
        ]),
        ("06", "Giao nội bộ", [
            ("Lệnh giao nội bộ", "Internal delivery", "Cao"),
            ("Xác nhận nhận hàng", "Receipt acknowledgment", "Cao"),
            ("Đối soát giao nội bộ", "Internal delivery reconciliation", "Cao"),
        ]),
        ("07", "Báo cáo giao vận", [
            ("Tỷ lệ giao đúng hạn", "On-time delivery", "Bắt buộc"),
            ("Tỷ lệ hoàn / thất bại", "Delivery failure rate", "Bắt buộc"),
            ("Năng suất tài xế / chuyến", "Driver productivity", "Cao"),
            ("Chi phí vận chuyển", "Freight cost analysis", "Cao"),
            ("Báo cáo COD tồn / đã nộp", "COD outstanding report", "Bắt buộc"),
            ("Dashboard giao vận", "Logistics dashboard", "Bắt buộc"),
        ]),
    ],
    "MFG": [
        ("01", "Danh mục sản xuất", [
            ("Danh mục thành phẩm / bán thành phẩm", "Finished/semi-finished items", "Bắt buộc"),
            ("Danh mục nguyên vật liệu", "Raw material master", "Bắt buộc"),
            ("Danh mục xưởng / dây chuyền", "Work center master", "Bắt buộc"),
            ("Danh mục công đoạn", "Operation master", "Cao"),
            ("Ca sản xuất / năng lực", "Capacity planning basics", "Cao"),
        ]),
        ("02", "BOM & định mức", [
            ("Tạo BOM nhiều cấp", "Multi-level BOM", "Bắt buộc"),
            ("Phiên bản BOM", "BOM versioning", "Bắt buộc"),
            ("Định mức nguyên vật liệu", "Material quantity per unit", "Bắt buộc"),
            ("Định mức hao hụt", "Scrap allowance", "Cao"),
            ("So sánh phiên bản BOM", "BOM comparison", "Trung bình"),
            ("Sao chép BOM", "Clone BOM", "Cao"),
        ]),
        ("03", "Kế hoạch sản xuất", [
            ("Kế hoạch SX theo nhu cầu", "Production planning", "Cao"),
            ("Kế hoạch SX theo đơn hàng", "Make-to-order", "Bắt buộc"),
            ("Tính nhu cầu nguyên vật liệu", "MRP light", "Cao"),
            ("Đề xuất mua nguyên vật liệu thiếu", "Generate purchase requisition", "Cao"),
            ("Lịch SX theo xưởng/ca", "Production schedule", "Cao"),
        ]),
        ("04", "Lệnh sản xuất", [
            ("Tạo lệnh sản xuất", "Work order creation", "Bắt buộc"),
            ("Duyệt lệnh sản xuất", "Work order approval", "Bắt buộc"),
            ("Phát hành lệnh / in phiếu", "Release work order", "Bắt buộc"),
            ("Xuất nguyên vật liệu cho lệnh", "Material issue to WO", "Bắt buộc"),
            ("Ghi nhận tiến độ công đoạn", "Operation progress", "Cao"),
            ("Ghi nhận thành phẩm nhập kho", "Finished goods receipt", "Bắt buộc"),
            ("Ghi nhận phế phẩm / hao hụt", "Scrap reporting", "Bắt buộc"),
            ("Tạm dừng / hủy lệnh", "Hold/cancel work order", "Cao"),
            ("Đóng lệnh sản xuất", "Close work order", "Bắt buộc"),
            ("Lệnh sản xuất lại", "Rework order", "Trung bình"),
        ]),
        ("05", "Giá thành sản xuất", [
            ("Tập hợp chi phí nguyên vật liệu", "Material cost rollup", "Bắt buộc"),
            ("Phân bổ nhân công / chi phí chung", "Overhead allocation", "Cao"),
            ("Giá thành đơn vị thành phẩm", "Unit cost calculation", "Bắt buộc"),
            ("Đối chiếu lý thuyết vs thực tế", "Cost variance analysis", "Cao"),
            ("Đẩy giá thành sang INV/FIN", "Post production costing", "Bắt buộc"),
        ]),
        ("06", "Chất lượng (QC)", [
            ("Tiêu chí QC đầu vào", "Incoming quality control", "Cao"),
            ("QC thành phẩm", "Outgoing quality control", "Cao"),
            ("Ghi nhận lô đạt / không đạt", "QC result recording", "Cao"),
            ("Cách ly hàng lỗi", "Quarantine stock", "Cao"),
            ("Báo cáo tỷ lệ đạt QC", "Quality yield report", "Cao"),
        ]),
        ("07", "Sản xuất theo lô/mẻ", [
            ("Lô/mẻ sản xuất", "Batch/lot production", "Cao"),
            ("Ghi nhận thông số mẻ", "Process parameters", "Cao"),
            ("Đóng gói & gắn tem", "Packaging & labeling", "Cao"),
            ("Định mức phối trộn", "Blend recipe", "Trung bình"),
        ]),
        ("08", "Báo cáo sản xuất", [
            ("Tiến độ lệnh sản xuất", "Work order status board", "Bắt buộc"),
            ("Sản lượng theo ngày/ca/xưởng", "Production output", "Bắt buộc"),
            ("Tiêu hao nguyên vật liệu variance", "Material usage variance", "Bắt buộc"),
            ("Hiệu suất / OEE", "Manufacturing efficiency", "Trung bình"),
            ("Dashboard sản xuất", "Manufacturing dashboard", "Bắt buộc"),
            ("Xuất báo cáo sản xuất", "Export production reports", "Bắt buộc"),
        ]),
    ],
    "FSM": [
        ("01", "Danh mục kỹ thuật", [
            ("Danh mục loại dịch vụ", "Service type master", "Bắt buộc"),
            ("Danh mục mã lỗi", "Fault code catalog", "Bắt buộc"),
            ("Danh mục linh kiện", "Spare parts catalog", "Bắt buộc"),
            ("Bảng giá dịch vụ", "Service pricing", "Cao"),
            ("Cấu hình SLA", "SLA matrix", "Bắt buộc"),
            ("Kỹ năng / chứng chỉ kỹ thuật viên", "Technician skill matrix", "Cao"),
            ("Vùng phụ trách", "Service territory", "Cao"),
        ]),
        ("02", "Install base – thiết bị tại khách", [
            ("Hồ sơ thiết bị đã bán", "Installed equipment base", "Bắt buộc"),
            ("Serial / model / ngày kích hoạt BH", "Warranty tracking", "Bắt buộc"),
            ("Lịch sử bảo hành / sửa chữa", "Service history", "Bắt buộc"),
            ("Cảnh báo hết hạn bảo hành", "Warranty expiry alert", "Cao"),
            ("Hợp đồng bảo trì định kỳ", "Maintenance contract", "Cao"),
        ]),
        ("03", "Tiếp nhận & phân công ticket", [
            ("Tạo ticket từ kênh", "Service ticket creation", "Bắt buộc"),
            ("Phân loại mức ưu tiên", "Priority classification", "Bắt buộc"),
            ("Phân công kỹ thuật viên thủ công", "Manual technician assignment", "Bắt buộc"),
            ("Phân công theo rule", "Auto assignment by rule", "Cao"),
            ("Đổi kỹ thuật viên / escalate", "Reassignment", "Bắt buộc"),
            ("Lịch hẹn với khách", "Appointment scheduling", "Bắt buộc"),
            ("Xác nhận lịch trên APP", "Accept job on mobile", "Bắt buộc"),
        ]),
        ("04", "Thực hiện hiện trường", [
            ("Check-in hiện trường GPS", "Onsite check-in", "Cao"),
            ("Checklist công việc", "Service checklist", "Cao"),
            ("Ghi nhận nguyên nhân & xử lý", "Work log & resolution", "Bắt buộc"),
            ("Chụp ảnh trước/sau", "Photo documentation", "Cao"),
            ("Xuất linh kiện theo ticket", "Parts consumption", "Bắt buộc"),
            ("Hoàn linh kiện thừa", "Return unused parts", "Cao"),
            ("Ghi nhận phí sửa chữa", "Chargeable service", "Cao"),
            ("Check-out / hoàn thành", "Complete job", "Bắt buộc"),
        ]),
        ("05", "Nghiệm thu & đóng ticket", [
            ("Khách ký nghiệm thu", "Customer sign-off", "Bắt buộc"),
            ("Đánh giá dịch vụ", "Service rating", "Trung bình"),
            ("Đóng ticket đạt/trễ SLA", "Close ticket with SLA flag", "Bắt buộc"),
            ("Tái mở ticket", "Reopen ticket", "Cao"),
            ("Chuyển chi phí sang FIN", "Post service costs", "Cao"),
        ]),
        ("06", "Bảo trì định kỳ", [
            ("Lịch bảo trì theo thiết bị", "PM schedule", "Cao"),
            ("Tự tạo ticket bảo trì đến hạn", "Auto PM ticket generation", "Cao"),
            ("Checklist bảo trì chuẩn", "PM checklist", "Cao"),
            ("Báo cáo thực hiện bảo trì", "PM compliance report", "Cao"),
        ]),
        ("07", "Kho linh kiện kỹ thuật", [
            ("Tồn linh kiện tại kho KT", "Parts inventory view", "Bắt buộc"),
            ("Cấp linh kiện cho KTV", "Issue parts to technician", "Bắt buộc"),
            ("Đối soát linh kiện", "Parts reconciliation", "Bắt buộc"),
            ("Cảnh báo thất thoát", "Parts loss alert", "Cao"),
        ]),
        ("08", "APP kỹ thuật viên", [
            ("Danh sách việc hôm nay", "My jobs list", "Bắt buộc"),
            ("Điều hướng / thông tin khách", "Job detail & navigation", "Bắt buộc"),
            ("Làm việc offline", "Offline mode", "Thấp"),
            ("Nộp quyết toán ngày", "Daily closeout", "Cao"),
        ]),
        ("09", "Báo cáo FSM", [
            ("SLA compliance realtime", "SLA dashboard", "Bắt buộc"),
            ("Năng suất kỹ thuật viên", "Technician productivity", "Bắt buộc"),
            ("Chi phí linh kiện", "Parts cost by ticket", "Bắt buộc"),
            ("Tỷ lệ sửa lần đầu", "First time fix rate", "Cao"),
            ("Báo cáo bảo hành", "Warranty split report", "Cao"),
            ("Xuất báo cáo kỹ thuật", "Export service reports", "Bắt buộc"),
        ]),
    ],
    "PJM": [
        ("01", "Danh mục dự án", [
            ("Loại dự án", "Project types", "Bắt buộc"),
            ("Mẫu hạng mục / WBS", "WBS templates", "Bắt buộc"),
            ("Mẫu checklist nghiệm thu", "Acceptance checklist template", "Cao"),
            ("Trạng thái dự án chuẩn", "Project status model", "Bắt buộc"),
        ]),
        ("02", "Khởi tạo dự án", [
            ("Tạo dự án từ cơ hội CRM", "Project from opportunity", "Bắt buộc"),
            ("Tạo dự án thủ công", "Manual project creation", "Bắt buộc"),
            ("Gắn khách hàng / hợp đồng", "Project linkages", "Bắt buộc"),
            ("Gán quản lý dự án / thành viên", "Project team assignment", "Bắt buộc"),
            ("Ngân sách dự kiến & timeline", "Budget & schedule baseline", "Bắt buộc"),
            ("Phê duyệt khởi động", "Project kickoff approval", "Cao"),
        ]),
        ("03", "Kế hoạch & tiến độ", [
            ("Tạo hạng mục WBS", "WBS breakdown", "Bắt buộc"),
            ("Gán người thực hiện", "Task assignment", "Bắt buộc"),
            ("Cập nhật % hoàn thành", "Progress update", "Bắt buộc"),
            ("Milestone & deadline", "Milestone tracking", "Bắt buộc"),
            ("Phụ thuộc giữa hạng mục", "Task dependencies", "Trung bình"),
            ("Gantt / timeline dự án", "Timeline visualization", "Cao"),
            ("Cảnh báo trễ tiến độ", "Delay alert", "Bắt buộc"),
            ("Nhật ký thay đổi kế hoạch", "Plan change log", "Cao"),
        ]),
        ("04", "Nguồn lực & chi phí dự án", [
            ("Phân công nhân sự", "Resource assignment", "Bắt buộc"),
            ("Timesheet theo dự án", "Project timesheet", "Cao"),
            ("Xuất nguyên vật liệu cho dự án", "Material issue to project", "Bắt buộc"),
            ("Ghi nhận chi phí phát sinh", "Expense entry", "Bắt buộc"),
            ("Theo dõi ngân sách vs thực tế", "Budget vs actual tracking", "Bắt buộc"),
            ("Cảnh báo vượt ngân sách", "Budget overrun alert", "Cao"),
        ]),
        ("05", "Thực hiện dự án", [
            ("Checklist khảo sát", "Survey checklist", "Cao"),
            ("Checklist lắp đặt", "Installation checklist", "Cao"),
            ("Checklist bàn giao", "Handover checklist", "Cao"),
            ("Ghi nhận ảnh / biên bản", "Site documentation", "Cao"),
            ("Phát sinh change request", "Change request", "Cao"),
            ("Duyệt change request", "CR approval & impact", "Cao"),
        ]),
        ("06", "Nghiệm thu & đóng dự án", [
            ("Biên bản nghiệm thu giai đoạn", "Phase acceptance", "Bắt buộc"),
            ("Nghiệm thu cuối & bàn giao", "Final acceptance", "Bắt buộc"),
            ("Khách ký xác nhận", "Customer sign-off", "Bắt buộc"),
            ("Ghi nhận doanh thu dự án", "Revenue recognition", "Bắt buộc"),
            ("Quyết toán chi phí & P&L", "Project financial close", "Bắt buộc"),
            ("Đóng dự án / lưu trữ", "Close project", "Bắt buộc"),
            ("Bảo hành sau dự án", "Post-project warranty", "Cao"),
        ]),
        ("07", "Báo cáo dự án", [
            ("Portfolio dự án đang chạy", "Project portfolio board", "Bắt buộc"),
            ("Tiến độ & sức khỏe dự án", "RAG status report", "Bắt buộc"),
            ("Lợi nhuận theo dự án", "Project margin analysis", "Bắt buộc"),
            ("Năng suất nguồn lực", "Resource utilization", "Cao"),
            ("Xuất báo cáo dự án", "Export project reports", "Bắt buộc"),
        ]),
    ],
    "FIN": [
        ("01", "Danh mục kế toán", [
            ("Hệ thống tài khoản (COA)", "Chart of accounts", "Bắt buộc"),
            ("Nhóm tài khoản / chỉ tiêu", "Account groups", "Bắt buộc"),
            ("Kỳ kế toán / năm tài chính", "Fiscal calendar", "Bắt buộc"),
            ("Khóa sổ kỳ / mở lại", "Period lock/unlock", "Bắt buộc"),
            ("Đồng tiền hạch toán & tỷ giá", "Currency & exchange rates", "Cao"),
            ("Trung tâm chi phí", "Cost center master", "Bắt buộc"),
            ("Khoản mục thu/chi", "Cash flow line items", "Cao"),
            ("Hình thức thanh toán", "Payment methods", "Bắt buộc"),
            ("Danh mục thuế", "Tax code master", "Bắt buộc"),
        ]),
        ("02", "Sổ cái & bút toán", [
            ("Tạo bút toán thủ công", "Manual journal entry", "Bắt buộc"),
            ("Bút toán định kỳ / mẫu", "Recurring journal", "Cao"),
            ("Đảo bút toán", "Journal reversal", "Bắt buộc"),
            ("Xem sổ cái theo tài khoản", "GL inquiry", "Bắt buộc"),
            ("Sổ chi tiết theo đối tượng", "Subledger inquiry", "Bắt buộc"),
            ("Nhận bút toán tự động", "Auto posting from modules", "Bắt buộc"),
            ("Kiểm soát bút toán lệch Nợ/Có", "Debit/credit balance check", "Bắt buộc"),
            ("Đính kèm chứng từ gốc", "Voucher attachment", "Cao"),
        ]),
        ("03", "Quỹ tiền mặt", [
            ("Danh mục quỹ / thủ quỹ", "Cash books", "Bắt buộc"),
            ("Phiếu thu tiền mặt", "Cash receipt", "Bắt buộc"),
            ("Phiếu chi tiền mặt", "Cash payment", "Bắt buộc"),
            ("Đề nghị tạm ứng / hoàn ứng", "Advance & settlement", "Cao"),
            ("Kiểm kê quỹ", "Cash count", "Cao"),
            ("Báo cáo sổ quỹ", "Cash book report", "Bắt buộc"),
        ]),
        ("04", "Ngân hàng", [
            ("Danh mục tài khoản ngân hàng", "Bank account master", "Bắt buộc"),
            ("Giấy báo Nợ / Có", "Bank voucher", "Bắt buộc"),
            ("Đối soát sao kê ngân hàng", "Bank reconciliation", "Bắt buộc"),
            ("Đề nghị chuyển khoản", "Payment order", "Bắt buộc"),
            ("Import sao kê", "Bank statement import", "Cao"),
            ("Theo dõi số dư ngân hàng", "Bank balance tracking", "Bắt buộc"),
        ]),
        ("05", "Công nợ phải thu (AR)", [
            ("Tạo hóa đơn phải thu", "AR invoice", "Bắt buộc"),
            ("Công nợ theo khách / hóa đơn", "AR open items", "Bắt buộc"),
            ("Thu tiền & phân bổ", "Cash application", "Bắt buộc"),
            ("Bù trừ công nợ", "AR offset", "Cao"),
            ("Nhắc nợ tự động", "Dunning", "Cao"),
            ("Cảnh báo vượt hạn mức", "Credit limit alert", "Bắt buộc"),
            ("Bảng tuổi nợ phải thu", "AR aging report", "Bắt buộc"),
            ("Xử lý nợ khó đòi", "Bad debt provision", "Trung bình"),
            ("Đối soát COD về AR", "COD to AR reconciliation", "Cao"),
        ]),
        ("06", "Công nợ phải trả (AP)", [
            ("Tạo hóa đơn phải trả", "AP invoice", "Bắt buộc"),
            ("Công nợ theo nhà cung cấp", "AP open items", "Bắt buộc"),
            ("Đề nghị thanh toán", "Payment proposal", "Bắt buộc"),
            ("Duyệt chi trả", "Payment approval", "Bắt buộc"),
            ("Thanh toán & phân bổ AP", "AP payment application", "Bắt buộc"),
            ("Bảng tuổi nợ phải trả", "AP aging report", "Bắt buộc"),
            ("Tạm ứng nhà cung cấp", "Vendor prepayment", "Cao"),
            ("Đối soát 3 chiều", "3-way match from FIN view", "Cao"),
        ]),
        ("07", "Hóa đơn điện tử", [
            ("Cấu hình nhà cung cấp HĐĐT", "E-invoice provider setup", "Cao"),
            ("Phát hành hóa đơn điện tử", "Issue e-invoice", "Cao"),
            ("Điều chỉnh / thay thế / hủy", "E-invoice adjustment", "Cao"),
            ("Tra cứu trạng thái phát hành", "E-invoice status", "Cao"),
            ("Lưu trữ bảng kê HĐĐT", "E-invoice registry", "Cao"),
        ]),
        ("08", "Thuế", [
            ("Tính thuế GTGT đầu ra / đầu vào", "VAT calculation", "Bắt buộc"),
            ("Bảng kê hóa đơn GTGT", "VAT listing", "Bắt buộc"),
            ("Tờ khai thuế GTGT", "VAT return preparation", "Cao"),
            ("Thuế TNCN từ lương", "Personal income tax from payroll", "Cao"),
            ("Cấu hình thuế suất", "Tax rate configuration", "Bắt buộc"),
        ]),
        ("09", "Doanh thu & giá vốn", [
            ("Ghi nhận doanh thu từ POS", "POS revenue posting", "Bắt buộc"),
            ("Ghi nhận doanh thu từ đơn", "Order revenue posting", "Bắt buộc"),
            ("Ghi nhận doanh thu dự án", "Project revenue recognition", "Cao"),
            ("Ghi nhận giá vốn hàng bán", "COGS posting", "Bắt buộc"),
            ("Doanh thu nhận trước", "Deferred revenue", "Trung bình"),
            ("Chiết khấu làm giảm doanh thu", "Revenue deductions", "Bắt buộc"),
        ]),
        ("10", "Chi phí & phân bổ", [
            ("Ghi nhận chi phí hoạt động", "Operating expense entry", "Bắt buộc"),
            ("Phân bổ chi phí", "Cost allocation", "Cao"),
            ("Chi phí lương từ HRM", "Payroll cost posting", "Bắt buộc"),
            ("Chi phí marketing từ CRM", "Marketing cost posting", "Cao"),
            ("Tạm ứng chi phí / quyết toán", "Expense claim & settlement", "Cao"),
        ]),
        ("11", "Kết chuyển & khóa sổ", [
            ("Kết chuyển lãi/lỗ cuối kỳ", "Closing entries", "Bắt buộc"),
            ("Đối chiếu công nợ – sổ cái", "Subledger reconciliation", "Bắt buộc"),
            ("Checklist khóa sổ tháng", "Month-end checklist", "Cao"),
            ("Khóa sổ năm tài chính", "Year-end close", "Bắt buộc"),
        ]),
        ("12", "Ngân sách tài chính", [
            ("Lập ngân sách theo kỳ", "Budget planning", "Cao"),
            ("So sánh thực tế vs ngân sách", "Budget vs actual", "Cao"),
            ("Cảnh báo vượt ngân sách", "Budget alert", "Cao"),
            ("Phiên bản ngân sách", "Budget versioning", "Trung bình"),
        ]),
        ("13", "Báo cáo tài chính & quản trị", [
            ("Bảng cân đối phát sinh", "Trial balance", "Bắt buộc"),
            ("Báo cáo P&L quản trị", "Income statement", "Bắt buộc"),
            ("Bảng cân đối kế toán", "Balance sheet", "Bắt buộc"),
            ("Báo cáo lưu chuyển tiền tệ", "Cash flow statement", "Bắt buộc"),
            ("P&L theo chi nhánh / đơn vị", "Dimensional P&L", "Bắt buộc"),
            ("Báo cáo công nợ tổng hợp", "AR/AP summary", "Bắt buộc"),
            ("Dashboard tài chính", "Financial dashboard", "Bắt buộc"),
            ("Xuất báo cáo tài chính", "Export financial reports", "Bắt buộc"),
        ]),
    ],
    "AST": [
        ("01", "Danh mục tài sản", [
            ("Danh mục nhóm TSCĐ", "Asset category", "Bắt buộc"),
            ("Tạo thẻ tài sản", "Asset card", "Bắt buộc"),
            ("Thông tin nguyên giá / ngày ghi tăng", "Acquisition info", "Bắt buộc"),
            ("Gắn vị trí / chi nhánh", "Asset allocation", "Bắt buộc"),
            ("Ảnh & tài liệu kèm", "Asset documents", "Cao"),
            ("Import danh mục tài sản", "Asset import", "Trung bình"),
            ("In tem mã tài sản", "Asset label printing", "Cao"),
        ]),
        ("02", "Khấu hao", [
            ("Cấu hình phương pháp khấu hao", "Depreciation method", "Bắt buộc"),
            ("Cấu hình thời gian / tỷ lệ", "Useful life & rate", "Bắt buộc"),
            ("Tính khấu hao định kỳ", "Run depreciation", "Bắt buộc"),
            ("Xem sổ khấu hao", "Depreciation book", "Bắt buộc"),
            ("Đẩy bút toán khấu hao sang FIN", "Post depreciation", "Bắt buộc"),
            ("Tạm dừng / điều chỉnh khấu hao", "Depreciation adjustment", "Cao"),
        ]),
        ("03", "Ghi tăng – ghi giảm", [
            ("Ghi tăng từ mua sắm", "Capitalize from purchase", "Bắt buộc"),
            ("Ghi tăng từ xây dựng", "AUC to fixed asset", "Trung bình"),
            ("Điều chuyển tài sản nội bộ", "Internal asset transfer", "Bắt buộc"),
            ("Bàn giao tài sản cho nhân viên", "Asset handover", "Bắt buộc"),
            ("Thanh lý / nhượng bán", "Asset disposal/sale", "Bắt buộc"),
            ("Ghi giảm do mất mát", "Asset write-off", "Cao"),
            ("Đánh giá lại nguyên giá", "Asset revaluation", "Thấp"),
        ]),
        ("04", "Kiểm kê & bảo trì tài sản", [
            ("Tạo đợt kiểm kê tài sản", "Asset physical count", "Bắt buộc"),
            ("Đối chiếu thiếu / thừa", "Count variance", "Bắt buộc"),
            ("Lịch bảo trì TSCĐ", "Maintenance schedule", "Trung bình"),
            ("Lịch sử sửa chữa", "Repair history", "Cao"),
            ("Cảnh báo tài sản sắp hết khấu hao", "End-of-life alert", "Cao"),
        ]),
        ("05", "Công cụ dụng cụ & cấp phát", [
            ("Quản lý công cụ dụng cụ", "Tools & supplies", "Cao"),
            ("Cấp phát công cụ cho nhân viên", "Issue tools", "Cao"),
            ("Thu hồi công cụ", "Return tools", "Cao"),
            ("Phân bổ chi phí công cụ", "Tools cost allocation", "Trung bình"),
        ]),
        ("06", "Báo cáo tài sản", [
            ("Sổ tài sản cố định", "Fixed asset register", "Bắt buộc"),
            ("Báo cáo khấu hao theo kỳ", "Depreciation report", "Bắt buộc"),
            ("Báo cáo tài sản theo vị trí", "Asset by location", "Bắt buộc"),
            ("Giá trị còn lại theo nhóm", "Net book value by category", "Cao"),
            ("Xuất báo cáo tài sản", "Export asset reports", "Bắt buộc"),
        ]),
    ],
    "WF": [
        ("01", "Danh mục công việc", [
            ("Loại công việc / ticket", "Work types", "Bắt buộc"),
            ("Độ ưu tiên & SLA nội bộ", "Priority & internal SLA", "Cao"),
            ("Mẫu công việc lặp lại", "Recurring work templates", "Cao"),
            ("Nhóm / dự án nội bộ", "Workspaces", "Bắt buộc"),
        ]),
        ("02", "Giao việc & theo dõi", [
            ("Tạo task / giao việc", "Create task", "Bắt buộc"),
            ("Gán người thực hiện / theo dõi", "Assignee & followers", "Bắt buộc"),
            ("Deadline / nhắc việc", "Due date & reminders", "Bắt buộc"),
            ("Checklist trong task", "Sub-checklist", "Cao"),
            ("Bình luận / đính kèm file", "Collaboration", "Bắt buộc"),
            ("Chuyển trạng thái task", "Task status workflow", "Bắt buộc"),
            ("Ủy thác / chuyển người làm", "Task reassignment", "Cao"),
            ("Task liên kết chứng từ ERP", "Link to documents", "Cao"),
        ]),
        ("03", "Bảng làm việc (Board)", [
            ("Kanban theo nhóm/dự án", "Kanban board", "Cao"),
            ("Lọc task theo tiêu chí", "Task filters", "Bắt buộc"),
            ("Calendar công việc", "Calendar view", "Cao"),
            ("Workload theo người", "Workload distribution", "Cao"),
        ]),
        ("04", "Ticket nội bộ / helpdesk", [
            ("Tạo ticket nội bộ", "Internal helpdesk ticket", "Bắt buộc"),
            ("Phân loại & định tuyến", "Ticket routing", "Cao"),
            ("Escalate ticket quá hạn", "Ticket escalation", "Cao"),
            ("CSAT nội bộ", "Internal satisfaction", "Thấp"),
            ("Kiến thức / FAQ nội bộ", "Knowledge base", "Trung bình"),
        ]),
        ("05", "Thiết kế quy trình phê duyệt", [
            ("Tạo mẫu workflow duyệt", "Workflow designer", "Bắt buộc"),
            ("Điều kiện duyệt theo quy tắc", "Conditional approval rules", "Bắt buộc"),
            ("Nhiều cấp duyệt tuần tự / song song", "Multi-level approval", "Bắt buộc"),
            ("Gắn workflow vào loại chứng từ", "Bind workflow to document type", "Bắt buộc"),
            ("Phiên bản quy trình", "Workflow versioning", "Cao"),
            ("Mô phỏng / kiểm thử", "Workflow dry-run", "Trung bình"),
        ]),
        ("06", "Thực thi phê duyệt", [
            ("Hộp chờ duyệt của tôi", "My approval inbox", "Bắt buộc"),
            ("Duyệt / từ chối / trả bổ sung", "Approval actions", "Bắt buộc"),
            ("Duyệt hàng loạt", "Bulk approve", "Cao"),
            ("Duyệt trên mobile APP", "Mobile approval", "Bắt buộc"),
            ("Ủy quyền duyệt tạm thời", "Delegation", "Bắt buộc"),
            ("Nhắc duyệt / escalate", "Approval SLA & reminders", "Bắt buộc"),
            ("Lịch sử duyệt & comment", "Approval history", "Bắt buộc"),
            ("Thu hồi chứng từ đang chờ", "Recall submission", "Cao"),
        ]),
        ("07", "Báo cáo quy trình & công việc", [
            ("Thời gian duyệt trung bình", "Approval cycle time", "Cao"),
            ("Bottleneck cấp duyệt", "Approval bottleneck", "Cao"),
            ("Khối lượng task mở / quá hạn", "Task backlog", "Bắt buộc"),
            ("Năng suất hoàn thành", "Task completion rate", "Cao"),
            ("Dashboard workflow", "Workflow dashboard", "Bắt buộc"),
        ]),
    ],
    "BI": [
        ("01", "Nền tảng dữ liệu báo cáo", [
            ("Catalog dataset theo module", "Licensed dataset catalog", "Bắt buộc"),
            ("Làm mới dữ liệu định kỳ", "Data refresh policy", "Bắt buộc"),
            ("Phân quyền xem báo cáo", "BI access control", "Bắt buộc"),
            ("Từ điển chỉ tiêu KPI", "KPI dictionary", "Cao"),
            ("Nhật ký truy cập báo cáo", "Report access log", "Trung bình"),
        ]),
        ("02", "Dashboard quản trị", [
            ("Dashboard Ban lãnh đạo", "Executive dashboard", "Bắt buộc"),
            ("Dashboard theo module", "Module-specific dashboards", "Bắt buộc"),
            ("Widget doanh thu – lợi nhuận", "Revenue & profit widgets", "Bắt buộc"),
            ("Widget tồn – mua – giao", "Supply chain widgets", "Cao"),
            ("Widget nhân sự – công", "HR widgets", "Cao"),
            ("Widget sales pipeline", "Sales widgets", "Cao"),
            ("Tùy chỉnh bố cục theo role", "Layout customization", "Cao"),
        ]),
        ("03", "Thư viện báo cáo chuẩn", [
            ("Danh mục báo cáo theo module", "Report catalog", "Bắt buộc"),
            ("Chạy báo cáo với bộ lọc", "Parameterized reports", "Bắt buộc"),
            ("Lưu bộ lọc / yêu thích", "Saved report views", "Cao"),
            ("Xuất Excel / PDF", "Report export", "Bắt buộc"),
            ("Gửi báo cáo email định kỳ", "Scheduled report email", "Cao"),
            ("So sánh kỳ / mục tiêu", "Period & target comparison", "Bắt buộc"),
        ]),
        ("04", "Cảnh báo & KPI", [
            ("Cấu hình ngưỡng cảnh báo", "KPI threshold alerts", "Bắt buộc"),
            ("Cảnh báo realtime / digest", "Alert channels", "Cao"),
            ("Bảng theo dõi Target vs Actual", "KPI tracking board", "Bắt buộc"),
            ("Đăng ký nhận cảnh báo", "Subscribe to alerts", "Cao"),
        ]),
        ("05", "Self-service & phân tích", [
            ("Tạo báo cáo tùy chỉnh", "Self-service reporting", "Trung bình"),
            ("Pivot / biểu đồ tương tác", "Interactive visualizations", "Cao"),
            ("Chia sẻ báo cáo", "Share reports", "Cao"),
            ("Xuất dataset đã lọc", "Filtered data extract", "Cao"),
        ]),
        ("06", "Dự báo & AI", [
            ("Dự báo doanh thu", "Sales forecast", "Thấp"),
            ("Dự báo nhu cầu", "Demand forecast", "Thấp"),
            ("Phát hiện bất thường", "Anomaly detection", "Thấp"),
            ("Tóm tắt insight bằng AI", "AI insights summary", "Thấp"),
        ]),
    ],
    "PRT": [
        ("01", "Tài khoản portal", [
            ("Đăng ký tài khoản khách hàng", "Customer signup", "Bắt buộc"),
            ("Đăng nhập / quên mật khẩu", "Portal authentication", "Bắt buộc"),
            ("Liên kết tài khoản với mã khách", "Link customer account", "Bắt buộc"),
            ("Quản lý nhiều liên hệ", "Multi-contact management", "Cao"),
            ("Phân quyền liên hệ", "Contact permissions", "Cao"),
            ("Xác thực email/SĐT", "Contact verification", "Cao"),
        ]),
        ("02", "Đơn hàng & giao nhận (khách hàng)", [
            ("Xem danh sách đơn hàng", "My orders", "Bắt buộc"),
            ("Xem chi tiết & trạng thái đơn", "Order detail & status", "Bắt buộc"),
            ("Theo dõi vận đơn", "Shipment tracking", "Cao"),
            ("Tải hóa đơn / biên bản", "Download documents", "Cao"),
            ("Yêu cầu trả hàng / khiếu nại", "Return/complaint request", "Cao"),
            ("Đặt hàng lại", "Reorder", "Trung bình"),
            ("Tạo yêu cầu báo giá", "RFQ from portal", "Thấp"),
        ]),
        ("03", "Công nợ & thanh toán (khách hàng)", [
            ("Xem công nợ hiện tại", "My AR balance", "Bắt buộc"),
            ("Xem bảng kê hóa đơn chưa thanh toán", "Open invoices", "Bắt buộc"),
            ("Lịch sử thanh toán", "Payment history", "Bắt buộc"),
            ("Thanh toán online", "Online payment", "Trung bình"),
            ("Đối chiếu sao kê", "AR statement", "Cao"),
        ]),
        ("04", "Hỗ trợ & bảo hành (khách hàng)", [
            ("Tạo ticket hỗ trợ", "Create support ticket", "Bắt buộc"),
            ("Xem trạng thái ticket", "Ticket status", "Bắt buộc"),
            ("Trao đổi / gửi ảnh", "Ticket conversation", "Cao"),
            ("Xem thiết bị đã mua", "My equipment", "Cao"),
            ("Đặt lịch bảo trì", "Book maintenance", "Trung bình"),
            ("Đánh giá dịch vụ", "Rate service", "Trung bình"),
        ]),
        ("05", "Kiến thức & tài liệu khách hàng", [
            ("Xem catalogue / bảng giá", "Product catalog", "Trung bình"),
            ("Tải tài liệu kỹ thuật", "Download documents", "Cao"),
            ("Thông báo từ nhà cung cấp", "Announcements", "Trung bình"),
            ("Đăng ký nhận bản tin", "Newsletter subscription", "Thấp"),
        ]),
        ("06", "Portal nhà cung cấp / đối tác", [
            ("Đăng nhập portal nhà cung cấp", "Vendor login", "Trung bình"),
            ("Xem PO được gửi", "View purchase orders", "Trung bình"),
            ("Xác nhận PO / ngày giao", "PO acknowledgment", "Trung bình"),
            ("Gửi thông báo sẵn sàng giao", "ASN notification", "Thấp"),
            ("Xem công nợ phía nhà cung cấp", "Vendor AP view", "Thấp"),
            ("Portal đại lý", "Dealer portal", "Thấp"),
        ]),
        ("07", "Báo cáo & quản trị portal", [
            ("Thống kê lượt dùng portal", "Usage statistics", "Cao"),
            ("Quản trị nội dung portal", "CMS light", "Trung bình"),
            ("Cấu hình module portal theo gói", "Portal features by plan", "Bắt buộc"),
            ("Nhật ký thao tác phía portal", "Portal audit log", "Cao"),
        ]),
    ],
}
