# -*- coding: utf-8 -*-
"""Catalog tổng hợp toàn bộ bảng & trường CSDL ERP (logic Phase 1)."""
from __future__ import annotations

from typing import TypedDict


class Field(TypedDict):
    name: str
    dtype: str
    meaning: str
    note: str


class Table(TypedDict):
    module: str
    group: str
    name: str  # schema.table
    purpose: str
    fields: list[Field]


def F(name: str, dtype: str, meaning: str, note: str = "") -> Field:
    return {"name": name, "dtype": dtype, "meaning": meaning, "note": note}


def std_fields(include_tenant: bool = True) -> list[Field]:
    rows: list[Field] = [F("id", "UUID", "Khóa chính", "PK")]
    if include_tenant:
        rows.append(F("tenant_id", "UUID", "Định danh tenant", "FK → sys.tenant; index"))
    rows += [
        F("created_at", "timestamptz", "Thời điểm tạo (UTC)", "NOT NULL"),
        F("created_by", "UUID", "Người tạo", "FK → sys.app_user; nullable với job hệ thống"),
        F("updated_at", "timestamptz", "Thời điểm cập nhật cuối (UTC)", "NOT NULL"),
        F("updated_by", "UUID", "Người cập nhật cuối", "FK → sys.app_user"),
        F("is_deleted", "boolean", "Cờ xóa mềm", "Mặc định false"),
        F("deleted_at", "timestamptz", "Thời điểm xóa mềm", "Null nếu chưa xóa"),
        F("row_version", "int", "Phiên bản hàng (optimistic lock)", "Tăng mỗi lần update"),
    ]
    return rows


def doc_fields() -> list[Field]:
    return [
        F("doc_no", "varchar(50)", "Số chứng từ", "Unique theo tenant; Sequence SYS"),
        F("doc_date", "date", "Ngày chứng từ", ""),
        F("status", "varchar(30)", "Trạng thái vòng đời", "Draft/Submitted/Approved/Posted/Cancelled…"),
        F("org_unit_id", "UUID", "Đơn vị/chi nhánh phát sinh", "FK/ref sys.org_unit"),
        F("remark", "text", "Ghi chú", ""),
        F("correlation_id", "UUID", "Mã truy vết liên module", "Khớp event INT"),
    ]


def money_fields(prefix: str = "") -> list[Field]:
    p = f"{prefix}_" if prefix else ""
    return [
        F(f"{p}currency_code", "char(3)", "Mã tiền tệ ISO", "VD VND, USD"),
        F(f"{p}exchange_rate", "numeric(18,8)", "Tỷ giá quy đổi", "Null nếu cùng tiền tệ gốc"),
    ]


def T(module: str, group: str, name: str, purpose: str, extra: list[Field], *, tenant: bool = True, doc: bool = False) -> Table:
    fields = std_fields(tenant)
    if doc:
        fields += doc_fields()
    fields += extra
    return {"module": module, "group": group, "name": name, "purpose": purpose, "fields": fields}


def build_catalog() -> list[Table]:
    t: list[Table] = []

    # ========== SYS ==========
    t += [
        T("SYS", "Tenant & tổ chức", "sys.tenant", "Không gian dữ liệu khách hàng thuê bao", [
            F("code", "varchar(30)", "Mã tenant", "Unique toàn hệ"),
            F("name", "varchar(200)", "Tên tenant", ""),
            F("status", "varchar(20)", "Trạng thái", "Active/Suspended/Closed"),
            F("timezone", "varchar(64)", "Múi giờ mặc định", "VD Asia/Ho_Chi_Minh"),
            F("default_locale", "varchar(10)", "Ngôn ngữ mặc định", "vi-VN"),
            F("default_currency", "char(3)", "Tiền tệ mặc định", "VND"),
        ], tenant=False),
        T("SYS", "Tenant & tổ chức", "sys.org_unit", "Cây tổ chức pháp lý / chi nhánh (Company/Branch)", [
            F("code", "varchar(40)", "Mã đơn vị", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên đơn vị", ""),
            F("parent_id", "UUID", "Đơn vị cha", "FK self; null = gốc"),
            F("unit_type", "varchar(30)", "Loại đơn vị", "Company/Branch/Division (không dùng thay Department)"),
            F("path", "varchar(500)", "Đường dẫn cây", "Materialized path"),
            F("manager_user_id", "UUID", "Người quản lý đơn vị", "Ref app_user; optional"),
            F("sort_order", "int", "Thứ tự hiển thị", ""),
            F("is_active", "boolean", "Còn hiệu lực", ""),
        ]),
        T("SYS", "Tenant & tổ chức", "sys.department", "Phòng ban (cây phòng) — trục data scope Department", [
            F("code", "varchar(40)", "Mã phòng ban", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên phòng ban", ""),
            F("parent_id", "UUID", "Phòng ban cha", "FK self; null = gốc"),
            F("org_unit_id", "UUID", "Chi nhánh / đơn vị thuộc về", "FK org_unit (Branch)"),
            F("manager_user_id", "UUID", "Trưởng phòng", "Ref app_user"),
            F("path", "varchar(500)", "Đường dẫn cây phòng", "Materialized path — scope gồm con"),
            F("sort_order", "int", "Thứ tự hiển thị", ""),
            F("is_active", "boolean", "Còn hiệu lực", ""),
        ]),
        T("SYS", "Tenant & tổ chức", "sys.job_level", "Cấp bậc — gắn mặc định data scope 4 tầng", [
            F("code", "varchar(40)", "Mã cấp bậc", "Unique theo tenant; VD STAFF/MANAGER/DIRECTOR"),
            F("name", "varchar(200)", "Tên cấp bậc", ""),
            F("level_order", "int", "Thứ tự cấp (cao → thấp hoặc ngược)", "Dùng so sánh cấp"),
            F("default_scope_type", "varchar(20)", "Phạm vi dữ liệu mặc định", "Own|Team|Department|All (Digi ScopeType)"),
            F("description", "text", "Mô tả", ""),
            F("is_active", "boolean", "Còn dùng", ""),
        ]),
        T("SYS", "Người dùng & bảo mật", "sys.app_user", "Tài khoản đăng nhập hệ thống", [
            F("username", "varchar(100)", "Tên đăng nhập", "Unique theo tenant"),
            F("display_name", "varchar(200)", "Tên hiển thị", ""),
            F("email", "varchar(255)", "Email", "Unique theo tenant nếu có"),
            F("phone", "varchar(30)", "Số điện thoại", ""),
            F("password_hash", "varchar(255)", "Hash mật khẩu", "Null nếu SSO-only"),
            F("status", "varchar(20)", "Trạng thái tài khoản", "Active/Locked/Disabled"),
            F("must_change_password", "boolean", "Bắt buộc đổi mật khẩu", ""),
            F("last_login_at", "timestamptz", "Lần đăng nhập cuối", ""),
            F("failed_login_count", "int", "Số lần đăng nhập sai liên tiếp", "Reset khi login OK"),
            F("locked_until", "timestamptz", "Khóa tạm đến thời điểm", ""),
            F("primary_org_unit_id", "UUID", "Chi nhánh/đơn vị chính", "FK org_unit"),
            F("department_id", "UUID", "Phòng ban chính", "FK department — nền scope Department"),
            F("job_level_id", "UUID", "Cấp bậc", "FK job_level — lấy default_scope_type"),
            F("manager_user_id", "UUID", "Quản lý trực tiếp", "FK self — nền scope Team"),
            F("employee_id", "UUID", "Liên kết hồ sơ NV", "Ref mềm hrm.employee; sync khi có HRM"),
        ]),
        T("SYS", "Người dùng & bảo mật", "sys.user_department", "Phòng ban kiêm nhiệm / phụ của user", [
            F("user_id", "UUID", "Người dùng", "FK app_user"),
            F("department_id", "UUID", "Phòng ban", "FK department"),
            F("is_primary", "boolean", "Có phải phòng chính", "Chỉ 1 primary/user"),
            F("valid_from", "date", "Hiệu lực từ", ""),
            F("valid_to", "date", "Hiệu lực đến", "Null = không hạn"),
        ]),
        T("SYS", "Người dùng & bảo mật", "sys.role", "Vai trò RBAC (quyền chức năng)", [
            F("code", "varchar(50)", "Mã role", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên role", ""),
            F("description", "text", "Mô tả", ""),
            F("bypass_data_scope", "boolean", "Bỏ qua lọc data scope", "true = coi như All + full quyền nếu là super"),
            F("is_system", "boolean", "Role hệ thống không xóa", "VD SUPER_ADMIN"),
            F("is_active", "boolean", "Đang hiệu lực", ""),
            F("sort_order", "int", "Thứ tự hiển thị", ""),
        ]),
        T("SYS", "Người dùng & bảo mật", "sys.permission", "Danh mục mã quyền chức năng (catalog toàn sản phẩm)", [
            F("module_code", "varchar(10)", "Module sở hữu quyền", "SYS/HRM/CRM…"),
            F("code", "varchar(100)", "Mã quyền", "Unique; dạng {module}.{resource}.{action}"),
            F("name", "varchar(200)", "Tên hiển thị", ""),
            F("resource", "varchar(80)", "Tài nguyên", "VD employee, leave, sales_order"),
            F("action", "varchar(40)", "Hành động", "Create/Read/Update/Delete/Approve/Assign/Export/Manage…"),
            F("description", "text", "Mô tả chi tiết", ""),
            F("is_active", "boolean", "Còn dùng", ""),
        ], tenant=False),
        T("SYS", "Người dùng & bảo mật", "sys.role_permission", "Gán permission vào role", [
            F("role_id", "UUID", "Vai trò", "FK role"),
            F("permission_id", "UUID", "Quyền", "FK permission"),
        ]),
        T("SYS", "Người dùng & bảo mật", "sys.user_role", "Gán role cho user", [
            F("user_id", "UUID", "Người dùng", "FK app_user"),
            F("role_id", "UUID", "Vai trò", "FK role"),
            F("is_active", "boolean", "Đang hiệu lực", "false hoặc revoked_at = thu hồi mềm"),
            F("valid_from", "timestamptz", "Hiệu lực từ", ""),
            F("valid_to", "timestamptz", "Hiệu lực đến", "Null = không hạn"),
            F("revoked_at", "timestamptz", "Thời điểm thu hồi", ""),
            F("assigned_by", "UUID", "Người gán", "Ref app_user"),
        ]),
        T("SYS", "Người dùng & bảo mật", "sys.user_data_scope", "Phạm vi dữ liệu theo đối tượng (bổ sung / ghi đè)", [
            F("user_id", "UUID", "Người dùng", "FK app_user"),
            F("dimension", "varchar(30)", "Chiều phạm vi", "OrgUnit/Department/Warehouse/Store/Project…"),
            F("scope_id", "UUID", "ID đối tượng phạm vi", "Theo dimension"),
            F("include_children", "boolean", "Gồm cây con", "Áp dụng OrgUnit/Department"),
            F("access_level", "varchar(20)", "Mức truy cập", "Read/Write"),
            F("source", "varchar(30)", "Nguồn gán", "Manual/Import/Sync — không thay JobLevel mặc định"),
            F("valid_from", "date", "Hiệu lực từ", ""),
            F("valid_to", "date", "Hiệu lực đến", "Null = không hạn"),
        ]),
        T("SYS", "Người dùng & bảo mật", "sys.field_permission", "Quyền theo trường nhạy cảm (field-level)", [
            F("role_id", "UUID", "Vai trò", "FK role"),
            F("entity_type", "varchar(80)", "Loại thực thể", "VD hrm.employee"),
            F("field_name", "varchar(80)", "Tên trường", "VD national_id_enc, base_salary"),
            F("access_level", "varchar(20)", "Mức", "Hidden/Masked/Read/Write"),
        ]),
        T("SYS", "Người dùng & bảo mật", "sys.menu_item", "Menu chức năng UI (lọc theo license + permission)", [
            F("code", "varchar(80)", "Mã menu", "Unique theo tenant hoặc global+override"),
            F("parent_id", "UUID", "Menu cha", "FK self"),
            F("module_code", "varchar(10)", "Module", ""),
            F("title", "varchar(200)", "Nhãn hiển thị", ""),
            F("route_path", "varchar(255)", "Đường dẫn FE", ""),
            F("permission_code", "varchar(100)", "Quyền cần có để hiện", "Null = chỉ cần license module"),
            F("icon", "varchar(80)", "Icon", ""),
            F("sort_order", "int", "Thứ tự", ""),
            F("is_active", "boolean", "Đang hiện trong catalog", ""),
        ]),
        T("SYS", "Người dùng & bảo mật", "sys.session", "Phiên đăng nhập đang hoạt động", [
            F("user_id", "UUID", "Người dùng", "FK app_user"),
            F("refresh_token_hash", "varchar(255)", "Hash refresh token", ""),
            F("ip_address", "varchar(45)", "IP đăng nhập", ""),
            F("user_agent", "varchar(500)", "Thiết bị / trình duyệt", ""),
            F("expires_at", "timestamptz", "Hết hạn phiên", ""),
            F("revoked_at", "timestamptz", "Thời điểm thu hồi", ""),
        ]),
        T("SYS", "License & cấu hình", "sys.license", "Hợp đồng / gói license của tenant", [
            F("plan_code", "varchar(50)", "Mã gói", ""),
            F("valid_from", "date", "Ngày bắt đầu", ""),
            F("valid_to", "date", "Ngày hết hạn", ""),
            F("max_users", "int", "Hạn mức user", ""),
            F("status", "varchar(20)", "Trạng thái license", "Active/Expired"),
        ]),
        T("SYS", "License & cấu hình", "sys.license_module", "Module được bật trong license", [
            F("license_id", "UUID", "License", "FK license"),
            F("module_code", "varchar(10)", "Mã module", "HRM/CRM…"),
            F("is_enabled", "boolean", "Đang bật", ""),
            F("quota_json", "jsonb", "Hạn mức riêng module", "Optional"),
        ]),
        T("SYS", "License & cấu hình", "sys.sequence_rule", "Quy tắc sinh số chứng từ", [
            F("code", "varchar(50)", "Mã sequence", "Unique theo tenant"),
            F("pattern", "varchar(100)", "Mẫu sinh số", "VD {YYYY}{MM}-{SEQ:5}"),
            F("current_value", "bigint", "Giá trị hiện tại", ""),
            F("reset_policy", "varchar(30)", "Chính sách reset", "Never/Yearly/Monthly"),
            F("padding", "int", "Độ dài phần số", ""),
        ]),
        T("SYS", "License & cấu hình", "sys.setting", "Cấu hình key-value theo tenant", [
            F("setting_key", "varchar(100)", "Khóa cấu hình", "Unique theo tenant"),
            F("setting_value", "text", "Giá trị", "Có thể JSON string"),
            F("value_type", "varchar(20)", "Kiểu giá trị", "string/number/bool/json"),
            F("module_code", "varchar(10)", "Module liên quan", ""),
        ]),
        T("SYS", "File & thông báo", "sys.file_object", "Metadata file đính kèm (binary ở object storage)", [
            F("storage_key", "varchar(500)", "Key trên object storage", ""),
            F("file_name", "varchar(255)", "Tên file gốc", ""),
            F("content_type", "varchar(100)", "MIME type", ""),
            F("size_bytes", "bigint", "Dung lượng", ""),
            F("checksum", "varchar(64)", "Hash kiểm tra toàn vẹn", ""),
            F("owner_module", "varchar(10)", "Module gắn file", ""),
            F("owner_type", "varchar(50)", "Loại đối tượng nghiệp vụ", ""),
            F("owner_id", "UUID", "ID đối tượng nghiệp vụ", ""),
        ]),
        T("SYS", "File & thông báo", "sys.notification_template", "Mẫu thông báo email/SMS/in-app", [
            F("code", "varchar(50)", "Mã mẫu", "Unique theo tenant"),
            F("channel", "varchar(20)", "Kênh", "Email/SMS/InApp/Push"),
            F("subject_template", "varchar(500)", "Tiêu đề mẫu", ""),
            F("body_template", "text", "Nội dung mẫu", "Placeholder"),
            F("locale", "varchar(10)", "Ngôn ngữ mẫu", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("SYS", "File & thông báo", "sys.notification_log", "Lịch sử gửi thông báo", [
            F("template_code", "varchar(50)", "Mã mẫu đã dùng", ""),
            F("channel", "varchar(20)", "Kênh gửi", ""),
            F("recipient", "varchar(255)", "Người nhận", ""),
            F("payload_json", "jsonb", "Dữ liệu render", ""),
            F("status", "varchar(20)", "Kết quả gửi", "Pending/Sent/Failed"),
            F("error_message", "text", "Lỗi nếu thất bại", ""),
            F("sent_at", "timestamptz", "Thời điểm gửi thành công", ""),
        ]),
        T("SYS", "Nhắn tin realtime", "sys.conversation", "Hội thoại 1-1 / nhóm (SYS-13)", [
            F("kind", "varchar(20)", "Loại hội thoại", "Direct/Group"),
            F("title", "nvarchar(200)", "Tên nhóm", "Nullable với Direct"),
            F("created_by", "UUID", "Người tạo", "FK → sys.app_user"),
        ]),
        T("SYS", "Nhắn tin realtime", "sys.conversation_member", "Thành viên hội thoại + unread/mute", [
            F("conversation_id", "UUID", "Hội thoại", "FK → sys.conversation"),
            F("user_id", "UUID", "Thành viên", "FK → sys.app_user"),
            F("last_read_at", "timestamptz", "Mốc đã đọc", ""),
            F("muted", "boolean", "Tắt thông báo hội thoại", "Mặc định false"),
        ]),
        T("SYS", "Nhắn tin realtime", "sys.chat_message", "Tin nhắn realtime", [
            F("conversation_id", "UUID", "Hội thoại", "FK → sys.conversation"),
            F("sender_user_id", "UUID", "Người gửi", "FK → sys.app_user"),
            F("body", "nvarchar(max)", "Nội dung text", ""),
            F("attachment_file_id", "UUID", "File đính kèm", "FK → sys.file_object; nullable"),
            F("sent_at", "timestamptz", "Thời điểm gửi", ""),
            F("recalled_at", "timestamptz", "Thu hồi", "Nullable"),
        ]),
        T("SYS", "Audit & tích hợp", "sys.audit_log", "Nhật ký thay đổi dữ liệu", [
            F("entity_type", "varchar(80)", "Loại thực thể", ""),
            F("entity_id", "UUID", "ID bản ghi", ""),
            F("action", "varchar(30)", "Hành động", "Create/Update/Delete"),
            F("before_json", "jsonb", "Giá trị trước", ""),
            F("after_json", "jsonb", "Giá trị sau", ""),
            F("actor_user_id", "UUID", "Người thực hiện", ""),
            F("ip_address", "varchar(45)", "IP", ""),
        ]),
        T("SYS", "Audit & tích hợp", "sys.login_log", "Nhật ký đăng nhập / thất bại", [
            F("user_id", "UUID", "User (nếu xác định được)", ""),
            F("username_attempt", "varchar(100)", "Chuỗi đăng nhập thử", ""),
            F("success", "boolean", "Thành công hay không", ""),
            F("fail_reason", "varchar(100)", "Lý do thất bại", ""),
            F("ip_address", "varchar(45)", "IP", ""),
            F("user_agent", "varchar(500)", "User agent", ""),
        ]),
        T("SYS", "Audit & tích hợp", "sys.api_key", "Khóa API tích hợp", [
            F("name", "varchar(100)", "Tên key", ""),
            F("key_hash", "varchar(255)", "Hash API key", "Không lưu plaintext"),
            F("scopes_json", "jsonb", "Phạm vi quyền", ""),
            F("expires_at", "timestamptz", "Hết hạn", ""),
            F("revoked_at", "timestamptz", "Thu hồi", ""),
            F("last_used_at", "timestamptz", "Lần dùng cuối", ""),
        ]),
        T("SYS", "Audit & tích hợp", "sys.webhook_subscription", "Đăng ký webhook outbound", [
            F("event_types_json", "jsonb", "Danh sách event đăng ký", ""),
            F("target_url", "varchar(500)", "URL nhận", ""),
            F("secret_hash", "varchar(255)", "Secret ký request", ""),
            F("is_active", "boolean", "Đang bật", ""),
        ]),
        T("SYS", "Audit & tích hợp", "sys.integration_outbox", "Hàng đợi phát sự kiện (Outbox)", [
            F("event_id", "UUID", "ID sự kiện duy nhất", "Unique"),
            F("event_type", "varchar(120)", "Loại sự kiện", "Theo INT-03"),
            F("aggregate_type", "varchar(80)", "Loại aggregate nguồn", ""),
            F("aggregate_id", "UUID", "ID aggregate nguồn", ""),
            F("payload_json", "jsonb", "Envelope + payload", ""),
            F("status", "varchar(20)", "Trạng thái publish", "New/Published/Failed"),
            F("occurred_at", "timestamptz", "Thời điểm nghiệp vụ xảy ra", ""),
            F("published_at", "timestamptz", "Thời điểm publish", ""),
            F("retry_count", "int", "Số lần retry", ""),
            F("last_error", "text", "Lỗi gần nhất", ""),
        ]),
        T("SYS", "Audit & tích hợp", "sys.integration_inbox", "Inbox chống xử lý trùng sự kiện", [
            F("event_id", "UUID", "ID sự kiện", "Unique cùng consumer"),
            F("consumer", "varchar(80)", "Tên consumer/module", ""),
            F("processed_at", "timestamptz", "Thời điểm xử lý xong", ""),
            F("result", "varchar(30)", "Kết quả", "Success/Skipped/Failed"),
        ]),
    ]

    # ========== WF ==========
    t += [
        T("WF", "Định nghĩa quy trình", "wf.wf_definition", "Định nghĩa quy trình duyệt theo loại chứng từ", [
            F("code", "varchar(50)", "Mã quy trình", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên quy trình", ""),
            F("source_module", "varchar(10)", "Module nguồn", ""),
            F("doc_type", "varchar(50)", "Loại chứng từ áp dụng", ""),
            F("is_active", "boolean", "Đang hiệu lực", ""),
        ]),
        T("WF", "Định nghĩa quy trình", "wf.wf_definition_version", "Phiên bản quy trình (immutable khi đã chạy)", [
            F("definition_id", "UUID", "Quy trình gốc", "FK wf_definition"),
            F("version_no", "int", "Số phiên bản", ""),
            F("published_at", "timestamptz", "Thời điểm phát hành", ""),
            F("is_current", "boolean", "Đang là bản hiện hành", ""),
        ]),
        T("WF", "Định nghĩa quy trình", "wf.wf_node", "Bước/nút trong quy trình", [
            F("version_id", "UUID", "Phiên bản quy trình", "FK"),
            F("node_key", "varchar(50)", "Mã bước", ""),
            F("node_type", "varchar(30)", "Loại nút", "Start/Approve/Condition/End"),
            F("name", "varchar(200)", "Tên bước", ""),
            F("assignee_rule_json", "jsonb", "Rule gán người duyệt", ""),
        ]),
        T("WF", "Định nghĩa quy trình", "wf.wf_transition", "Chuyển tiếp giữa các bước", [
            F("version_id", "UUID", "Phiên bản quy trình", "FK"),
            F("from_node_id", "UUID", "Nút nguồn", "FK wf_node"),
            F("to_node_id", "UUID", "Nút đích", "FK wf_node"),
            F("condition_json", "jsonb", "Điều kiện chuyển", ""),
        ]),
        T("WF", "Thực thi duyệt", "wf.wf_instance", "Một lần chạy quy trình trên chứng từ", [
            F("definition_version_id", "UUID", "Version quy trình", "FK"),
            F("source_module", "varchar(10)", "Module chứng từ", ""),
            F("source_doc_type", "varchar(50)", "Loại chứng từ", ""),
            F("source_doc_id", "UUID", "ID chứng từ nguồn", "Ref mềm"),
            F("status", "varchar(30)", "Trạng thái instance", "Running/Approved/Rejected/Cancelled"),
            F("started_by", "UUID", "Người khởi tạo", ""),
            F("completed_at", "timestamptz", "Hoàn tất", ""),
        ]),
        T("WF", "Thực thi duyệt", "wf.wf_task", "Việc chờ duyệt của một bước", [
            F("instance_id", "UUID", "Instance", "FK"),
            F("node_id", "UUID", "Bước", "FK"),
            F("assignee_user_id", "UUID", "Người được gán", ""),
            F("status", "varchar(30)", "Trạng thái task", "Pending/Done/Skipped"),
            F("due_at", "timestamptz", "Hạn xử lý", ""),
            F("acted_at", "timestamptz", "Thời điểm xử lý", ""),
        ]),
        T("WF", "Thực thi duyệt", "wf.wf_task_action", "Hành động duyệt trên task", [
            F("task_id", "UUID", "Task", "FK"),
            F("action", "varchar(30)", "Hành động", "Approve/Reject/Return/Delegate"),
            F("comment", "text", "Ý kiến", ""),
            F("acted_by", "UUID", "Người thực hiện", ""),
            F("acted_at", "timestamptz", "Thời điểm", ""),
        ]),
        T("WF", "Thực thi duyệt", "wf.wf_delegation", "Ủy quyền duyệt tạm thời", [
            F("from_user_id", "UUID", "Người ủy quyền", ""),
            F("to_user_id", "UUID", "Người nhận ủy quyền", ""),
            F("valid_from", "timestamptz", "Từ", ""),
            F("valid_to", "timestamptz", "Đến", ""),
            F("scope_json", "jsonb", "Phạm vi ủy quyền", "Optional filter doc type"),
        ]),
    ]

    # ========== HRM ==========
    t += [
        T("HRM", "Danh mục nhân sự", "hrm.job_title", "Danh mục chức danh (khác JobLevel phân quyền)", [
            F("code", "varchar(40)", "Mã chức danh", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên chức danh", ""),
            F("job_level_id", "UUID", "Cấp bậc mặc định gợi ý", "Ref sys.job_level — sync sang user khi nhận việc"),
            F("is_active", "boolean", "Còn dùng", ""),
        ]),
        T("HRM", "Danh mục nhân sự", "hrm.employee_type", "Loại nhân sự (CT/TV/Part-time…)", [
            F("code", "varchar(40)", "Mã loại", ""),
            F("name", "varchar(200)", "Tên loại", ""),
            F("is_active", "boolean", "Còn dùng", ""),
        ]),
        T("HRM", "Hồ sơ nhân sự", "hrm.employee", "Hồ sơ nhân sự master", [
            F("employee_code", "varchar(40)", "Mã nhân sự", "Unique theo tenant; không tái sử dụng"),
            F("user_id", "UUID", "Tài khoản SYS", "Ref sys.app_user"),
            F("full_name", "varchar(200)", "Họ và tên", ""),
            F("dob", "date", "Ngày sinh", ""),
            F("gender", "varchar(20)", "Giới tính", ""),
            F("national_id_enc", "varchar(255)", "CCCD/CMND (mã hóa/mask)", "Field security"),
            F("email", "varchar(255)", "Email cá nhân/công ty", ""),
            F("phone", "varchar(30)", "SĐT", ""),
            F("org_unit_id", "UUID", "Chi nhánh/đơn vị chính", "Ref sys.org_unit"),
            F("department_id", "UUID", "Phòng ban chính", "Ref sys.department — đồng bộ app_user.department_id"),
            F("job_title_id", "UUID", "Chức danh", "FK job_title"),
            F("job_level_id", "UUID", "Cấp bậc", "Ref sys.job_level — đồng bộ app_user.job_level_id"),
            F("manager_employee_id", "UUID", "Quản lý trực tiếp (NS)", "FK self — map sang app_user.manager_user_id"),
            F("employee_type_id", "UUID", "Loại NS", "FK employee_type"),
            F("status", "varchar(30)", "Trạng thái NS", "Probation/Active/Terminated…"),
            F("hire_date", "date", "Ngày vào làm", ""),
            F("probation_end_date", "date", "Hết hạn thử việc", ""),
            F("terminate_date", "date", "Ngày nghỉ việc", ""),
        ]),
        T("HRM", "Hồ sơ nhân sự", "hrm.employment_status_history", "Lịch sử thay đổi trạng thái nhân sự", [
            F("employee_id", "UUID", "Nhân sự", "FK employee"),
            F("from_status", "varchar(30)", "Trạng thái cũ", ""),
            F("to_status", "varchar(30)", "Trạng thái mới", ""),
            F("effective_date", "date", "Ngày hiệu lực", ""),
            F("reason", "text", "Lý do", ""),
        ]),
        T("HRM", "Hợp đồng", "hrm.contract", "Hợp đồng lao động", [
            F("employee_id", "UUID", "Nhân sự", "FK employee"),
            F("contract_no", "varchar(50)", "Số HĐ", ""),
            F("contract_type", "varchar(30)", "Loại HĐ", ""),
            F("signed_date", "date", "Ngày ký", ""),
            F("effective_from", "date", "Hiệu lực từ", ""),
            F("effective_to", "date", "Hiệu lực đến", ""),
            F("base_salary", "numeric(18,2)", "Lương HĐ", "Nhạy cảm"),
            F("currency_code", "char(3)", "Tiền tệ lương", ""),
            F("status", "varchar(30)", "Trạng thái HĐ", "Active/Expired/Terminated"),
            F("file_id", "UUID", "File scan HĐ", "Ref sys.file_object"),
        ]),
        T("HRM", "Hợp đồng", "hrm.contract_appendix", "Phụ lục hợp đồng", [
            F("contract_id", "UUID", "Hợp đồng gốc", "FK contract"),
            F("appendix_no", "varchar(50)", "Số phụ lục", ""),
            F("effective_from", "date", "Hiệu lực từ", ""),
            F("content_summary", "text", "Tóm tắt thay đổi", ""),
            F("file_id", "UUID", "File đính kèm", ""),
        ]),
        T("HRM", "Tuyển dụng", "hrm.recruitment_request", "Phiếu đề xuất tuyển dụng", [
            *doc_fields()[:3],
            F("position_name", "varchar(200)", "Vị trí cần tuyển", ""),
            F("headcount", "int", "Số lượng", ""),
            F("org_unit_id", "UUID", "Đơn vị đề xuất", ""),
            F("reason", "text", "Lý do tuyển", ""),
            F("requested_by", "UUID", "Người đề xuất", ""),
        ]),
        T("HRM", "Tuyển dụng", "hrm.candidate", "Hồ sơ ứng viên", [
            F("full_name", "varchar(200)", "Họ tên ứng viên", ""),
            F("email", "varchar(255)", "Email", ""),
            F("phone", "varchar(30)", "SĐT", ""),
            F("request_id", "UUID", "Đề xuất tuyển liên quan", "FK optional"),
            F("source_channel", "varchar(50)", "Kênh ứng tuyển", ""),
            F("status", "varchar(30)", "Trạng thái pipeline", "New/Screening/Offer/Hired/Rejected"),
            F("cv_file_id", "UUID", "File CV", ""),
        ]),
        T("HRM", "Tuyển dụng", "hrm.job_posting", "Tin tuyển dụng", [
            F("request_id", "UUID", "Đề xuất đã duyệt", "FK"),
            F("title", "varchar(200)", "Tiêu đề tin", ""),
            F("content", "text", "Nội dung tin", ""),
            F("channel", "varchar(50)", "Kênh đăng", ""),
            F("published_at", "timestamptz", "Ngày đăng", ""),
            F("closed_at", "timestamptz", "Ngày đóng tin", ""),
            F("status", "varchar(30)", "Trạng thái tin", ""),
        ]),
        T("HRM", "Chấm công & ca", "hrm.shift_template", "Mẫu ca làm việc", [
            F("code", "varchar(40)", "Mã ca", ""),
            F("name", "varchar(100)", "Tên ca", ""),
            F("start_time", "time", "Giờ vào", ""),
            F("end_time", "time", "Giờ ra", ""),
            F("break_minutes", "int", "Phút nghỉ giữa ca", ""),
            F("is_overnight", "boolean", "Ca qua đêm", ""),
        ]),
        T("HRM", "Chấm công & ca", "hrm.shift_assignment", "Phân công ca cho nhân viên", [
            F("employee_id", "UUID", "Nhân sự", "FK"),
            F("shift_template_id", "UUID", "Mẫu ca", "FK"),
            F("work_date", "date", "Ngày làm", ""),
            F("status", "varchar(30)", "Trạng thái xếp ca", ""),
        ]),
        T("HRM", "Chấm công & ca", "hrm.attendance_punch", "Bản ghi chấm công thô", [
            F("employee_id", "UUID", "Nhân sự", "FK"),
            F("punch_time", "timestamptz", "Thời điểm chấm", ""),
            F("punch_type", "varchar(20)", "Loại", "In/Out"),
            F("source", "varchar(30)", "Nguồn", "Device/App/Manual"),
            F("device_code", "varchar(50)", "Mã máy chấm", ""),
            F("geo_lat", "numeric(10,7)", "Vĩ độ (nếu app)", ""),
            F("geo_lng", "numeric(10,7)", "Kinh độ (nếu app)", ""),
        ]),
        T("HRM", "Chấm công & ca", "hrm.timesheet", "Bảng công theo kỳ", [
            F("period_code", "varchar(20)", "Mã kỳ công", "VD 2026-08"),
            F("org_unit_id", "UUID", "Phạm vi đơn vị", ""),
            F("status", "varchar(30)", "Trạng thái", "Open/Locked"),
            F("locked_at", "timestamptz", "Thời điểm khóa", ""),
            F("locked_by", "UUID", "Người khóa", ""),
        ]),
        T("HRM", "Chấm công & ca", "hrm.timesheet_line", "Dòng công từng nhân viên trong kỳ", [
            F("timesheet_id", "UUID", "Bảng công", "FK"),
            F("employee_id", "UUID", "Nhân sự", "FK"),
            F("work_days", "numeric(8,2)", "Ngày công", ""),
            F("ot_hours", "numeric(8,2)", "Giờ OT", ""),
            F("late_minutes", "int", "Phút đi trễ", ""),
            F("leave_days", "numeric(8,2)", "Ngày nghỉ", ""),
            F("note", "varchar(500)", "Ghi chú dòng", ""),
        ]),
        T("HRM", "Nghỉ phép", "hrm.leave_type", "Danh mục loại nghỉ", [
            F("code", "varchar(40)", "Mã loại nghỉ", ""),
            F("name", "varchar(100)", "Tên loại nghỉ", ""),
            F("paid", "boolean", "Nghỉ hưởng lương", ""),
            F("affects_balance", "boolean", "Trừ quỹ phép", ""),
        ]),
        T("HRM", "Nghỉ phép", "hrm.leave_balance", "Quỹ phép của nhân viên", [
            F("employee_id", "UUID", "Nhân sự", "FK"),
            F("leave_type_id", "UUID", "Loại nghỉ", "FK"),
            F("year", "int", "Năm áp dụng", ""),
            F("entitled", "numeric(8,2)", "Được cấp", ""),
            F("used", "numeric(8,2)", "Đã dùng", ""),
            F("remaining", "numeric(8,2)", "Còn lại", "Có thể computed"),
        ]),
        T("HRM", "Nghỉ phép", "hrm.leave_request", "Đơn xin nghỉ", [
            *doc_fields()[:3],
            F("employee_id", "UUID", "Nhân sự", "FK"),
            F("leave_type_id", "UUID", "Loại nghỉ", "FK"),
            F("from_date", "date", "Từ ngày", ""),
            F("to_date", "date", "Đến ngày", ""),
            F("days", "numeric(8,2)", "Số ngày nghỉ", ""),
            F("reason", "text", "Lý do", ""),
        ]),
        T("HRM", "Lương", "hrm.payroll_period", "Kỳ tính lương", [
            F("period_code", "varchar(20)", "Mã kỳ lương", "Unique theo tenant"),
            F("from_date", "date", "Từ ngày", ""),
            F("to_date", "date", "Đến ngày", ""),
            F("status", "varchar(30)", "Trạng thái kỳ", "Open/Calculating/Posted/Locked"),
            F("timesheet_id", "UUID", "Bảng công nguồn", "Ref"),
        ]),
        T("HRM", "Lương", "hrm.payslip", "Phiếu lương nhân viên", [
            F("payroll_period_id", "UUID", "Kỳ lương", "FK"),
            F("employee_id", "UUID", "Nhân sự", "FK"),
            F("gross_amount", "numeric(18,2)", "Tổng thu nhập", "Nhạy cảm"),
            F("deduction_amount", "numeric(18,2)", "Tổng khấu trừ", ""),
            F("net_amount", "numeric(18,2)", "Thực lĩnh", ""),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("status", "varchar(30)", "Trạng thái phiếu", ""),
        ]),
        T("HRM", "Lương", "hrm.payslip_line", "Chi tiết dòng phiếu lương", [
            F("payslip_id", "UUID", "Phiếu lương", "FK"),
            F("line_type", "varchar(30)", "Loại dòng", "Earning/Deduction"),
            F("component_code", "varchar(50)", "Mã thành phần lương", ""),
            F("component_name", "varchar(200)", "Tên thành phần", ""),
            F("amount", "numeric(18,2)", "Số tiền", ""),
        ]),
        T("HRM", "Biến động & nghỉ việc", "hrm.transfer_order", "Lệnh điều động / thăng chức", [
            *doc_fields()[:3],
            F("employee_id", "UUID", "Nhân sự", "FK"),
            F("from_org_unit_id", "UUID", "Đơn vị cũ", ""),
            F("to_org_unit_id", "UUID", "Đơn vị mới", ""),
            F("from_job_title_id", "UUID", "Chức danh cũ", ""),
            F("to_job_title_id", "UUID", "Chức danh mới", ""),
            F("effective_date", "date", "Ngày hiệu lực", ""),
        ]),
        T("HRM", "Biến động & nghỉ việc", "hrm.offboarding_case", "Hồ sơ nghỉ việc / offboarding", [
            *doc_fields()[:3],
            F("employee_id", "UUID", "Nhân sự", "FK"),
            F("last_working_date", "date", "Ngày làm việc cuối", ""),
            F("reason", "text", "Lý do nghỉ", ""),
            F("checklist_status", "varchar(30)", "Tiến độ checklist", ""),
        ]),
    ]

    # ========== LMS ==========
    t += [
        T("LMS", "Nội dung đào tạo", "lms.course", "Khóa học", [
            F("code", "varchar(40)", "Mã khóa", ""),
            F("title", "varchar(200)", "Tên khóa", ""),
            F("description", "text", "Mô tả", ""),
            F("course_type", "varchar(30)", "Loại", "Online/Offline/Blended"),
            F("status", "varchar(30)", "Trạng thái", "Draft/Published/Archived"),
        ]),
        T("LMS", "Nội dung đào tạo", "lms.course_version", "Phiên bản nội dung khóa học", [
            F("course_id", "UUID", "Khóa học", "FK"),
            F("version_no", "int", "Số version", ""),
            F("is_current", "boolean", "Bản đang dùng", ""),
            F("published_at", "timestamptz", "Ngày xuất bản", ""),
        ]),
        T("LMS", "Nội dung đào tạo", "lms.lesson", "Bài học trong khóa", [
            F("course_version_id", "UUID", "Version khóa", "FK"),
            F("title", "varchar(200)", "Tiêu đề bài", ""),
            F("sort_order", "int", "Thứ tự", ""),
            F("content_type", "varchar(30)", "Loại nội dung", "Video/Doc/SCORM…"),
            F("content_ref", "varchar(500)", "Tham chiếu nội dung/file", ""),
            F("duration_minutes", "int", "Thời lượng ước tính", ""),
        ]),
        T("LMS", "Nội dung đào tạo", "lms.assessment", "Bài kiểm tra / bài thi", [
            F("course_version_id", "UUID", "Version khóa", "FK"),
            F("title", "varchar(200)", "Tên bài kiểm tra", ""),
            F("pass_score", "numeric(5,2)", "Điểm đạt", ""),
            F("max_attempts", "int", "Số lần làm tối đa", ""),
            F("time_limit_minutes", "int", "Thời gian làm bài", ""),
        ]),
        T("LMS", "Ghi danh & tiến độ", "lms.enrollment", "Ghi danh học viên vào khóa", [
            F("course_id", "UUID", "Khóa học", "FK"),
            F("learner_user_id", "UUID", "User học viên", "Ref sys.app_user"),
            F("employee_id", "UUID", "NV (nếu có)", "Ref hrm.employee"),
            F("enrolled_at", "timestamptz", "Thời điểm ghi danh", ""),
            F("status", "varchar(30)", "Trạng thái học", "Enrolled/InProgress/Completed/Failed"),
            F("progress_percent", "numeric(5,2)", "% hoàn thành", ""),
        ]),
        T("LMS", "Ghi danh & tiến độ", "lms.assessment_attempt", "Lần làm bài kiểm tra", [
            F("assessment_id", "UUID", "Bài kiểm tra", "FK"),
            F("enrollment_id", "UUID", "Ghi danh", "FK"),
            F("attempt_no", "int", "Lần thứ", ""),
            F("score", "numeric(5,2)", "Điểm", ""),
            F("passed", "boolean", "Đạt/không đạt", ""),
            F("started_at", "timestamptz", "Bắt đầu", ""),
            F("submitted_at", "timestamptz", "Nộp bài", ""),
        ]),
        T("LMS", "Ghi danh & tiến độ", "lms.certificate", "Chứng chỉ hoàn thành", [
            F("enrollment_id", "UUID", "Ghi danh", "FK"),
            F("certificate_no", "varchar(50)", "Số chứng chỉ", ""),
            F("issued_at", "timestamptz", "Ngày cấp", ""),
            F("expires_at", "date", "Hết hạn (nếu có)", ""),
            F("file_id", "UUID", "File chứng chỉ", ""),
        ]),
        T("LMS", "Lớp học", "lms.training_class", "Lớp đào tạo offline/hybrid", [
            F("course_id", "UUID", "Khóa học", "FK"),
            F("class_code", "varchar(40)", "Mã lớp", ""),
            F("start_date", "date", "Ngày bắt đầu", ""),
            F("end_date", "date", "Ngày kết thúc", ""),
            F("location", "varchar(255)", "Địa điểm", ""),
            F("instructor_name", "varchar(200)", "Giảng viên", ""),
            F("capacity", "int", "Sĩ số tối đa", ""),
            F("status", "varchar(30)", "Trạng thái lớp", ""),
        ]),
    ]

    # ========== CRM ==========
    t += [
        T("CRM", "Khách hàng", "crm.customer", "Khách hàng / tổ chức mua hàng", [
            F("code", "varchar(40)", "Mã KH", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên KH", ""),
            F("customer_type", "varchar(30)", "Loại KH", "Company/Individual"),
            F("tax_code", "varchar(50)", "Mã số thuế", ""),
            F("phone", "varchar(30)", "SĐT", ""),
            F("email", "varchar(255)", "Email", ""),
            F("billing_address", "text", "Địa chỉ xuất HĐ", ""),
            F("shipping_address", "text", "Địa chỉ giao mặc định", ""),
            F("owner_user_id", "UUID", "NV phụ trách", ""),
            F("status", "varchar(30)", "Trạng thái", "Active/Inactive"),
            F("credit_limit", "numeric(18,2)", "Hạn mức công nợ", ""),
        ]),
        T("CRM", "Khách hàng", "crm.contact", "Người liên hệ của khách hàng", [
            F("customer_id", "UUID", "Khách hàng", "FK"),
            F("full_name", "varchar(200)", "Họ tên", ""),
            F("title", "varchar(100)", "Chức danh", ""),
            F("email", "varchar(255)", "Email", ""),
            F("phone", "varchar(30)", "SĐT", ""),
            F("is_primary", "boolean", "Liên hệ chính", ""),
        ]),
        T("CRM", "Phễu bán", "crm.lead", "Đầu mối tiềm năng", [
            F("full_name", "varchar(200)", "Tên lead", ""),
            F("company_name", "varchar(200)", "Công ty", ""),
            F("phone", "varchar(30)", "SĐT", ""),
            F("email", "varchar(255)", "Email", ""),
            F("source", "varchar(50)", "Nguồn lead", ""),
            F("status", "varchar(30)", "Trạng thái", "New/Qualified/Disqualified/Converted"),
            F("owner_user_id", "UUID", "NV phụ trách", ""),
        ]),
        T("CRM", "Phễu bán", "crm.opportunity", "Cơ hội bán hàng", [
            F("name", "varchar(200)", "Tên cơ hội", ""),
            F("customer_id", "UUID", "KH", "FK optional"),
            F("lead_id", "UUID", "Lead nguồn", "FK optional"),
            F("stage", "varchar(30)", "Giai đoạn pipeline", ""),
            F("amount", "numeric(18,2)", "Giá trị ước tính", ""),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("expected_close_date", "date", "Ngày chốt dự kiến", ""),
            F("probability", "numeric(5,2)", "% thành công", ""),
            F("owner_user_id", "UUID", "NV phụ trách", ""),
            F("status", "varchar(30)", "Open/Won/Lost", ""),
        ]),
        T("CRM", "Báo giá & đơn", "crm.quote", "Báo giá", [
            *doc_fields(),
            F("customer_id", "UUID", "KH", "FK"),
            F("opportunity_id", "UUID", "Cơ hội", "Optional"),
            F("valid_until", "date", "Hiệu lực đến", ""),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("total_amount", "numeric(18,2)", "Tổng tiền", ""),
        ], doc=False),
        T("CRM", "Báo giá & đơn", "crm.quote_line", "Dòng báo giá", [
            F("quote_id", "UUID", "Báo giá", "FK"),
            F("line_no", "int", "Số dòng", ""),
            F("item_id", "UUID", "Hàng hóa", "Ref inv.item"),
            F("item_code_snapshot", "varchar(40)", "Mã hàng snapshot", ""),
            F("item_name_snapshot", "varchar(200)", "Tên hàng snapshot", ""),
            F("qty", "numeric(18,6)", "Số lượng", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("unit_price", "numeric(18,4)", "Đơn giá", ""),
            F("discount_percent", "numeric(9,4)", "% CK", ""),
            F("line_amount", "numeric(18,2)", "Thành tiền", ""),
        ]),
        T("CRM", "Báo giá & đơn", "crm.sales_order", "Đơn bán hàng", [
            *doc_fields(),
            F("customer_id", "UUID", "KH", "FK"),
            F("quote_id", "UUID", "Báo giá nguồn", "Optional"),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("total_amount", "numeric(18,2)", "Tổng tiền", ""),
            F("warehouse_id", "UUID", "Kho xuất dự kiến", "Ref inv.warehouse"),
            F("promised_date", "date", "Ngày giao hẹn", ""),
        ], doc=False),
        T("CRM", "Báo giá & đơn", "crm.sales_order_line", "Dòng đơn bán", [
            F("sales_order_id", "UUID", "Đơn bán", "FK"),
            F("line_no", "int", "Số dòng", ""),
            F("item_id", "UUID", "Hàng hóa", "Ref inv.item"),
            F("item_code_snapshot", "varchar(40)", "Mã hàng snapshot", ""),
            F("item_name_snapshot", "varchar(200)", "Tên hàng snapshot", ""),
            F("qty", "numeric(18,6)", "Số lượng đặt", ""),
            F("qty_delivered", "numeric(18,6)", "Số lượng đã giao", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("unit_price", "numeric(18,4)", "Đơn giá", ""),
            F("line_amount", "numeric(18,2)", "Thành tiền", ""),
        ]),
        T("CRM", "Marketing & CSKH", "crm.campaign", "Chiến dịch marketing", [
            F("code", "varchar(40)", "Mã chiến dịch", ""),
            F("name", "varchar(200)", "Tên chiến dịch", ""),
            F("channel", "varchar(50)", "Kênh", ""),
            F("start_date", "date", "Bắt đầu", ""),
            F("end_date", "date", "Kết thúc", ""),
            F("budget", "numeric(18,2)", "Ngân sách", ""),
            F("status", "varchar(30)", "Trạng thái", ""),
        ]),
        T("CRM", "Marketing & CSKH", "crm.sales_case", "Case / khiếu nại CSKH", [
            *doc_fields()[:3],
            F("customer_id", "UUID", "KH", "FK"),
            F("subject", "varchar(200)", "Tiêu đề", ""),
            F("priority", "varchar(20)", "Mức ưu tiên", ""),
            F("channel", "varchar(30)", "Kênh tiếp nhận", ""),
            F("owner_user_id", "UUID", "Người xử lý", ""),
        ]),
    ]

    # ========== POS ==========
    t += [
        T("POS", "Cấu hình điểm bán", "pos.store", "Cửa hàng / điểm bán", [
            F("code", "varchar(40)", "Mã CH", ""),
            F("name", "varchar(200)", "Tên CH", ""),
            F("org_unit_id", "UUID", "Đơn vị tổ chức", "Ref sys.org_unit"),
            F("warehouse_id", "UUID", "Kho gắn CH", "Ref inv.warehouse"),
            F("address", "text", "Địa chỉ", ""),
            F("is_active", "boolean", "Đang hoạt động", ""),
        ]),
        T("POS", "Cấu hình điểm bán", "pos.terminal", "Máy POS / terminal", [
            F("store_id", "UUID", "Cửa hàng", "FK"),
            F("code", "varchar(40)", "Mã máy", ""),
            F("name", "varchar(100)", "Tên máy", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("POS", "Cấu hình điểm bán", "pos.price_list", "Bảng giá bán", [
            F("code", "varchar(40)", "Mã bảng giá", ""),
            F("name", "varchar(100)", "Tên bảng giá", ""),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("valid_from", "date", "Hiệu lực từ", ""),
            F("valid_to", "date", "Hiệu lực đến", ""),
            F("is_active", "boolean", "Đang áp dụng", ""),
        ]),
        T("POS", "Cấu hình điểm bán", "pos.price_list_item", "Giá theo sản phẩm trong bảng giá", [
            F("price_list_id", "UUID", "Bảng giá", "FK"),
            F("item_id", "UUID", "Hàng", "Ref inv.item"),
            F("unit_price", "numeric(18,4)", "Đơn giá", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
        ]),
        T("POS", "Giao dịch bán", "pos.cash_shift", "Ca quỹ thu ngân", [
            F("store_id", "UUID", "Cửa hàng", "FK"),
            F("terminal_id", "UUID", "Máy POS", "FK"),
            F("cashier_user_id", "UUID", "Thu ngân", ""),
            F("opened_at", "timestamptz", "Mở ca", ""),
            F("closed_at", "timestamptz", "Đóng ca", ""),
            F("opening_amount", "numeric(18,2)", "Tiền đầu ca", ""),
            F("closing_amount", "numeric(18,2)", "Tiền cuối ca", ""),
            F("status", "varchar(30)", "Open/Closed", ""),
        ]),
        T("POS", "Giao dịch bán", "pos.pos_order", "Hóa đơn / giao dịch bán tại quầy", [
            F("shift_id", "UUID", "Ca quỹ", "FK"),
            F("doc_no", "varchar(50)", "Số HĐ", ""),
            F("customer_id", "UUID", "KH (nếu có)", "Ref crm.customer"),
            F("order_time", "timestamptz", "Thời điểm bán", ""),
            F("status", "varchar(30)", "Completed/Void/Returned", ""),
            F("total_amount", "numeric(18,2)", "Tổng tiền", ""),
            F("currency_code", "char(3)", "Tiền tệ", ""),
        ]),
        T("POS", "Giao dịch bán", "pos.pos_order_line", "Dòng hàng trên hóa đơn POS", [
            F("pos_order_id", "UUID", "Hóa đơn", "FK"),
            F("line_no", "int", "Số dòng", ""),
            F("item_id", "UUID", "Hàng bán", "Ref inv.item"),
            F("qty", "numeric(18,6)", "Số lượng", ""),
            F("unit_price", "numeric(18,4)", "Đơn giá", ""),
            F("line_amount", "numeric(18,2)", "Thành tiền", ""),
            F("discount_amount", "numeric(18,2)", "Chiết khấu dòng", ""),
        ]),
        T("POS", "Giao dịch bán", "pos.pos_payment", "Thanh toán của hóa đơn POS", [
            F("pos_order_id", "UUID", "Hóa đơn", "FK"),
            F("method", "varchar(30)", "Phương thức", "Cash/Card/QR/Transfer"),
            F("amount", "numeric(18,2)", "Số tiền", ""),
            F("ref_no", "varchar(100)", "Mã tham chiếu giao dịch", ""),
            F("paid_at", "timestamptz", "Thời điểm thanh toán", ""),
        ]),
        T("POS", "Định mức", "pos.recipe", "Định mức trừ kho cho món/SP", [
            F("item_id", "UUID", "SP bán", "Ref inv.item"),
            F("name", "varchar(200)", "Tên định mức", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("POS", "Định mức", "pos.recipe_line", "Dòng NVL trong định mức", [
            F("recipe_id", "UUID", "Định mức", "FK"),
            F("component_item_id", "UUID", "NVL", "Ref inv.item"),
            F("qty", "numeric(18,6)", "Định mức NVL / 1 SP", ""),
            F("uom", "varchar(20)", "ĐVT NVL", ""),
        ]),
    ]

    # ========== PUR ==========
    t += [
        T("PUR", "Nhà cung cấp", "pur.vendor", "Nhà cung cấp", [
            F("code", "varchar(40)", "Mã NCC", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên NCC", ""),
            F("tax_code", "varchar(50)", "MST", ""),
            F("phone", "varchar(30)", "SĐT", ""),
            F("email", "varchar(255)", "Email", ""),
            F("address", "text", "Địa chỉ", ""),
            F("payment_term_days", "int", "Công nợ (ngày)", ""),
            F("status", "varchar(30)", "Active/Inactive", ""),
        ]),
        T("PUR", "Nhà cung cấp", "pur.vendor_item_price", "Bảng giá mua theo NCC–hàng", [
            F("vendor_id", "UUID", "NCC", "FK"),
            F("item_id", "UUID", "Hàng", "Ref inv.item"),
            F("unit_price", "numeric(18,4)", "Đơn giá mua", ""),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("valid_from", "date", "Hiệu lực từ", ""),
            F("valid_to", "date", "Hiệu lực đến", ""),
            F("min_qty", "numeric(18,6)", "SL tối thiểu", ""),
        ]),
        T("PUR", "Chứng từ mua", "pur.purchase_requisition", "Phiếu yêu cầu mua hàng (PR)", [
            *doc_fields(),
            F("requested_by", "UUID", "Người yêu cầu", ""),
            F("needed_date", "date", "Ngày cần hàng", ""),
        ], doc=False),
        T("PUR", "Chứng từ mua", "pur.purchase_requisition_line", "Dòng PR", [
            F("pr_id", "UUID", "PR", "FK"),
            F("line_no", "int", "Số dòng", ""),
            F("item_id", "UUID", "Hàng", "Ref inv.item"),
            F("qty", "numeric(18,6)", "SL yêu cầu", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("needed_date", "date", "Ngày cần", ""),
        ]),
        T("PUR", "Chứng từ mua", "pur.purchase_order", "Đơn mua hàng (PO)", [
            *doc_fields(),
            F("vendor_id", "UUID", "NCC", "FK"),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("total_amount", "numeric(18,2)", "Tổng tiền", ""),
            F("expected_date", "date", "Ngày giao dự kiến", ""),
            F("warehouse_id", "UUID", "Kho nhận", "Ref inv.warehouse"),
        ], doc=False),
        T("PUR", "Chứng từ mua", "pur.purchase_order_line", "Dòng PO", [
            F("po_id", "UUID", "PO", "FK"),
            F("line_no", "int", "Số dòng", ""),
            F("item_id", "UUID", "Hàng", "Ref inv.item"),
            F("qty_ordered", "numeric(18,6)", "SL đặt", ""),
            F("qty_received", "numeric(18,6)", "SL đã nhận", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("unit_price", "numeric(18,4)", "Đơn giá", ""),
            F("line_amount", "numeric(18,2)", "Thành tiền", ""),
        ]),
        T("PUR", "Chứng từ mua", "pur.goods_receipt", "Phiếu nhập hàng từ NCC (GRN)", [
            *doc_fields(),
            F("po_id", "UUID", "PO nguồn", "FK optional"),
            F("vendor_id", "UUID", "NCC", "FK"),
            F("warehouse_id", "UUID", "Kho nhận", "Ref inv.warehouse"),
            F("received_at", "timestamptz", "Thời điểm nhận", ""),
        ], doc=False),
        T("PUR", "Chứng từ mua", "pur.goods_receipt_line", "Dòng GRN", [
            F("grn_id", "UUID", "GRN", "FK"),
            F("po_line_id", "UUID", "Dòng PO", "Optional"),
            F("item_id", "UUID", "Hàng", "Ref inv.item"),
            F("qty_received", "numeric(18,6)", "SL nhận", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("lot_code", "varchar(50)", "Mã lô (nếu có)", ""),
        ]),
    ]

    # ========== INV ==========
    t += [
        T("INV", "Master hàng hóa", "inv.item", "Danh mục hàng hóa / NVL / TP / dịch vụ", [
            F("code", "varchar(40)", "Mã hàng (SKU)", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên hàng", ""),
            F("item_type", "varchar(30)", "Loại", "Goods/Service/Raw/Finished/Recipe"),
            F("category_id", "UUID", "Nhóm hàng", "FK item_category"),
            F("base_uom", "varchar(20)", "ĐVT cơ bản", ""),
            F("is_stockable", "boolean", "Quản lý tồn kho", ""),
            F("is_sales_item", "boolean", "Được bán", ""),
            F("is_purchase_item", "boolean", "Được mua", ""),
            F("status", "varchar(30)", "Active/Inactive", ""),
        ]),
        T("INV", "Master hàng hóa", "inv.item_category", "Nhóm hàng hóa", [
            F("code", "varchar(40)", "Mã nhóm", ""),
            F("name", "varchar(200)", "Tên nhóm", ""),
            F("parent_id", "UUID", "Nhóm cha", "Self FK"),
        ]),
        T("INV", "Master hàng hóa", "inv.uom_conversion", "Quy đổi đơn vị tính theo hàng", [
            F("item_id", "UUID", "Hàng", "FK"),
            F("from_uom", "varchar(20)", "ĐVT nguồn", ""),
            F("to_uom", "varchar(20)", "ĐVT đích", ""),
            F("factor", "numeric(18,8)", "Hệ số quy đổi", ""),
        ]),
        T("INV", "Kho & vị trí", "inv.warehouse", "Kho hàng", [
            F("code", "varchar(40)", "Mã kho", ""),
            F("name", "varchar(200)", "Tên kho", ""),
            F("org_unit_id", "UUID", "Đơn vị quản lý", "Ref sys.org_unit"),
            F("address", "text", "Địa chỉ kho", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("INV", "Kho & vị trí", "inv.bin_location", "Vị trí / ngăn trong kho", [
            F("warehouse_id", "UUID", "Kho", "FK"),
            F("code", "varchar(40)", "Mã vị trí", ""),
            F("name", "varchar(100)", "Tên vị trí", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("INV", "Tồn kho", "inv.stock_balance", "Tồn kho hiện tại theo chiều item–kho–vị trí–lô", [
            F("item_id", "UUID", "Hàng", "FK"),
            F("warehouse_id", "UUID", "Kho", "FK"),
            F("bin_id", "UUID", "Vị trí", "FK optional"),
            F("lot_id", "UUID", "Lô", "FK optional"),
            F("qty_on_hand", "numeric(18,6)", "Tồn thực tế", ""),
            F("qty_reserved", "numeric(18,6)", "Tồn đã giữ", ""),
            F("qty_available", "numeric(18,6)", "Tồn khả dụng", "on_hand - reserved"),
        ]),
        T("INV", "Tồn kho", "inv.lot", "Lô hàng", [
            F("item_id", "UUID", "Hàng", "FK"),
            F("lot_code", "varchar(50)", "Mã lô", ""),
            F("manufacture_date", "date", "NSX", ""),
            F("expiry_date", "date", "HSD", ""),
        ]),
        T("INV", "Tồn kho", "inv.serial_no", "Số serial theo từng đơn vị hàng", [
            F("item_id", "UUID", "Hàng", "FK"),
            F("serial", "varchar(100)", "Số serial", "Unique theo tenant"),
            F("status", "varchar(30)", "InStock/Issued/Scrapped", ""),
            F("warehouse_id", "UUID", "Kho hiện tại", ""),
        ]),
        T("INV", "Chứng từ kho", "inv.stock_document", "Chứng từ kho (nhập/xuất/chuyển/điều chỉnh)", [
            *doc_fields(),
            F("doc_type", "varchar(30)", "Loại CT", "In/Out/Transfer/Adjust"),
            F("warehouse_id", "UUID", "Kho chính", "FK"),
            F("warehouse_to_id", "UUID", "Kho đích (chuyển)", "Optional"),
            F("source_module", "varchar(10)", "Module nguồn", ""),
            F("source_doc_id", "UUID", "ID chứng từ nguồn", ""),
            F("posted_at", "timestamptz", "Thời điểm post tồn", ""),
        ], doc=False),
        T("INV", "Chứng từ kho", "inv.stock_document_line", "Dòng chứng từ kho", [
            F("stock_document_id", "UUID", "Chứng từ kho", "FK"),
            F("line_no", "int", "Số dòng", ""),
            F("item_id", "UUID", "Hàng", "FK"),
            F("qty", "numeric(18,6)", "Số lượng", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("bin_id", "UUID", "Vị trí", ""),
            F("lot_id", "UUID", "Lô", ""),
            F("unit_cost", "numeric(18,4)", "Đơn giá vốn", "Optional"),
        ]),
        T("INV", "Giữ hàng", "inv.reservation", "Phiếu giữ hàng (reserve)", [
            F("source_module", "varchar(10)", "Module nguồn", "CRM/POS/MFG…"),
            F("source_doc_type", "varchar(50)", "Loại chứng từ nguồn", ""),
            F("source_doc_id", "UUID", "ID chứng từ nguồn", ""),
            F("warehouse_id", "UUID", "Kho giữ", "FK"),
            F("status", "varchar(30)", "Active/Released/Consumed/Cancelled", ""),
            F("expires_at", "timestamptz", "Hết hạn giữ", ""),
        ]),
        T("INV", "Giữ hàng", "inv.reservation_line", "Dòng giữ hàng", [
            F("reservation_id", "UUID", "Phiếu giữ", "FK"),
            F("item_id", "UUID", "Hàng", "FK"),
            F("qty", "numeric(18,6)", "SL giữ", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
        ]),
        T("INV", "Kiểm kê", "inv.stock_count", "Phiếu kiểm kê", [
            *doc_fields(),
            F("warehouse_id", "UUID", "Kho kiểm", "FK"),
            F("counted_at", "timestamptz", "Thời điểm kiểm", ""),
        ], doc=False),
        T("INV", "Kiểm kê", "inv.stock_count_line", "Dòng kiểm kê", [
            F("stock_count_id", "UUID", "Phiếu kiểm", "FK"),
            F("item_id", "UUID", "Hàng", "FK"),
            F("system_qty", "numeric(18,6)", "SL sổ", ""),
            F("counted_qty", "numeric(18,6)", "SL thực đếm", ""),
            F("variance_qty", "numeric(18,6)", "Chênh lệch", ""),
            F("bin_id", "UUID", "Vị trí", ""),
            F("lot_id", "UUID", "Lô", ""),
        ]),
    ]

    # ========== LOG ==========
    t += [
        T("LOG", "Vận hành giao hàng", "log.carrier", "Đơn vị vận chuyển / 3PL", [
            F("code", "varchar(40)", "Mã ĐVVC", ""),
            F("name", "varchar(200)", "Tên ĐVVC", ""),
            F("contact_phone", "varchar(30)", "SĐT", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("LOG", "Vận hành giao hàng", "log.vehicle", "Phương tiện giao hàng", [
            F("plate_no", "varchar(20)", "Biển số", ""),
            F("vehicle_type", "varchar(30)", "Loại xe", ""),
            F("capacity_kg", "numeric(18,2)", "Tải trọng", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("LOG", "Vận hành giao hàng", "log.driver", "Tài xế / nhân viên giao", [
            F("full_name", "varchar(200)", "Họ tên", ""),
            F("phone", "varchar(30)", "SĐT", ""),
            F("employee_id", "UUID", "Liên kết NS (nếu có)", "Ref hrm.employee"),
            F("license_no", "varchar(50)", "Số GPLX", ""),
            F("is_active", "boolean", "Đang làm việc", ""),
        ]),
        T("LOG", "Vận hành giao hàng", "log.shipment", "Chuyến / lô giao hàng", [
            *doc_fields(),
            F("source_module", "varchar(10)", "Module nguồn đơn", "CRM…"),
            F("source_doc_id", "UUID", "ID đơn nguồn", ""),
            F("customer_id", "UUID", "KH nhận", "Ref crm.customer"),
            F("carrier_id", "UUID", "ĐVVC", "FK optional"),
            F("driver_id", "UUID", "Tài xế", "FK optional"),
            F("vehicle_id", "UUID", "Xe", "FK optional"),
            F("shipped_at", "timestamptz", "Xuất giao", ""),
            F("delivered_at", "timestamptz", "Giao xong", ""),
            F("cod_amount", "numeric(18,2)", "Tiền COD", ""),
        ], doc=False),
        T("LOG", "Vận hành giao hàng", "log.shipment_line", "Dòng hàng trên chuyến giao", [
            F("shipment_id", "UUID", "Chuyến giao", "FK"),
            F("item_id", "UUID", "Hàng", "Ref inv.item"),
            F("qty", "numeric(18,6)", "SL giao", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("sales_order_line_id", "UUID", "Dòng SO nguồn", "Optional"),
        ]),
        T("LOG", "Vận hành giao hàng", "log.shipment_tracking", "Mốc tracking trạng thái giao", [
            F("shipment_id", "UUID", "Chuyến giao", "FK"),
            F("tracking_time", "timestamptz", "Thời điểm", ""),
            F("status_code", "varchar(30)", "Mã trạng thái", ""),
            F("description", "varchar(500)", "Mô tả", ""),
            F("location_text", "varchar(255)", "Vị trí", ""),
        ]),
        T("LOG", "Vận hành giao hàng", "log.cod_collection", "Thu hộ COD", [
            F("shipment_id", "UUID", "Chuyến giao", "FK"),
            F("amount", "numeric(18,2)", "Số tiền COD", ""),
            F("collected_at", "timestamptz", "Thời điểm thu", ""),
            F("status", "varchar(30)", "Collected/Remitted", ""),
            F("fin_doc_id", "UUID", "Chứng từ FIN liên quan", "Ref mềm"),
        ]),
    ]

    # ========== MFG ==========
    t += [
        T("MFG", "Định mức & quy trình", "mfg.bom_header", "BOM định mức NVL cho thành phẩm", [
            F("item_id", "UUID", "Thành phẩm", "Ref inv.item"),
            F("code", "varchar(40)", "Mã BOM", ""),
            F("version_no", "int", "Version BOM", ""),
            F("is_active", "boolean", "Đang dùng", ""),
            F("effective_from", "date", "Hiệu lực từ", ""),
        ]),
        T("MFG", "Định mức & quy trình", "mfg.bom_line", "Dòng NVL trong BOM", [
            F("bom_id", "UUID", "BOM", "FK"),
            F("component_item_id", "UUID", "NVL", "Ref inv.item"),
            F("qty", "numeric(18,6)", "Định mức / 1 TP", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("scrap_percent", "numeric(9,4)", "% hao hụt", ""),
        ]),
        T("MFG", "Định mức & quy trình", "mfg.routing", "Quy trình sản xuất", [
            F("item_id", "UUID", "TP áp dụng", "Ref inv.item"),
            F("code", "varchar(40)", "Mã routing", ""),
            F("name", "varchar(200)", "Tên quy trình", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("MFG", "Định mức & quy trình", "mfg.routing_operation", "Công đoạn trong routing", [
            F("routing_id", "UUID", "Routing", "FK"),
            F("op_seq", "int", "Thứ tự công đoạn", ""),
            F("op_name", "varchar(200)", "Tên công đoạn", ""),
            F("work_center", "varchar(100)", "Tổ/máy", ""),
            F("std_minutes", "numeric(10,2)", "Thời gian chuẩn (phút)", ""),
        ]),
        T("MFG", "Lệnh sản xuất", "mfg.work_order", "Lệnh sản xuất", [
            *doc_fields(),
            F("item_id", "UUID", "Thành phẩm", "Ref inv.item"),
            F("bom_id", "UUID", "BOM dùng", "FK optional"),
            F("routing_id", "UUID", "Routing dùng", "FK optional"),
            F("qty_planned", "numeric(18,6)", "SL kế hoạch", ""),
            F("qty_completed", "numeric(18,6)", "SL hoàn thành", ""),
            F("warehouse_id", "UUID", "Kho NVL/TP", "Ref inv.warehouse"),
            F("due_date", "date", "Hạn hoàn thành", ""),
        ], doc=False),
        T("MFG", "Lệnh sản xuất", "mfg.work_order_material", "NVL cấp phát / định mức cho LSX", [
            F("work_order_id", "UUID", "LSX", "FK"),
            F("item_id", "UUID", "NVL", "Ref inv.item"),
            F("qty_required", "numeric(18,6)", "SL cần", ""),
            F("qty_issued", "numeric(18,6)", "SL đã xuất", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
        ]),
        T("MFG", "Lệnh sản xuất", "mfg.work_order_output", "Nhập thành phẩm từ LSX", [
            F("work_order_id", "UUID", "LSX", "FK"),
            F("item_id", "UUID", "TP", "Ref inv.item"),
            F("qty", "numeric(18,6)", "SL nhập", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("lot_id", "UUID", "Lô TP", "Optional"),
            F("stock_document_id", "UUID", "CT nhập kho", "Ref inv.stock_document"),
        ]),
        T("MFG", "QC", "mfg.qc_inspection", "Phiếu kiểm chất lượng", [
            *doc_fields()[:3],
            F("work_order_id", "UUID", "LSX", "FK optional"),
            F("lot_id", "UUID", "Lô kiểm", ""),
            F("result", "varchar(20)", "Pass/Fail/Conditional", ""),
            F("inspected_at", "timestamptz", "Thời điểm kiểm", ""),
            F("inspected_by", "UUID", "Người kiểm", ""),
        ]),
    ]

    # ========== FIN ==========
    t += [
        T("FIN", "Danh mục kế toán", "fin.account", "Hệ thống tài khoản kế toán (COA)", [
            F("code", "varchar(30)", "Số hiệu TK", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên TK", ""),
            F("account_type", "varchar(30)", "Loại TK", "Asset/Liability/Equity/Revenue/Expense"),
            F("parent_id", "UUID", "TK cha", "Self FK"),
            F("is_postable", "boolean", "Được hạch toán trực tiếp", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("FIN", "Danh mục kế toán", "fin.fiscal_year", "Năm tài chính", [
            F("year_code", "varchar(10)", "Mã năm", "VD 2026"),
            F("start_date", "date", "Ngày bắt đầu", ""),
            F("end_date", "date", "Ngày kết thúc", ""),
            F("status", "varchar(20)", "Open/Closed", ""),
        ]),
        T("FIN", "Danh mục kế toán", "fin.fiscal_period", "Kỳ kế toán (tháng/quý)", [
            F("fiscal_year_id", "UUID", "Năm TC", "FK"),
            F("period_code", "varchar(20)", "Mã kỳ", "VD 2026-08"),
            F("start_date", "date", "Từ ngày", ""),
            F("end_date", "date", "Đến ngày", ""),
            F("status", "varchar(20)", "Open/Closed", ""),
        ]),
        T("FIN", "Sổ cái", "fin.journal_entry", "Chứng từ ghi sổ / bút toán", [
            *doc_fields(),
            F("fiscal_period_id", "UUID", "Kỳ KT", "FK"),
            F("source_module", "varchar(10)", "Module nguồn", ""),
            F("source_doc_id", "UUID", "ID chứng từ nguồn", ""),
            F("posted_at", "timestamptz", "Thời điểm post", ""),
            F("total_debit", "numeric(18,2)", "Tổng Nợ", ""),
            F("total_credit", "numeric(18,2)", "Tổng Có", "Phải = Nợ khi posted"),
        ], doc=False),
        T("FIN", "Sổ cái", "fin.journal_line", "Dòng Nợ/Có của bút toán", [
            F("journal_id", "UUID", "Bút toán", "FK"),
            F("line_no", "int", "Số dòng", ""),
            F("account_id", "UUID", "Tài khoản", "FK account"),
            F("debit", "numeric(18,2)", "Phát sinh Nợ", "≥ 0"),
            F("credit", "numeric(18,2)", "Phát sinh Có", "≥ 0"),
            F("cost_center_id", "UUID", "Trung tâm CP", "Optional"),
            F("partner_type", "varchar(20)", "Loại đối tượng", "Customer/Vendor/Employee"),
            F("partner_id", "UUID", "ID đối tượng", "Ref mềm"),
            F("memo", "varchar(500)", "Diễn giải dòng", ""),
        ]),
        T("FIN", "Công nợ phải thu", "fin.ar_invoice", "Hóa đơn phải thu", [
            *doc_fields(),
            F("customer_id", "UUID", "KH", "Ref crm.customer"),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("total_amount", "numeric(18,2)", "Tổng tiền HĐ", ""),
            F("open_amount", "numeric(18,2)", "Còn phải thu", ""),
            F("due_date", "date", "Hạn thanh toán", ""),
        ], doc=False),
        T("FIN", "Công nợ phải thu", "fin.ar_receipt", "Phiếu thu tiền KH", [
            *doc_fields(),
            F("customer_id", "UUID", "KH", "Ref crm.customer"),
            F("amount", "numeric(18,2)", "Số tiền thu", ""),
            F("method", "varchar(30)", "Phương thức thu", ""),
            F("bank_account_id", "UUID", "TKNH/quỹ", "Optional"),
        ], doc=False),
        T("FIN", "Công nợ phải thu", "fin.ar_allocation", "Khớp phiếu thu với hóa đơn", [
            F("receipt_id", "UUID", "Phiếu thu", "FK"),
            F("invoice_id", "UUID", "Hóa đơn AR", "FK"),
            F("amount", "numeric(18,2)", "Số tiền khớp", ""),
        ]),
        T("FIN", "Công nợ phải trả", "fin.ap_invoice", "Hóa đơn phải trả NCC", [
            *doc_fields(),
            F("vendor_id", "UUID", "NCC", "Ref pur.vendor"),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("total_amount", "numeric(18,2)", "Tổng tiền", ""),
            F("open_amount", "numeric(18,2)", "Còn phải trả", ""),
            F("due_date", "date", "Hạn thanh toán", ""),
            F("po_id", "UUID", "PO liên quan", "Optional"),
        ], doc=False),
        T("FIN", "Công nợ phải trả", "fin.ap_payment", "Phiếu chi trả NCC", [
            *doc_fields(),
            F("vendor_id", "UUID", "NCC", "Ref pur.vendor"),
            F("amount", "numeric(18,2)", "Số tiền chi", ""),
            F("method", "varchar(30)", "Phương thức chi", ""),
            F("bank_account_id", "UUID", "TKNH/quỹ", ""),
        ], doc=False),
        T("FIN", "Quỹ & ngân hàng", "fin.bank_account", "Tài khoản ngân hàng / quỹ", [
            F("code", "varchar(40)", "Mã TK", ""),
            F("name", "varchar(200)", "Tên TK/quỹ", ""),
            F("account_kind", "varchar(20)", "Bank/Cash", ""),
            F("bank_name", "varchar(200)", "Ngân hàng", ""),
            F("account_number", "varchar(50)", "Số TK", ""),
            F("currency_code", "char(3)", "Tiền tệ", ""),
            F("gl_account_id", "UUID", "TK kế toán map", "FK account"),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("FIN", "Quỹ & ngân hàng", "fin.bank_transaction", "Giao dịch ngân hàng / quỹ", [
            F("bank_account_id", "UUID", "TK/quỹ", "FK"),
            F("txn_date", "date", "Ngày GD", ""),
            F("amount", "numeric(18,2)", "Số tiền (+/-)", ""),
            F("description", "varchar(500)", "Diễn giải", ""),
            F("ref_no", "varchar(100)", "Số tham chiếu", ""),
            F("source_doc_id", "UUID", "Chứng từ nguồn", ""),
        ]),
        T("FIN", "Danh mục kế toán", "fin.cost_center", "Trung tâm chi phí", [
            F("code", "varchar(40)", "Mã TTCP", ""),
            F("name", "varchar(200)", "Tên TTCP", ""),
            F("org_unit_id", "UUID", "Đơn vị gắn", "Optional"),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
        T("FIN", "Thuế", "fin.tax_code", "Mã thuế", [
            F("code", "varchar(30)", "Mã thuế", ""),
            F("name", "varchar(100)", "Tên thuế", ""),
            F("rate", "numeric(9,4)", "Thuế suất %", ""),
            F("is_active", "boolean", "Đang dùng", ""),
        ]),
    ]

    # ========== AST ==========
    t += [
        T("AST", "Tài sản", "ast.asset_category", "Nhóm tài sản cố định", [
            F("code", "varchar(40)", "Mã nhóm", ""),
            F("name", "varchar(200)", "Tên nhóm", ""),
            F("depr_method", "varchar(30)", "PP khấu hao mặc định", "StraightLine…"),
            F("useful_life_months", "int", "Thời gian sử dụng (tháng)", ""),
        ]),
        T("AST", "Tài sản", "ast.asset", "Hồ sơ tài sản cố định", [
            F("code", "varchar(40)", "Mã TS", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên TS", ""),
            F("category_id", "UUID", "Nhóm TS", "FK"),
            F("status", "varchar(30)", "InUse/Idle/Disposed", ""),
            F("acquisition_date", "date", "Ngày ghi tăng", ""),
            F("acquisition_cost", "numeric(18,2)", "Nguyên giá", ""),
            F("accum_depr", "numeric(18,2)", "Hao mòn lũy kế", ""),
            F("net_book_value", "numeric(18,2)", "Giá trị còn lại", ""),
            F("custodian_employee_id", "UUID", "Người đang giữ", "Ref hrm.employee"),
            F("org_unit_id", "UUID", "Đơn vị quản lý", ""),
            F("location_text", "varchar(255)", "Vị trí đặt", ""),
        ]),
        T("AST", "Tài sản", "ast.asset_acquisition", "Chứng từ ghi tăng TS", [
            *doc_fields()[:3],
            F("asset_id", "UUID", "Tài sản", "FK"),
            F("source_module", "varchar(10)", "Nguồn mua/vốn hóa", "PUR/PJM…"),
            F("source_doc_id", "UUID", "ID chứng từ nguồn", ""),
            F("amount", "numeric(18,2)", "Giá trị ghi tăng", ""),
        ]),
        T("AST", "Khấu hao", "ast.depreciation_run", "Đợt chạy khấu hao", [
            F("period_code", "varchar(20)", "Kỳ KH", ""),
            F("run_date", "date", "Ngày chạy", ""),
            F("status", "varchar(30)", "Draft/Posted", ""),
            F("posted_journal_id", "UUID", "Bút toán FIN", "Ref mềm"),
        ]),
        T("AST", "Khấu hao", "ast.depreciation_line", "Dòng khấu hao theo tài sản", [
            F("run_id", "UUID", "Đợt KH", "FK"),
            F("asset_id", "UUID", "Tài sản", "FK"),
            F("depr_amount", "numeric(18,2)", "Số tiền KH kỳ", ""),
        ]),
        T("AST", "Biến động TS", "ast.asset_transfer", "Điều chuyển tài sản", [
            *doc_fields()[:3],
            F("asset_id", "UUID", "Tài sản", "FK"),
            F("from_org_unit_id", "UUID", "Đơn vị cũ", ""),
            F("to_org_unit_id", "UUID", "Đơn vị mới", ""),
            F("from_custodian_id", "UUID", "Người giữ cũ", ""),
            F("to_custodian_id", "UUID", "Người giữ mới", ""),
            F("effective_date", "date", "Ngày hiệu lực", ""),
        ]),
        T("AST", "Biến động TS", "ast.asset_disposal", "Thanh lý / ghi giảm TS", [
            *doc_fields()[:3],
            F("asset_id", "UUID", "Tài sản", "FK"),
            F("disposal_date", "date", "Ngày thanh lý", ""),
            F("disposal_amount", "numeric(18,2)", "Giá trị thanh lý", ""),
            F("reason", "text", "Lý do", ""),
        ]),
    ]

    # ========== FSM ==========
    t += [
        T("FSM", "Dịch vụ kỹ thuật", "fsm.service_contract", "Hợp đồng dịch vụ / bảo hành", [
            F("customer_id", "UUID", "KH", "Ref crm.customer"),
            F("contract_no", "varchar(50)", "Số HĐ", ""),
            F("start_date", "date", "Bắt đầu", ""),
            F("end_date", "date", "Kết thúc", ""),
            F("sla_policy_id", "UUID", "Chính sách SLA", "FK optional"),
            F("status", "varchar(30)", "Active/Expired", ""),
        ]),
        T("FSM", "Dịch vụ kỹ thuật", "fsm.sla_policy", "Chính sách SLA", [
            F("code", "varchar(40)", "Mã SLA", ""),
            F("name", "varchar(200)", "Tên SLA", ""),
            F("response_minutes", "int", "SLA phản hồi (phút)", ""),
            F("resolve_minutes", "int", "SLA xử lý (phút)", ""),
        ]),
        T("FSM", "Dịch vụ kỹ thuật", "fsm.ticket", "Ticket yêu cầu hỗ trợ / sự cố", [
            *doc_fields()[:3],
            F("customer_id", "UUID", "KH", "Ref crm.customer"),
            F("subject", "varchar(200)", "Tiêu đề", ""),
            F("priority", "varchar(20)", "Mức ưu tiên", ""),
            F("channel", "varchar(30)", "Kênh tạo", "PRT/Phone/Email"),
            F("sla_due_at", "timestamptz", "Hạn SLA", ""),
            F("assignee_user_id", "UUID", "Người phụ trách", ""),
        ]),
        T("FSM", "Dịch vụ kỹ thuật", "fsm.work_order", "Phiếu công việc kỹ thuật hiện trường", [
            *doc_fields(),
            F("ticket_id", "UUID", "Ticket nguồn", "FK optional"),
            F("customer_id", "UUID", "KH", "Ref crm.customer"),
            F("technician_user_id", "UUID", "Kỹ thuật viên", ""),
            F("scheduled_start", "timestamptz", "Lịch bắt đầu", ""),
            F("scheduled_end", "timestamptz", "Lịch kết thúc", ""),
            F("completed_at", "timestamptz", "Hoàn thành", ""),
        ], doc=False),
        T("FSM", "Dịch vụ kỹ thuật", "fsm.work_order_part", "Linh kiện dùng trên phiếu KT", [
            F("work_order_id", "UUID", "Phiếu KT", "FK"),
            F("item_id", "UUID", "Linh kiện", "Ref inv.item"),
            F("qty", "numeric(18,6)", "SL dùng", ""),
            F("uom", "varchar(20)", "ĐVT", ""),
            F("stock_document_id", "UUID", "CT xuất kho", "Optional"),
        ]),
        T("FSM", "Dịch vụ kỹ thuật", "fsm.work_order_time", "Giờ công kỹ thuật viên", [
            F("work_order_id", "UUID", "Phiếu KT", "FK"),
            F("technician_user_id", "UUID", "KTV", ""),
            F("minutes", "int", "Số phút", ""),
            F("work_date", "date", "Ngày thực hiện", ""),
            F("note", "varchar(500)", "Ghi chú", ""),
        ]),
        T("FSM", "Dịch vụ kỹ thuật", "fsm.appointment", "Lịch hẹn hiện trường", [
            F("work_order_id", "UUID", "Phiếu KT", "FK"),
            F("start_at", "timestamptz", "Bắt đầu hẹn", ""),
            F("end_at", "timestamptz", "Kết thúc hẹn", ""),
            F("address", "text", "Địa chỉ hẹn", ""),
            F("status", "varchar(30)", "Scheduled/Done/Cancelled", ""),
        ]),
    ]

    # ========== PJM ==========
    t += [
        T("PJM", "Dự án", "pjm.project", "Dự án", [
            F("code", "varchar(40)", "Mã dự án", "Unique theo tenant"),
            F("name", "varchar(200)", "Tên dự án", ""),
            F("customer_id", "UUID", "KH", "Ref crm.customer"),
            F("manager_user_id", "UUID", "PM", ""),
            F("start_date", "date", "Ngày bắt đầu", ""),
            F("end_date", "date", "Ngày kết thúc KH", ""),
            F("status", "varchar(30)", "Planned/Active/Closed", ""),
            F("budget_amount", "numeric(18,2)", "Ngân sách", ""),
            F("currency_code", "char(3)", "Tiền tệ", ""),
        ]),
        T("PJM", "Dự án", "pjm.project_member", "Thành viên dự án", [
            F("project_id", "UUID", "Dự án", "FK"),
            F("employee_id", "UUID", "Nhân sự", "Ref hrm.employee"),
            F("role_name", "varchar(100)", "Vai trò trong DA", ""),
            F("allocation_percent", "numeric(5,2)", "% phân bổ", ""),
            F("joined_at", "date", "Ngày tham gia", ""),
        ]),
        T("PJM", "Kế hoạch", "pjm.wbs_node", "Nút WBS / cấu trúc phân rã công việc", [
            F("project_id", "UUID", "Dự án", "FK"),
            F("parent_id", "UUID", "Nút cha", "Self FK"),
            F("code", "varchar(40)", "Mã WBS", ""),
            F("name", "varchar(200)", "Tên hạng mục", ""),
            F("sort_order", "int", "Thứ tự", ""),
        ]),
        T("PJM", "Kế hoạch", "pjm.task", "Công việc / task dự án", [
            F("project_id", "UUID", "Dự án", "FK"),
            F("wbs_id", "UUID", "WBS", "FK optional"),
            F("name", "varchar(200)", "Tên task", ""),
            F("assignee_user_id", "UUID", "Người thực hiện", ""),
            F("start_date", "date", "Bắt đầu", ""),
            F("due_date", "date", "Hạn", ""),
            F("progress_percent", "numeric(5,2)", "% hoàn thành", ""),
            F("status", "varchar(30)", "Todo/Doing/Done", ""),
        ]),
        T("PJM", "Kế hoạch", "pjm.milestone", "Mốc dự án", [
            F("project_id", "UUID", "Dự án", "FK"),
            F("name", "varchar(200)", "Tên mốc", ""),
            F("due_date", "date", "Ngày mốc", ""),
            F("status", "varchar(30)", "Pending/Achieved", ""),
        ]),
        T("PJM", "Chi phí & thay đổi", "pjm.project_budget_line", "Dòng ngân sách dự án", [
            F("project_id", "UUID", "Dự án", "FK"),
            F("category", "varchar(50)", "Hạng mục NS", ""),
            F("amount", "numeric(18,2)", "Số tiền NS", ""),
        ]),
        T("PJM", "Chi phí & thay đổi", "pjm.change_request", "Yêu cầu thay đổi phạm vi/CR", [
            *doc_fields()[:3],
            F("project_id", "UUID", "Dự án", "FK"),
            F("title", "varchar(200)", "Tiêu đề CR", ""),
            F("impact_summary", "text", "Tóm tắt ảnh hưởng", ""),
            F("requested_by", "UUID", "Người đề xuất", ""),
        ]),
    ]

    # ========== BI ==========
    t += [
        T("BI", "Metadata BI", "bi.dataset", "Đăng ký dataset phân tích", [
            F("code", "varchar(50)", "Mã dataset", ""),
            F("name", "varchar(200)", "Tên dataset", ""),
            F("source_module", "varchar(10)", "Module nguồn", ""),
            F("description", "text", "Mô tả", ""),
            F("is_active", "boolean", "Đang mở", "Phụ thuộc license module nguồn"),
        ]),
        T("BI", "Metadata BI", "bi.dataset_field", "Trường trong dataset", [
            F("dataset_id", "UUID", "Dataset", "FK"),
            F("field_name", "varchar(80)", "Tên trường", ""),
            F("data_type", "varchar(30)", "Kiểu logic", ""),
            F("label", "varchar(200)", "Nhãn hiển thị", ""),
        ]),
        T("BI", "Metadata BI", "bi.dashboard", "Dashboard tổng hợp", [
            F("code", "varchar(50)", "Mã dashboard", ""),
            F("name", "varchar(200)", "Tên dashboard", ""),
            F("owner_user_id", "UUID", "Chủ sở hữu", ""),
            F("is_published", "boolean", "Đã phát hành", ""),
        ]),
        T("BI", "Metadata BI", "bi.dashboard_widget", "Widget trên dashboard", [
            F("dashboard_id", "UUID", "Dashboard", "FK"),
            F("dataset_id", "UUID", "Dataset", "FK"),
            F("widget_type", "varchar(30)", "Loại", "Chart/Table/KPI"),
            F("config_json", "jsonb", "Cấu hình hiển thị", ""),
            F("sort_order", "int", "Thứ tự", ""),
        ]),
        T("BI", "Metadata BI", "bi.report_definition", "Định nghĩa báo cáo", [
            F("code", "varchar(50)", "Mã báo cáo", ""),
            F("name", "varchar(200)", "Tên báo cáo", ""),
            F("dataset_id", "UUID", "Dataset", "FK"),
            F("query_config_json", "jsonb", "Cấu hình truy vấn/bộ lọc", ""),
        ]),
        T("BI", "Metadata BI", "bi.report_schedule", "Lịch chạy/gửi báo cáo", [
            F("report_id", "UUID", "Báo cáo", "FK"),
            F("cron_expr", "varchar(80)", "Biểu thức lịch", ""),
            F("channel", "varchar(20)", "Kênh gửi", "Email"),
            F("recipients_json", "jsonb", "Danh sách nhận", ""),
            F("is_active", "boolean", "Đang bật", ""),
        ]),
        T("BI", "Metadata BI", "bi.bi_acl", "Phân quyền xem dataset/dashboard", [
            F("object_type", "varchar(30)", "Dataset/Dashboard/Report", ""),
            F("object_id", "UUID", "ID đối tượng", ""),
            F("principal_type", "varchar(20)", "User/Role", ""),
            F("principal_id", "UUID", "ID user/role", ""),
            F("access_level", "varchar(20)", "View/Edit", ""),
        ]),
    ]

    # ========== PRT ==========
    t += [
        T("PRT", "Cổng khách hàng", "prt.portal_account", "Tài khoản đăng nhập cổng KH/NCC", [
            F("login_email", "varchar(255)", "Email đăng nhập", "Unique theo tenant"),
            F("password_hash", "varchar(255)", "Hash mật khẩu", ""),
            F("account_type", "varchar(20)", "Customer/Vendor", ""),
            F("customer_id", "UUID", "KH liên kết", "Ref crm.customer"),
            F("vendor_id", "UUID", "NCC liên kết", "Ref pur.vendor"),
            F("user_id", "UUID", "User SYS (nếu map)", "Optional"),
            F("status", "varchar(20)", "Active/Disabled", ""),
            F("last_login_at", "timestamptz", "Đăng nhập cuối", ""),
        ]),
        T("PRT", "Cổng khách hàng", "prt.portal_role", "Vai trò trên cổng", [
            F("code", "varchar(40)", "Mã role cổng", ""),
            F("name", "varchar(100)", "Tên role", ""),
            F("permissions_json", "jsonb", "Quyền chức năng cổng", ""),
        ]),
        T("PRT", "Cổng khách hàng", "prt.portal_account_role", "Gán role cho tài khoản cổng", [
            F("portal_account_id", "UUID", "Tài khoản cổng", "FK"),
            F("portal_role_id", "UUID", "Role cổng", "FK"),
        ]),
        T("PRT", "Cổng khách hàng", "prt.self_service_ticket", "Ticket KH tự tạo trên cổng", [
            F("portal_account_id", "UUID", "TK cổng", "FK"),
            F("customer_id", "UUID", "KH", "Ref crm.customer"),
            F("subject", "varchar(200)", "Tiêu đề", ""),
            F("description", "text", "Mô tả chi tiết", ""),
            F("status", "varchar(30)", "New/InProgress/Closed", ""),
            F("fsm_ticket_id", "UUID", "Ticket FSM đồng bộ", "Ref mềm"),
        ]),
        T("PRT", "Cổng khách hàng", "prt.portal_notification", "Thông báo hiển thị trên cổng", [
            F("portal_account_id", "UUID", "TK cổng", "FK"),
            F("title", "varchar(200)", "Tiêu đề", ""),
            F("body", "text", "Nội dung", ""),
            F("is_read", "boolean", "Đã đọc", ""),
            F("read_at", "timestamptz", "Thời điểm đọc", ""),
            F("ref_type", "varchar(50)", "Loại đối tượng liên quan", "Order/Invoice/Ticket"),
            F("ref_id", "UUID", "ID đối tượng liên quan", ""),
        ]),
        T("PRT", "Cổng khách hàng", "prt.portal_document_share", "Chia sẻ chứng từ cho tài khoản cổng", [
            F("portal_account_id", "UUID", "TK cổng", "FK"),
            F("doc_module", "varchar(10)", "Module chứng từ", ""),
            F("doc_type", "varchar(50)", "Loại chứng từ", ""),
            F("doc_id", "UUID", "ID chứng từ", ""),
            F("can_download", "boolean", "Cho tải file", ""),
            F("shared_at", "timestamptz", "Thời điểm share", ""),
        ]),
    ]

    return t
