# -*- coding: utf-8 -*-
"""Phần META còn lại — merge vào META chính."""

REST = {
    "LMS": {
        "ten": "Đào tạo (Learning Management System)",
        "ma_tai_lieu": "SRS-LMS-v1.0",
        "phien_ban": "1.0",
        "lop": "Nhân sự & Đào tạo",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["HRM", "CRM", "FIN"],
        "tom_tat": (
            "Module LMS quản lý chương trình/khóa học, lớp offline, học online, ngân hàng câu hỏi, "
            "thi–chứng chỉ, lộ trình theo vị trí, khảo sát tuân thủ và báo cáo đào tạo. "
            "Phục vụ đào tạo nội bộ và/hoặc đào tạo có thu phí."
        ),
        "muc_tieu": [
            "Chuẩn hóa nội dung và tiến độ đào tạo theo vị trí.",
            "Hỗ trợ học offline + online trên cùng nền tảng.",
            "Đo lường hoàn thành, điểm thi, chứng chỉ.",
            "Đồng bộ chứng chỉ bắt buộc sang hồ sơ nhân sự (khi có HRM).",
        ],
        "in_scope": [
            "Catalog khóa học, nội dung, lớp, enrollment, online learning, exam, certificate, learning path, survey/acknowledge, LMS reports.",
        ],
        "out_scope": [
            "Tuyển dụng và tính lương (HRM).",
            "POS bán hàng vật lý tại quầy (POS).",
            "AI tutor nâng cao (phase sau).",
        ],
        "actors": [
            ("LMS Admin", "Cấu hình catalog, quyền giảng viên, publish khóa"),
            ("Instructor", "Giảng dạy, điểm danh, phản hồi bài"),
            ("Learner (NV nội bộ)", "Học bắt buộc / đăng ký nội bộ"),
            ("Learner (Khách)", "Học viên bên ngoài mua khóa"),
            ("HR Training", "Gán lộ trình, theo dõi tuân thủ"),
            ("Hệ thống", "Mở khóa bài, chấm quiz, nhắc học, cấp chứng chỉ"),
        ],
        "terms": [
            ("Enrollment", "Ghi danh học viên vào khóa/lớp"),
            ("Learning path", "Lộ trình khóa bắt buộc/tùy chọn theo vị trí"),
            ("Certificate", "Chứng chỉ hoàn thành điện tử"),
            ("Acknowledge", "Xác nhận đã đọc quy định/SOP"),
        ],
        "workflows": [
            {
                "ma": "WF-LMS-01",
                "ten": "Xây dựng và xuất bản khóa học",
                "muc_tieu": "Có khóa học sẵn sàng để ghi danh",
                "buoc": [
                    "Tạo chương trình/khóa; cấu trúc chương–bài",
                    "Upload video/tài liệu; tạo ngân hàng câu hỏi",
                    "Cấu hình điều kiện hoàn thành & chứng chỉ",
                    "Review nội dung; xuất bản",
                    "Gán vào lộ trình vị trí (nếu có)",
                ],
            },
            {
                "ma": "WF-LMS-02",
                "ten": "Đào tạo bắt buộc cho nhân sự mới",
                "muc_tieu": "NV hoàn thành khóa trước hạn",
                "buoc": [
                    "HRM/HR Training kích hoạt gán lộ trình khi nhận việc",
                    "Hệ thống tạo enrollment và gửi thông báo",
                    "Học viên học, làm quiz/thi",
                    "Đạt điều kiện → cấp chứng chỉ",
                    "Đồng bộ chứng chỉ sang hồ sơ HRM; cảnh báo quá hạn nếu chậm",
                ],
            },
            {
                "ma": "WF-LMS-03",
                "ten": "Lớp offline có thu phí / nội bộ",
                "muc_tieu": "Mở lớp – ghi danh – điểm danh – tổng kết",
                "buoc": [
                    "Mở lớp, gán giảng viên/lịch/địa điểm",
                    "Ghi danh học viên; ghi nhận học phí nếu có",
                    "Điểm danh buổi; đánh giá thực hành",
                    "Đóng lớp; cấp chứng chỉ; ghi nhận doanh thu (FIN/CRM nếu có)",
                ],
            },
        ],
        "entities": [
            ("Program / Course / Lesson", "Cấu trúc nội dung"),
            ("QuestionBank / Exam", "Thi cử"),
            ("ClassSession / Enrollment", "Lớp & ghi danh"),
            ("LearningProgress", "Tiến độ học"),
            ("Certificate", "Chứng chỉ"),
            ("LearningPath", "Lộ trình"),
            ("Survey / Acknowledgement", "Khảo sát & xác nhận"),
        ],
        "business_rules": [
            "BR-LMS-01: Chỉ khóa đã publish mới cho ghi danh mới.",
            "BR-LMS-02: Chứng chỉ chỉ cấp khi đủ điều kiện hoàn thành cấu hình.",
            "BR-LMS-03: Khóa bắt buộc quá hạn phải cảnh báo quản lý/HR.",
            "BR-LMS-04: Học viên khách và nội bộ có thể tách chính sách giá/quyền.",
        ],
        "nfr": [
            ("Streaming", "Xem video ổn định trên web/mobile; hỗ trợ resume"),
            ("Bảo mật nội dung", "Giới hạn thiết bị/phiên theo cấu hình gói"),
            ("Hiệu năng", "Dashboard tiến độ 10.000 enrollment truy vấn được phân trang"),
        ],
        "integrations": [
            ("SYS", "User, thông báo, file, license"),
            ("HRM", "Gán lộ trình theo vị trí; đồng bộ chứng chỉ"),
            ("CRM/FIN", "Doanh thu khóa học / upsell sau đào tạo"),
            ("Payment", "Cổng thanh toán mua khóa online"),
        ],
        "permissions": [
            "lms.course.manage", "lms.class.manage", "lms.grade.manage",
            "lms.learn.access", "lms.certificate.issue", "lms.report.view",
        ],
        "kpis": [
            "% hoàn thành đào tạo bắt buộc đúng hạn",
            "Tỷ lệ đạt thi lần 1",
            "Số giờ học / học viên",
            "Doanh thu khóa (nếu bán ngoài)",
        ],
        "assumptions": [
            "Nội dung video do khách tự cung cấp hoặc mua riêng; LMS là nền tảng quản trị học tập.",
        ],
        "open_questions": [
            "Có cần SCORM/xAPI phase 1 không?",
            "Portal học viên tách biệt PRT hay dùng chung UI LMS?",
        ],
        "default_actors_by_group": {
            "01": "LMS Admin", "02": "LMS Admin / Instructor", "03": "LMS Admin / Instructor",
            "04": "Instructor / HR Training", "05": "Learner", "06": "Learner / Hệ thống",
            "07": "Instructor / LMS Admin", "08": "HR Training / Learner",
            "09": "HR Training", "10": "LMS Admin / HR Training", "11": "LMS Admin",
        },
    },
    "CRM": {
        "ten": "CRM & Bán hàng",
        "ma_tai_lieu": "SRS-CRM-v1.0",
        "phien_ban": "1.0",
        "lop": "Bán hàng & Khách hàng",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["INV", "LOG", "FIN", "WF", "PRT"],
        "tom_tat": (
            "Module CRM quản lý khách hàng, marketing, omnichannel, lead–cơ hội–báo giá–đơn hàng, "
            "bán hàng hiện trường, sales admin, CSKH, hoa hồng và báo cáo doanh số. "
            "Thiết kế generic cho B2B/B2C/phân phối."
        ),
        "muc_tieu": [
            "Một hồ sơ khách 360° dùng chung toàn công ty.",
            "Chuẩn hóa phễu Lead → Order.",
            "Kiểm soát giá, chiết khấu, hạn mức công nợ.",
            "Đo hiệu quả marketing và năng suất sales.",
        ],
        "in_scope": [
            "Customer master, campaign, promo, omnichannel inbox, lead, opportunity, quote, order, route sales, sales admin, contract/policy, CS, commission, CRM reports.",
        ],
        "out_scope": [
            "Thanh toán quầy POS (POS).",
            "Xuất kho/giao hàng chi tiết (INV/LOG).",
            "Hạch toán kế toán đầy đủ (FIN).",
        ],
        "actors": [
            ("Sales Rep", "Chăm lead/KH, báo giá, đơn"),
            ("Sales Manager", "Pipeline, duyệt chiết khấu, KPI đội"),
            ("Sales Admin", "Xử lý hàng đợi đơn, đối soát chứng từ"),
            ("Marketer", "Campaign, nguồn lead, KM"),
            ("Contact Center Agent", "Inbox omnichannel"),
            ("CSKH", "Ticket sau bán, loyalty"),
            ("Khách hàng (gián tiếp)", "Qua PRT/kênh chat"),
        ],
        "terms": [
            ("Lead", "Đầu mối tiềm năng chưa thành KH/cơ hội"),
            ("Opportunity", "Cơ hội bán có giá trị và giai đoạn"),
            ("Quote", "Báo giá"),
            ("Reserve stock", "Giữ tồn khi đơn được duyệt"),
            ("Credit limit", "Hạn mức công nợ"),
        ],
        "workflows": [
            {
                "ma": "WF-CRM-01",
                "ten": "Lead-to-Order",
                "muc_tieu": "Từ lead đến đơn hàng đã xác nhận",
                "buoc": [
                    "Tiếp nhận lead (thủ công/tự động)",
                    "Phân bổ sales; scoring; follow-up",
                    "Qualify thành cơ hội",
                    "Lập báo giá; duyệt chiết khấu nếu vượt khung",
                    "Khách chấp nhận → tạo đơn",
                    "Kiểm tra tín dụng/tồn; reserve; chuyển fulfillment",
                ],
            },
            {
                "ma": "WF-CRM-02",
                "ten": "Campaign → đo ROI",
                "muc_tieu": "Gắn chi phí marketing với lead/doanh thu",
                "buoc": [
                    "Tạo campaign và ngân sách",
                    "Thu lead theo nguồn/attribution",
                    "Chăm sóc và chuyển đổi",
                    "Ghi nhận doanh thu đơn gắn campaign",
                    "Báo cáo CPL/CAC/ROI",
                ],
            },
            {
                "ma": "WF-CRM-03",
                "ten": "Visit bán hàng hiện trường",
                "muc_tieu": "Thực hiện kế hoạch thăm và chốt nhu cầu/đơn",
                "buoc": [
                    "Lập kế hoạch visit theo tệp KH",
                    "Check-in GPS; ghi nhận kết quả",
                    "Tạo hoạt động/cơ hội/đơn tại điểm",
                    "Đồng bộ về pipeline và dashboard",
                ],
            },
        ],
        "entities": [
            ("Customer / Contact", "Khách & người liên hệ"),
            ("Campaign / Promo / Voucher", "Marketing & KM"),
            ("Conversation", "Hội thoại omnichannel"),
            ("Lead / Opportunity", "Phễu bán"),
            ("Quote / SalesOrder", "Báo giá & đơn"),
            ("VisitPlan / VisitLog", "Bán hiện trường"),
            ("SupportCase", "CSKH"),
            ("CommissionRule / CommissionSheet", "Hoa hồng"),
        ],
        "business_rules": [
            "BR-CRM-01: Không tạo trùng KH theo rule SĐT/MST (cấu hình).",
            "BR-CRM-02: Chiết khấu vượt khung bắt buộc qua workflow duyệt.",
            "BR-CRM-03: Đơn vượt hạn mức công nợ bị block hoặc cần duyệt vượt mức.",
            "BR-CRM-04: Mỗi lead/cơ hội có owner; bàn giao có lịch sử.",
            "BR-CRM-05: Đơn hủy sau reserve phải giải phóng tồn.",
        ],
        "nfr": [
            ("Realtime inbox", "Hội thoại đồng bộ gần realtime theo kênh tích hợp"),
            ("Search", "Tìm KH/đơn < 2s với bộ lọc phổ biến"),
            ("Mobile", "Sales field dùng được trên mobile"),
        ],
        "integrations": [
            ("INV", "ATP, reserve, giá vốn tham chiếu"),
            ("LOG", "Lệnh giao từ đơn"),
            ("FIN", "Công nợ, thanh toán, doanh thu"),
            ("WF", "Duyệt báo giá/chiết khấu/vượt hạn mức"),
            ("FSM", "Escalate ticket kỹ thuật"),
            ("PRT", "KH tự phục vụ đơn/công nợ/ticket"),
            ("Meta/Zalo/Web", "Lead & messaging"),
        ],
        "permissions": [
            "crm.customer.manage", "crm.lead.manage", "crm.opportunity.manage",
            "crm.quote.manage", "crm.order.manage", "crm.discount.approve",
            "crm.campaign.manage", "crm.inbox.agent", "crm.report.view",
        ],
        "kpis": [
            "Tỷ lệ chuyển đổi lead→opportunity→order",
            "Doanh số / margin theo NV–vùng–SP",
            "Cycle time báo giá → đơn",
            "CPL, CAC, ROI campaign",
        ],
        "assumptions": [
            "Bảng giá và chính sách công nợ cấu hình theo tenant.",
        ],
        "open_questions": [
            "Phase 1 có tích hợp sàn TMĐT sâu hay chỉ khung intake đơn?",
            "Omnichannel Zalo cá nhân có nằm trong phạm vi pháp lý triển khai không?",
        ],
        "default_actors_by_group": {
            "01": "Sales Admin / Sales Rep", "02": "Marketer", "03": "Marketer",
            "04": "Marketer / Sales Admin", "05": "Contact Center Agent",
            "06": "Sales Rep", "07": "Sales Rep / Sales Manager",
            "08": "Sales Rep / Sales Manager", "09": "Sales Rep / Sales Admin",
            "10": "Sales Rep", "11": "Sales Admin", "12": "Sales Manager / Sales Admin",
            "13": "CSKH", "14": "Sales Manager", "15": "Sales Manager",
        },
    },
    "POS": {
        "ten": "POS bán lẻ",
        "ma_tai_lieu": "SRS-POS-v1.0",
        "phien_ban": "1.0",
        "lop": "Bán hàng & Khách hàng",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["INV", "FIN", "CRM"],
        "tom_tat": (
            "Module POS phục vụ bán tại điểm bán: danh mục hàng/món, giá, khuyến mại, "
            "thanh toán, ca thu ngân, đồng bộ tồn và doanh thu, báo cáo cửa hàng/chuỗi."
        ),
        "muc_tieu": [
            "Thanh toán nhanh, kiểm soát quỹ ca.",
            "Đồng bộ tồn/định mức với kho.",
            "Chuẩn hóa menu/giá/KM toàn chuỗi.",
            "Cung cấp số liệu doanh thu realtime cho quản lý.",
        ],
        "in_scope": [
            "Store/terminal config, sellable catalog, pricing, promo at POS, checkout, shift/cash, loyalty light, stock sync, POS reports, chain push config.",
        ],
        "out_scope": [
            "CRM pipeline đầy đủ.",
            "Kế toán sổ cái (FIN).",
            "WMS chi tiết vị trí kho tổng (INV).",
        ],
        "actors": [
            ("Cashier", "Thu ngân"),
            ("Store Manager", "Duyệt giảm giá/hủy, đóng ca, báo cáo CH"),
            ("Chain Admin", "Đẩy menu/giá/KM xuống điểm bán"),
            ("Inventory Clerk (CH)", "Nhận hàng/kiểm kê nhanh tại CH"),
        ],
        "terms": [
            ("Terminal", "Máy POS tại quầy"),
            ("Shift", "Ca thu ngân"),
            ("BOM/Recipe", "Định mức nguyên liệu gắn SP/món"),
            ("Void", "Hủy món/bill có kiểm soát"),
        ],
        "workflows": [
            {
                "ma": "WF-POS-01",
                "ten": "Bán hàng trong ca",
                "muc_tieu": "Hoàn tất giao dịch và ghi nhận doanh thu ca",
                "buoc": [
                    "Mở ca, nhập tiền đầu ca",
                    "Tạo đơn, thêm SP/món, áp KM/voucher",
                    "Thanh toán một/nhiều hình thức; in hóa đơn",
                    "Trừ tồn theo rule; cộng doanh thu ca",
                    "Đóng ca, đếm quỹ, đối soát lệch",
                ],
            },
            {
                "ma": "WF-POS-02",
                "ten": "Đẩy cấu hình chuỗi",
                "muc_tieu": "Điểm bán nhận menu/giá/KM mới",
                "buoc": [
                    "Chain Admin cập nhật master catalog/giá/KM",
                    "Chọn điểm bán đích và phát hành",
                    "Terminal đồng bộ phiên bản cấu hình",
                    "Báo cáo điểm chưa đồng bộ",
                ],
            },
        ],
        "entities": [
            ("Store / Terminal", "Điểm bán & máy"),
            ("SellableItem / Modifier / Recipe", "Hàng bán & định mức"),
            ("PriceList", "Bảng giá"),
            ("PosOrder / PosPayment", "Giao dịch"),
            ("CashShift", "Ca quỹ"),
            ("StoreRequisition", "Đề nghị hàng"),
        ],
        "business_rules": [
            "BR-POS-01: Hủy món/bill sau thanh toán hoặc sau gửi chế biến cần quyền riêng.",
            "BR-POS-02: Không đóng ca khi còn đơn mở (trừ force có quyền).",
            "BR-POS-03: Lệch quỹ phải ghi nhận lý do.",
            "BR-POS-04: Terminal chỉ bán SP đang active và còn cho phép tại cửa hàng.",
        ],
        "nfr": [
            ("Tốc độ", "Thêm món và thanh toán cảm nhận < 1s trên LAN cửa hàng"),
            ("Sẵn sàng", "Hỗ trợ hàng đợi offline hạn chế (tùy gói)"),
            ("In ấn", "Tương thích máy in nhiệt phổ biến"),
        ],
        "integrations": [
            ("INV", "Trừ tồn, nhận hàng CH, kiểm kê nhanh"),
            ("FIN", "Post doanh thu/ca/quỹ"),
            ("CRM", "KM, loyalty, gắn KH"),
            ("Payment QR/Card", "Cổng thanh toán"),
        ],
        "permissions": [
            "pos.sale.create", "pos.discount.apply", "pos.void.approve",
            "pos.shift.open_close", "pos.config.manage", "pos.report.view",
        ],
        "kpis": [
            "Doanh thu theo giờ/ca/CH",
            "Tỷ lệ void/discount",
            "Thời gian phục vụ trung bình",
            "Food/material cost variance (khi có recipe+INV)",
        ],
        "assumptions": [
            "Mỗi điểm bán thuộc một chi nhánh/org trong SYS.",
        ],
        "open_questions": [
            "Phase 1 có KDS bếp đầy đủ hay chỉ in lệnh?",
            "Có hỗ trợ đặt bàn/đặt trước không?",
        ],
        "default_actors_by_group": {
            "01": "Chain Admin / Store Manager", "02": "Chain Admin",
            "03": "Chain Admin", "04": "Cashier / Store Manager",
            "05": "Cashier", "06": "Cashier / Store Manager",
            "07": "Cashier / Store Manager", "08": "Store Manager / Inventory Clerk (CH)",
            "09": "Store Manager", "10": "Chain Admin",
        },
    },
    "PUR": {
        "ten": "Mua hàng (Procurement)",
        "ma_tai_lieu": "SRS-PUR-v1.0",
        "phien_ban": "1.0",
        "lop": "Chuỗi cung ứng",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["INV", "FIN", "WF"],
        "tom_tat": "Quản lý NCC, nhu cầu mua (PR), RFQ, PO, nhận hàng, hóa đơn mua và báo cáo chi tiêu.",
        "muc_tieu": [
            "Chuẩn hóa quy trình PR→PO→GRN→Invoice.",
            "Kiểm soát duyệt theo hạn mức.",
            "Hỗ trợ đối soát 3 chiều với kho và kế toán.",
        ],
        "in_scope": ["Vendor, price, PR, RFQ, PO, receiving, AP invoice match, purchase reports."],
        "out_scope": ["Quản lý tồn chi tiết (INV).", "Thanh toán sổ quỹ đầy đủ (FIN)."],
        "actors": [
            ("Buyer", "Tạo PR/PO, RFQ"),
            ("Requester", "Yêu cầu mua từ đơn vị"),
            ("Purchasing Manager", "Duyệt mua, chọn NCC"),
            ("Warehouse Receiver", "Nhận hàng theo PO"),
            ("AP Clerk", "Hóa đơn NCC / 3-way match"),
        ],
        "terms": [
            ("PR", "Purchase Requisition — yêu cầu mua"),
            ("RFQ", "Request for Quotation"),
            ("PO", "Purchase Order"),
            ("GRN", "Goods Receipt Note"),
            ("3-way match", "Đối chiếu PO–GRN–Invoice"),
        ],
        "workflows": [
            {
                "ma": "WF-PUR-01",
                "ten": "Mua hàng chuẩn PR→PO→GRN→Invoice",
                "muc_tieu": "Mua đúng nhu cầu, đúng giá, đủ chứng từ",
                "buoc": [
                    "Tạo PR và duyệt theo hạn mức",
                    "RFQ hoặc chọn NCC/bảng giá",
                    "Tạo và duyệt PO; gửi NCC",
                    "Nhận hàng (GRN) đẩy nhập INV",
                    "Nhập hóa đơn; 3-way match; đẩy AP sang FIN",
                ],
            }
        ],
        "entities": [
            ("Vendor", "NCC"), ("VendorItemPrice", "Giá mua"),
            ("PurchaseRequisition", "PR"), ("RFQ", "Yêu cầu báo giá"),
            ("PurchaseOrder", "PO"), ("GoodsReceipt", "GRN"),
            ("VendorInvoice", "Hóa đơn mua"),
        ],
        "business_rules": [
            "BR-PUR-01: PO vượt hạn mức phải qua workflow.",
            "BR-PUR-02: Nhận vượt PO chỉ cho phép trong dung sai cấu hình.",
            "BR-PUR-03: Không đóng PO khi còn số lượng mở vượt ngưỡng policy.",
            "BR-PUR-04: Hóa đơn lệch match phải xử lý exception trước khi post AP.",
        ],
        "nfr": [("Truy vết", "Mọi PO truy vết được PR/RFQ/người duyệt"), ("Hiệu năng", "Danh sách open PO phân trang nhanh")],
        "integrations": [
            ("INV", "Nhập kho từ GRN, cảnh báo tồn min→PR"),
            ("FIN", "AP, tạm ứng NCC"),
            ("WF", "Duyệt PR/PO/thanh toán"),
            ("PRT", "Portal NCC xác nhận PO (tùy gói)"),
        ],
        "permissions": [
            "pur.vendor.manage", "pur.pr.manage", "pur.po.manage",
            "pur.po.approve", "pur.grn.manage", "pur.invoice.match", "pur.report.view",
        ],
        "kpis": ["Spend theo NCC/SP", "OTIF NCC", "Open PR/PO aging", "Savings từ RFQ"],
        "assumptions": ["Đơn vị tính và SKU dùng chung master với INV."],
        "open_questions": ["Có hỗ trợ hợp đồng khung call-off ngay phase 1?"],
        "default_actors_by_group": {
            "01": "Buyer", "02": "Buyer", "03": "Requester / Buyer",
            "04": "Buyer / Purchasing Manager", "05": "Buyer / Purchasing Manager",
            "06": "Warehouse Receiver", "07": "AP Clerk", "08": "Purchasing Manager",
            "09": "Purchasing Manager",
        },
    },
    "INV": {
        "ten": "Kho & Tồn kho",
        "ma_tai_lieu": "SRS-INV-v1.0",
        "phien_ban": "1.0",
        "lop": "Chuỗi cung ứng",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["PUR", "LOG", "FIN", "POS", "MFG"],
        "tom_tat": (
            "Module INV quản lý master hàng hóa, đa kho/vị trí, nhập–xuất–chuyển, "
            "tồn khả dụng/giữ hàng, lô–HSD–serial, kiểm kê, giá trị kho và báo cáo xuất nhập tồn."
        ),
        "muc_tieu": [
            "Tồn realtime chính xác (on-hand / reserved / available).",
            "Truy vết lô/serial/HSD.",
            "Hỗ trợ nhiều mục đích xuất (bán, SX, kỹ thuật, dự án).",
            "Đồng bộ giá trị kho với FIN.",
        ],
        "in_scope": ["Item master, warehouse/bin, stock moves, reservation, lot/serial/expiry, stocktake, valuation, INV reports."],
        "out_scope": ["Mua hàng (PUR).", "Điều phối giao hàng (LOG).", "BOM/lệnh SX (MFG)."],
        "actors": [
            ("Inventory Admin", "Master hàng & cấu hình kho"),
            ("Storekeeper", "Nhập/xuất/chuyển/kiểm kê"),
            ("Planner", "Xem tồn khả dụng, đề nghị cấp hàng"),
            ("Auditor", "Đối chiếu kiểm kê"),
        ],
        "terms": [
            ("On-hand", "Tồn thực tế trong kho"),
            ("Reserved", "Tồn đang giữ cho đơn/lệnh"),
            ("Available", "On-hand − Reserved (− policy khác)"),
            ("FEFO", "First Expiry First Out"),
            ("Stocktake", "Kiểm kê"),
        ],
        "workflows": [
            {
                "ma": "WF-INV-01",
                "ten": "Nhập – giữ – xuất bán",
                "muc_tieu": "Đảm bảo ATP cho đơn hàng",
                "buoc": [
                    "Nhập kho từ GRN/SX/điều chỉnh",
                    "Đơn bán duyệt → reserve",
                    "Xuất kho theo lệnh giao/bán; trừ reserve + on-hand",
                    "Cập nhật thẻ kho và giá trị",
                ],
            },
            {
                "ma": "WF-INV-02",
                "ten": "Kiểm kê định kỳ",
                "muc_tieu": "Chốt lệch tồn có duyệt",
                "buoc": [
                    "Tạo đợt kiểm kê; tùy chọn đóng băng giao dịch",
                    "Nhập số đếm; đối chiếu lệch",
                    "Duyệt điều chỉnh; post phiếu điều chỉnh",
                    "Báo cáo kết quả",
                ],
            },
        ],
        "entities": [
            ("Item / UomConversion", "Hàng hóa"),
            ("Warehouse / Bin", "Kho & vị trí"),
            ("StockBalance / Lot / Serial", "Tồn & truy vết"),
            ("StockDocument (In/Out/Transfer/Adjust)", "Chứng từ kho"),
            ("Reservation", "Giữ hàng"),
            ("StocktakeSession", "Kiểm kê"),
        ],
        "business_rules": [
            "BR-INV-01: Không cho xuất vượt available (trừ khi policy tồn âm bật).",
            "BR-INV-02: Hàng quản lý HSD mặc định xuất FEFO.",
            "BR-INV-03: Hàng quá HSD bị chặn xuất.",
            "BR-INV-04: Mọi thay đổi tồn phải qua chứng từ; không sửa số dư tay.",
            "BR-INV-05: Reserve phải được release khi hủy nguồn giữ hàng.",
        ],
        "nfr": [
            ("Realtime", "Số tồn hiển thị gần realtime sau post chứng từ"),
            ("Khối lượng", "Hỗ trợ hàng trăm kho và hàng chục nghìn SKU"),
        ],
        "integrations": [
            ("PUR", "GRN nhập"), ("LOG", "Xuất giao"), ("POS", "Trừ recipe/SP"),
            ("MFG", "Xuất NVL – nhập TP"), ("FSM", "Xuất linh kiện"),
            ("PJM", "Xuất vật tư dự án"), ("FIN", "Inventory posting"),
        ],
        "permissions": [
            "inv.item.manage", "inv.warehouse.manage", "inv.doc.post",
            "inv.reservation.manage", "inv.stocktake.manage", "inv.report.view",
        ],
        "kpis": ["Độ chính xác tồn", "Hàng cận date", "Slow-moving", "Giá trị tồn theo kho"],
        "assumptions": ["Phương pháp giá vốn cấu hình theo tenant/item (TBXQ/FIFO…)."],
        "open_questions": ["Phase 1 có quản lý bin/location chi tiết hay chỉ mức kho?"],
        "default_actors_by_group": {
            "01": "Inventory Admin", "02": "Inventory Admin", "03": "Storekeeper",
            "04": "Storekeeper", "05": "Storekeeper", "06": "Storekeeper / Planner",
            "07": "Storekeeper", "08": "Storekeeper / Auditor", "09": "Planner",
            "10": "Inventory Admin", "11": "Inventory Admin / Storekeeper",
        },
    },
    "LOG": {
        "ten": "Giao vận (Logistics)",
        "ma_tai_lieu": "SRS-LOG-v1.0",
        "phien_ban": "1.0",
        "lop": "Chuỗi cung ứng",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS", "INV"],
        "khuyen_nghi_kem": ["CRM", "FIN"],
        "tom_tat": "Quản lý lệnh giao, điều phối tài xế/3PL, theo dõi vận đơn, COD, hoàn hàng và KPI giao hàng.",
        "muc_tieu": [
            "Biến đơn hàng thành chuyến giao có trạng thái rõ ràng.",
            "Đối soát COD 3 chiều.",
            "Đo on-time delivery và tỷ lệ thất bại.",
        ],
        "in_scope": ["Carrier/fleet, delivery order, dispatch, tracking/POD, COD, returns, LOG reports."],
        "out_scope": ["Tối ưu lộ trình AI nâng cao (phase sau).", "WMS picking chi tiết sâu (INV)."],
        "actors": [
            ("Logistics Coordinator", "Tạo DO, phân công"),
            ("Driver / 3PL", "Cập nhật trạng thái, thu COD"),
            ("Cashier/Accountant", "Đối soát COD"),
            ("Sales Admin", "Theo dõi đơn giao"),
        ],
        "terms": [
            ("DO", "Delivery Order — lệnh giao"),
            ("POD", "Proof of Delivery"),
            ("COD", "Cash on Delivery"),
            ("ASN", "Advanced Shipping Notice (NCC/3PL)"),
        ],
        "workflows": [
            {
                "ma": "WF-LOG-01",
                "ten": "Giao hàng có COD",
                "muc_tieu": "Giao thành công và nộp đủ tiền COD",
                "buoc": [
                    "Tạo DO từ đơn; pick/xuất kho",
                    "Phân công tài xế/3PL",
                    "Cập nhật trạng thái; POD",
                    "Thu COD; bàn giao tiền",
                    "Đối soát 3 chiều Sales–Ship–Kế toán",
                ],
            }
        ],
        "entities": [
            ("Carrier / Driver / Vehicle", "Năng lực giao"),
            ("DeliveryOrder / DeliveryTrip", "Lệnh & chuyến"),
            ("ShipmentEvent / POD", "Tracking"),
            ("CodCollection", "COD"),
            ("DeliveryReturn", "Hoàn"),
        ],
        "business_rules": [
            "BR-LOG-01: Chỉ tạo DO khi đơn đủ điều kiện fulfillment và có tồn/reserve.",
            "BR-LOG-02: Giao thất bại phải có lý do mã hóa.",
            "BR-LOG-03: COD chưa nộp quá hạn phải cảnh báo.",
            "BR-LOG-04: Hoàn hàng phải tạo chứng từ nhập lại INV.",
        ],
        "nfr": [("Mobile driver", "Cập nhật trạng thái trên mobile"), ("SLA tracking", "Trạng thái gần realtime")],
        "integrations": [
            ("CRM", "Nguồn đơn"), ("INV", "Xuất/nhập hoàn"),
            ("FIN", "COD & cước vận chuyển"), ("3PL API", "Tracking (khung)"),
        ],
        "permissions": [
            "log.do.manage", "log.dispatch.assign", "log.status.update",
            "log.cod.reconcile", "log.report.view",
        ],
        "kpis": ["On-time delivery", "Fail/return rate", "COD aging", "Cost per delivery"],
        "assumptions": ["Có thể giao nội bộ hoặc 3PL song song."],
        "open_questions": ["Phase 1 có map tracking GPS tài xế không?"],
        "default_actors_by_group": {
            "01": "Logistics Coordinator", "02": "Logistics Coordinator",
            "03": "Logistics Coordinator / Driver", "04": "Driver / Accountant",
            "05": "Storekeeper / Logistics Coordinator", "06": "Logistics Coordinator",
            "07": "Logistics Coordinator",
        },
    },
    "MFG": {
        "ten": "Sản xuất (Manufacturing)",
        "ma_tai_lieu": "SRS-MFG-v1.0",
        "phien_ban": "1.0",
        "lop": "Sản xuất & Dịch vụ",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS", "INV"],
        "khuyen_nghi_kem": ["PUR", "FIN", "HRM"],
        "tom_tat": "Quản lý BOM, kế hoạch/lệnh sản xuất, xuất NVL–nhập TP, giá thành sơ bộ, QC cơ bản và báo cáo sản lượng.",
        "muc_tieu": [
            "Kiểm soát lệnh SX và tiêu hao NVL.",
            "Tính giá thành đơn vị cơ bản.",
            "Giảm sai lệch lý thuyết vs thực tế.",
        ],
        "in_scope": ["BOM, planning/MRP-light, work order, issue/receipt, costing, QC basic, batch, MFG reports."],
        "out_scope": ["MES realtime máy móc nâng cao.", "APS tối ưu lịch phức tạp."],
        "actors": [
            ("Production Planner", "Kế hoạch & lệnh"),
            ("Shop Supervisor", "Điều phối xưởng"),
            ("Warehouse (SX)", "Xuất NVL/nhập TP"),
            ("QC Staff", "Kiểm chất lượng"),
            ("Cost Accountant", "Giá thành"),
        ],
        "terms": [
            ("BOM", "Bill of Materials"),
            ("WO", "Work Order — lệnh SX"),
            ("WIP", "Work in Progress"),
            ("Yield", "Tỷ lệ đạt"),
        ],
        "workflows": [
            {
                "ma": "WF-MFG-01",
                "ten": "Lệnh sản xuất chuẩn",
                "muc_tieu": "Hoàn thành WO và nhập TP",
                "buoc": [
                    "Tạo WO từ kế hoạch/đơn",
                    "Duyệt/phát hành; xuất NVL",
                    "Ghi nhận tiến độ/phế phẩm",
                    "QC (nếu bật); nhập TP",
                    "Đóng lệnh; tính giá thành; post FIN/INV",
                ],
            }
        ],
        "entities": [
            ("Bom / BomVersion", "Định mức"),
            ("WorkCenter / Operation", "Năng lực & công đoạn"),
            ("WorkOrder", "Lệnh SX"),
            ("MaterialIssue / FgReceipt", "Xuất–nhập"),
            ("QcResult", "QC"),
            ("ProductionCost", "Giá thành"),
        ],
        "business_rules": [
            "BR-MFG-01: WO chỉ xuất NVL khi đã release.",
            "BR-MFG-02: Không nhập TP vượt dung sai WO nếu policy chặn.",
            "BR-MFG-03: Đóng WO khi đã xử lý đủ NVL/TP/phế theo rule.",
            "BR-MFG-04: BOM dùng để tính nhu cầu phải ở phiên bản hiệu lực.",
        ],
        "nfr": [("Batch jobs", "MRP-light chạy theo lịch"), ("Traceability", "Truy vết NVL→TP theo lô khi bật")],
        "integrations": [
            ("INV", "Xuất NVL/nhập TP"), ("PUR", "PR thiếu NVL"),
            ("FIN", "Giá thành/bút toán"), ("CRM", "Nhu cầu theo đơn"),
        ],
        "permissions": [
            "mfg.bom.manage", "mfg.wo.manage", "mfg.wo.release",
            "mfg.issue.post", "mfg.qc.manage", "mfg.cost.run", "mfg.report.view",
        ],
        "kpis": ["WO on-time", "Material variance", "Yield/QC pass rate", "Output by center"],
        "assumptions": ["Áp dụng cho sản xuất rời rạc hoặc theo mẻ cấu hình được."],
        "open_questions": ["Có cần routing nhiều công đoạn ngay phase 1?"],
        "default_actors_by_group": {
            "01": "Production Planner", "02": "Production Planner",
            "03": "Production Planner", "04": "Shop Supervisor / Warehouse (SX)",
            "05": "Cost Accountant", "06": "QC Staff", "07": "Shop Supervisor",
            "08": "Production Planner",
        },
    },
    "FSM": {
        "ten": "Dịch vụ kỹ thuật hiện trường (Field Service)",
        "ma_tai_lieu": "SRS-FSM-v1.0",
        "phien_ban": "1.0",
        "lop": "Sản xuất & Dịch vụ",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["CRM", "INV", "FIN", "PRT"],
        "tom_tat": "Quản lý install base, ticket bảo hành/sửa chữa/bảo trì, phân công KTV, linh kiện, SLA, nghiệm thu và báo cáo dịch vụ.",
        "muc_tieu": [
            "Chuẩn hóa tiếp nhận và xử lý ticket theo SLA.",
            "Kiểm soát linh kiện mang đi/mang về.",
            "Lưu lịch sử dịch vụ theo thiết bị khách.",
        ],
        "in_scope": ["Service catalog, install base, ticket lifecycle, scheduling, onsite work, parts, PM, technician app, FSM reports."],
        "out_scope": ["CRM bán hàng đầy đủ.", "Kho tổng WMS (INV)."],
        "actors": [
            ("Dispatcher", "Tiếp nhận & phân công"),
            ("Technician", "Xử lý hiện trường"),
            ("Service Manager", "SLA & năng suất"),
            ("Parts Storekeeper", "Cấp linh kiện"),
            ("Customer (via PRT)", "Tạo/theo dõi ticket"),
        ],
        "terms": [
            ("Install base", "Thiết bị đang vận hành tại khách"),
            ("SLA", "Cam kết thời gian phản hồi/xử lý"),
            ("FTF", "First Time Fix"),
            ("PM", "Preventive Maintenance"),
        ],
        "workflows": [
            {
                "ma": "WF-FSM-01",
                "ten": "Xử lý ticket hiện trường",
                "muc_tieu": "Đóng ticket có nghiệm thu và đối soát linh kiện",
                "buoc": [
                    "Tạo ticket từ hotline/CRM/PRT",
                    "Phân công KTV + lịch hẹn",
                    "Check-in; xử lý; xuất linh kiện",
                    "KH nghiệm thu; đóng ticket",
                    "Đối soát linh kiện; ghi phí/BH; post FIN nếu có",
                ],
            }
        ],
        "entities": [
            ("ServiceType / FaultCode / SlaPolicy", "Danh mục"),
            ("InstalledAsset", "Thiết bị tại KH"),
            ("ServiceTicket / Appointment", "Ticket & lịch"),
            ("TicketPartIssue", "Linh kiện"),
            ("PmSchedule", "Bảo trì định kỳ"),
        ],
        "business_rules": [
            "BR-FSM-01: Ticket trong hạn BH không tính phí công/linh kiện theo policy.",
            "BR-FSM-02: Đóng ticket bắt buộc có nghiệm thu (trừ hủy hợp lệ).",
            "BR-FSM-03: Linh kiện xuất phải gắn ticket.",
            "BR-FSM-04: Vi phạm SLA phải được gắn cờ và báo cáo.",
        ],
        "nfr": [("Mobile tech", "APP KTV offline nhẹ tùy gói"), ("SLA engine", "Tính SLA theo lịch làm việc")],
        "integrations": [
            ("CRM", "KH & escalate"), ("INV", "Linh kiện"),
            ("FIN", "Phí dịch vụ"), ("PRT", "Self-service ticket"),
            ("PJM", "Bảo hành sau bàn giao dự án"),
        ],
        "permissions": [
            "fsm.ticket.manage", "fsm.dispatch.assign", "fsm.parts.issue",
            "fsm.ticket.close", "fsm.pm.manage", "fsm.report.view",
        ],
        "kpis": ["SLA compliance", "FTF", "Parts cost/ticket", "Tech utilization"],
        "assumptions": ["Thiết bị có thể gắn serial từ đơn bán CRM/INV."],
        "open_questions": ["Có tích hợp IoT/cảnh báo máy phase sau?"],
        "default_actors_by_group": {
            "01": "Service Manager", "02": "Service Manager / Dispatcher",
            "03": "Dispatcher", "04": "Technician", "05": "Technician / Dispatcher",
            "06": "Service Manager", "07": "Parts Storekeeper", "08": "Technician",
            "09": "Service Manager",
        },
    },
    "PJM": {
        "ten": "Quản lý dự án",
        "ma_tai_lieu": "SRS-PJM-v1.0",
        "phien_ban": "1.0",
        "lop": "Sản xuất & Dịch vụ",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["CRM", "INV", "FIN", "HRM", "WF"],
        "tom_tat": "Quản lý dự án dịch vụ/triển khai: WBS, tiến độ, nguồn lực, chi phí, change request, nghiệm thu và P&L dự án.",
        "muc_tieu": [
            "Theo dõi tiến độ và ngân sách dự án realtime.",
            "Gắn dự án với cơ hội/hợp đồng và vật tư.",
            "Nghiệm thu – quyết toán rõ ràng.",
        ],
        "in_scope": ["Project types/templates, initiation, WBS/schedule, resources/cost, execution checklists, acceptance, project P&L/reports."],
        "out_scope": ["PM phức tạp kiểu construction BIM.", "HRM full payroll."],
        "actors": [
            ("Project Manager", "Điều phối dự án"),
            ("Project Member", "Thực hiện hạng mục"),
            ("PMO / Manager", "Portfolio & duyệt NS"),
            ("Customer Rep", "Nghiệm thu"),
            ("Cost Controller", "Chi phí–doanh thu DA"),
        ],
        "terms": [
            ("WBS", "Work Breakdown Structure"),
            ("Milestone", "Mốc tiến độ"),
            ("CR", "Change Request"),
            ("Project P&L", "Lãi lỗ theo dự án"),
        ],
        "workflows": [
            {
                "ma": "WF-PJM-01",
                "ten": "Vòng đời dự án",
                "muc_tieu": "Từ khởi tạo đến đóng DA",
                "buoc": [
                    "Tạo DA từ CRM/thủ công; duyệt kickoff",
                    "Lập WBS, milestone, ngân sách, team",
                    "Thực hiện; xuất vật tư; cập nhật tiến độ",
                    "Xử lý CR nếu phát sinh",
                    "Nghiệm thu; ghi doanh thu/chi phí; đóng DA",
                ],
            }
        ],
        "entities": [
            ("Project / ProjectType", "Dự án"),
            ("WbsItem / Milestone", "Kế hoạch"),
            ("ProjectMember / TimeEntry", "Nguồn lực"),
            ("ProjectCost / ProjectBudget", "Tài chính DA"),
            ("ChangeRequest", "CR"),
            ("AcceptanceRecord", "Nghiệm thu"),
        ],
        "business_rules": [
            "BR-PJM-01: Vượt ngân sách quá ngưỡng phải cảnh báo/duyệt.",
            "BR-PJM-02: Đóng DA chỉ khi nghiệm thu cuối hoàn tất (hoặc hủy có duyệt).",
            "BR-PJM-03: CR làm đổi phạm vi/NS/tiến độ phải được duyệt trước thực hiện.",
            "BR-PJM-04: Xuất vật tư DA phải gắn mã dự án.",
        ],
        "nfr": [("Portfolio view", "Xem nhiều DA theo trạng thái RAG"), ("Audit", "Lịch sử đổi kế hoạch/NS")],
        "integrations": [
            ("CRM", "Cơ hội/HĐ"), ("INV", "Vật tư"), ("FIN", "Doanh thu/chi phí"),
            ("HRM", "Nhân sự DA"), ("FSM", "Bảo hành sau bàn giao"), ("WF", "Duyệt kickoff/CR"),
        ],
        "permissions": [
            "pjm.project.manage", "pjm.plan.manage", "pjm.cost.manage",
            "pjm.accept.manage", "pjm.report.view",
        ],
        "kpis": ["On-time milestone", "Budget variance", "Margin by project", "Resource utilization"],
        "assumptions": ["Áp dụng cho dự án dịch vụ/triển khai/nội bộ cấu hình được."],
        "open_questions": ["Có cần Gantt phụ thuộc phức tạp phase 1 không?"],
        "default_actors_by_group": {
            "01": "PMO / Manager", "02": "Project Manager", "03": "Project Manager",
            "04": "Project Manager / Cost Controller", "05": "Project Member / PM",
            "06": "Project Manager / Customer Rep", "07": "PMO / Manager",
        },
    },
    "FIN": {
        "ten": "Tài chính – Kế toán",
        "ma_tai_lieu": "SRS-FIN-v1.0",
        "phien_ban": "1.0",
        "lop": "Tài chính",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["CRM", "PUR", "INV", "POS", "HRM", "AST"],
        "tom_tat": (
            "Module FIN cung cấp COA, kỳ kế toán, sổ cái, quỹ–ngân hàng, AR/AP, thuế/HĐĐT (khung), "
            "ghi nhận doanh thu–chi phí từ module khác, ngân sách và báo cáo tài chính quản trị."
        ),
        "muc_tieu": [
            "Single source of truth cho số liệu tài chính quản trị.",
            "Đối soát công nợ phải thu/trả.",
            "Khóa sổ kỳ có kiểm soát.",
            "Nhận bút toán tự động từ các module vận hành.",
        ],
        "in_scope": ["COA/period, GL, cash/bank, AR, AP, e-invoice framework, tax, revenue/cost postings, budget, FIN reports."],
        "out_scope": [
            "Thay thế hoàn toàn phần mềm thuế chuyên sâu (có thể tích hợp).",
            "Hợp nhất báo cáo tập đoàn phức tạp đa chuẩn kế toán ngay phase 1.",
        ],
        "actors": [
            ("Chief Accountant", "COA, kỳ, khóa sổ"),
            ("GL Accountant", "Bút toán / sổ cái"),
            ("AR Accountant", "Công nợ khách"),
            ("AP Accountant", "Công nợ NCC"),
            ("Treasurer", "Quỹ – ngân hàng"),
            ("CFO / Manager", "Báo cáo & ngân sách"),
        ],
        "terms": [
            ("COA", "Chart of Accounts"),
            ("GL", "General Ledger"),
            ("AR/AP", "Accounts Receivable / Payable"),
            ("Trial balance", "Cân đối phát sinh"),
            ("Posting", "Hạch toán từ chứng từ nguồn"),
        ],
        "workflows": [
            {
                "ma": "WF-FIN-01",
                "ten": "Khóa sổ tháng",
                "muc_tieu": "Chốt số liệu kỳ",
                "buoc": [
                    "Đối chiếu AR/AP/kho/quỹ với sổ cái",
                    "Xử lý chênh lệch; hoàn tất bút toán điều chỉnh",
                    "Chạy kết chuyển cuối kỳ",
                    "Checklist month-end; khóa kỳ",
                    "Xuất P&L / BS / Cashflow quản trị",
                ],
            },
            {
                "ma": "WF-FIN-02",
                "ten": "Thu công nợ khách",
                "muc_tieu": "Phân bổ thanh toán vào hóa đơn",
                "buoc": [
                    "Phát sinh AR từ đơn/HĐ/POS",
                    "Nhận tiền quỹ/NH",
                    "Allocate vào hóa đơn mở",
                    "Cập nhật aging; nhắc nợ nếu quá hạn",
                ],
            },
        ],
        "entities": [
            ("Account / FiscalPeriod", "Danh mục kế toán"),
            ("JournalEntry / JournalLine", "Bút toán"),
            ("CashBook / BankAccount", "Quỹ–NH"),
            ("ArInvoice / ArReceipt", "Phải thu"),
            ("ApInvoice / ApPayment", "Phải trả"),
            ("TaxCode / EInvoice", "Thuế & HĐĐT"),
            ("Budget", "Ngân sách"),
        ],
        "business_rules": [
            "BR-FIN-01: Mọi bút toán phải cân Nợ=Có.",
            "BR-FIN-02: Không sửa trực tiếp chứng từ đã khóa kỳ; phải bút toán điều chỉnh/đảo.",
            "BR-FIN-03: Posting từ module nguồn phải idempotent (không nhân đôi).",
            "BR-FIN-04: Thanh toán AR/AP phải phân bổ hoặc ghi nhận unapplied rõ ràng.",
            "BR-FIN-05: Hạn mức duyệt chi theo workflow WF.",
        ],
        "nfr": [
            ("Toàn vẹn", "ACID cho post sổ cái"),
            ("Hiệu năng", "Trial balance kỳ hiện tại truy vấn chấp nhận được với khối lượng SMB/mid-market"),
            ("Bảo mật", "Tách quyền xem báo cáo lợi nhuận / chi tiết lương"),
        ],
        "integrations": [
            ("CRM/POS", "Doanh thu & thanh toán"), ("PUR/INV", "AP & kho"),
            ("HRM", "Chi phí lương"), ("AST", "Khấu hao"),
            ("LOG", "COD"), ("E-invoice provider", "HĐĐT"),
            ("Bank", "Sao kê / chi hộ"),
        ],
        "permissions": [
            "fin.coa.manage", "fin.journal.post", "fin.ar.manage", "fin.ap.manage",
            "fin.cash.manage", "fin.period.lock", "fin.report.view", "fin.budget.manage",
        ],
        "kpis": ["DSO/DPO", "Cash position", "Budget vs actual", "AR overdue %", "Month-end close days"],
        "assumptions": ["Chuẩn báo cáo quản trị ưu tiên; báo cáo thuế chi tiết có thể qua tích hợp."],
        "open_questions": [
            "Áp dụng chế độ kế toán nào làm mặc định template VN?",
            "Multi-currency bắt buộc phase 1 hay phase sau?",
        ],
        "default_actors_by_group": {
            "01": "Chief Accountant", "02": "GL Accountant", "03": "Treasurer",
            "04": "Treasurer", "05": "AR Accountant", "06": "AP Accountant",
            "07": "GL Accountant", "08": "GL Accountant", "09": "GL Accountant",
            "10": "GL Accountant", "11": "Chief Accountant", "12": "CFO / Manager",
            "13": "CFO / Manager",
        },
    },
    "AST": {
        "ten": "Quản lý tài sản",
        "ma_tai_lieu": "SRS-AST-v1.0",
        "phien_ban": "1.0",
        "lop": "Tài chính",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["FIN", "HRM", "PUR"],
        "tom_tat": "Quản lý TSCĐ/CCDC: thẻ tài sản, khấu hao, ghi tăng/giảm, điều chuyển, kiểm kê, cấp phát và báo cáo giá trị còn lại.",
        "muc_tieu": [
            "Theo dõi và định vị tài sản.",
            "Tính khấu hao định kỳ và post FIN.",
            "Kiểm kê và thu hồi khi nhân sự nghỉ việc.",
        ],
        "in_scope": ["Asset master, depreciation, acquire/transfer/dispose, stocktake, tools issue, AST reports."],
        "out_scope": ["FSM bảo trì hiện trường khách hàng (khác tài sản nội bộ)."],
        "actors": [
            ("Asset Accountant", "Khấu hao & sổ TS"),
            ("Asset Custodian", "Quản lý hiện vật"),
            ("Department Manager", "Người giữ TS"),
            ("HR Officer", "Thu hồi khi nghỉ việc"),
        ],
        "terms": [
            ("NBV", "Net Book Value — giá trị còn lại"),
            ("Depreciation", "Khấu hao"),
            ("CCDC", "Công cụ dụng cụ"),
            ("Disposal", "Thanh lý/ghi giảm"),
        ],
        "workflows": [
            {
                "ma": "WF-AST-01",
                "ten": "Ghi tăng → khấu hao → thanh lý",
                "muc_tieu": "Vòng đời tài sản đầy đủ",
                "buoc": [
                    "Ghi tăng từ mua/dự án; tạo thẻ TS",
                    "Gán vị trí/người giữ; cấu hình KH",
                    "Chạy khấu hao định kỳ; post FIN",
                    "Điều chuyển/kiểm kê khi cần",
                    "Thanh lý/ghi giảm có duyệt; cập nhật sổ",
                ],
            }
        ],
        "entities": [
            ("AssetCategory / Asset", "Danh mục & thẻ"),
            ("DepreciationPolicy / DepreciationEntry", "Khấu hao"),
            ("AssetTransfer / AssetDisposal", "Biến động"),
            ("AssetCountSession", "Kiểm kê"),
            ("ToolIssue", "Cấp phát CCDC"),
        ],
        "business_rules": [
            "BR-AST-01: Không xóa thẻ TS đã khấu hao; chỉ ghi giảm.",
            "BR-AST-02: Khấu hao không vượt nguyên giá (trừ policy đặc biệt).",
            "BR-AST-03: Thanh lý phải có phê duyệt và chứng từ.",
            "BR-AST-04: Điều chuyển đổi custodian phải ghi nhận ngày hiệu lực.",
        ],
        "nfr": [("Batch depreciation", "Chạy KH hàng tháng theo job"), ("Label", "In tem mã TS")],
        "integrations": [
            ("FIN", "Ghi tăng/KH/thanh lý"), ("PUR", "Mua sắm vốn hóa"),
            ("HRM", "Thu hồi khi offboarding"), ("PJM", "Vốn hóa từ dự án"),
        ],
        "permissions": [
            "ast.asset.manage", "ast.depreciation.run", "ast.transfer.manage",
            "ast.dispose.approve", "ast.count.manage", "ast.report.view",
        ],
        "kpis": ["NBV by category", "Assets missing on count", "Depreciation by period"],
        "assumptions": ["Phương pháp KH cấu hình theo nhóm TS."],
        "open_questions": ["Có quản lý tài sản thuê tài chính phase 1?"],
        "default_actors_by_group": {
            "01": "Asset Accountant", "02": "Asset Accountant", "03": "Asset Accountant / Custodian",
            "04": "Asset Custodian", "05": "Asset Custodian / HR Officer", "06": "Asset Accountant",
        },
    },
    "WF": {
        "ten": "Công việc & Phê duyệt",
        "ma_tai_lieu": "SRS-WF-v1.0",
        "phien_ban": "1.0",
        "lop": "Quản trị & Báo cáo",
        "ban_rieng": "Có (hoặc kèm SYS)",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["Tất cả module phát sinh chứng từ cần duyệt"],
        "tom_tat": "Cung cấp task/ticket nội bộ, board công việc và engine workflow phê duyệt đa cấp dùng chung cho toàn ERP.",
        "muc_tieu": [
            "Một hộp chờ duyệt thống nhất.",
            "Cấu hình quy trình duyệt theo loại chứng từ và điều kiện.",
            "Giảm tắc nghẽn phê duyệt bằng SLA và ủy quyền.",
        ],
        "in_scope": ["Tasks, boards, internal tickets, workflow designer, approval runtime, WF reports."],
        "out_scope": ["BPM cực phức tạp thay thế iBPMS doanh nghiệp lớn ngay phase 1."],
        "actors": [
            ("Process Admin", "Thiết kế workflow"),
            ("Approver", "Duyệt chứng từ"),
            ("Requester", "Trình duyệt / tạo task"),
            ("Team Member", "Thực hiện task"),
        ],
        "terms": [
            ("Workflow", "Quy trình duyệt có bước/điều kiện"),
            ("Delegation", "Ủy quyền duyệt tạm thời"),
            ("Escalation", "Chuyển cấp khi quá hạn"),
            ("Inbox", "Hộp chờ duyệt"),
        ],
        "workflows": [
            {
                "ma": "WF-WF-01",
                "ten": "Thiết kế và chạy quy trình duyệt",
                "muc_tieu": "Chứng từ được duyệt đúng người đúng hạn",
                "buoc": [
                    "Process Admin tạo mẫu workflow và gắn loại chứng từ",
                    "Requester trình duyệt từ module nguồn",
                    "Approver nhận inbox; duyệt/từ chối/trả bổ sung",
                    "Escalation/ủy quyền nếu cần",
                    "Kết quả trả về module nguồn; lưu lịch sử",
                ],
            }
        ],
        "entities": [
            ("Task / Ticket", "Công việc"),
            ("WorkflowDefinition / WorkflowVersion", "Mẫu quy trình"),
            ("ApprovalInstance / ApprovalStep", "Phiên duyệt"),
            ("DelegationRule", "Ủy quyền"),
        ],
        "business_rules": [
            "BR-WF-01: Không bỏ qua bước duyệt bắt buộc trừ force-approve có quyền đặc biệt + audit.",
            "BR-WF-02: Ủy quyền có thời hạn; hết hạn tự hết hiệu lực.",
            "BR-WF-03: Từ chối phải có lý do.",
            "BR-WF-04: Module nguồn không được coi là approved nếu instance WF chưa completed.",
        ],
        "nfr": [("Realtime inbox", "Thông báo duyệt đẩy về app/web"), ("Audit", "Lưu đầy đủ lịch sử bước duyệt")],
        "integrations": [
            ("SYS", "User/role/thông báo"),
            ("HRM/CRM/PUR/FIN/PJM/…", "Chứng từ nguồn"),
        ],
        "permissions": [
            "wf.task.manage", "wf.workflow.design", "wf.approve",
            "wf.delegate.manage", "wf.report.view",
        ],
        "kpis": ["Avg approval cycle time", "Overdue approvals", "Task backlog"],
        "assumptions": ["Các module đăng ký document type + callback khi cài đặt."],
        "open_questions": ["Có hỗ trợ duyệt song song nhiều nhánh ngay phase 1?"],
        "default_actors_by_group": {
            "01": "Process Admin", "02": "Requester / Team Member", "03": "Team Member",
            "04": "Requester / Team Member", "05": "Process Admin",
            "06": "Approver", "07": "Process Admin",
        },
    },
    "BI": {
        "ten": "Báo cáo & Business Intelligence",
        "ma_tai_lieu": "SRS-BI-v1.0",
        "phien_ban": "1.0",
        "lop": "Quản trị & Báo cáo",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["Các module nghiệp vụ đã mua — dataset theo license"],
        "tom_tat": (
            "Module BI cung cấp dataset theo license, dashboard quản trị, thư viện báo cáo chuẩn, "
            "cảnh báo KPI, self-service cơ bản và (phase sau) dự báo/AI."
        ),
        "muc_tieu": [
            "Một nơi xem KPI tổng hợp theo quyền và module đã mua.",
            "Giảm phụ thuộc xuất Excel thủ công.",
            "Cảnh báo sớm khi KPI vượt ngưỡng.",
        ],
        "in_scope": ["Datasets, dashboards, report catalog, alerts, self-service light, optional forecast."],
        "out_scope": ["Data warehouse doanh nghiệp tách biệt hoàn toàn (có thể phase sau).", "ETL ngoài hệ thống."],
        "actors": [
            ("BI Admin", "Catalog dataset/KPI, phân quyền"),
            ("Executive", "Dashboard lãnh đạo"),
            ("Manager", "Báo cáo chuyên môn"),
            ("Analyst", "Self-service nhẹ"),
        ],
        "terms": [
            ("Dataset", "Tập dữ liệu được phép phân tích"),
            ("KPI", "Chỉ tiêu đo lường"),
            ("Alert threshold", "Ngưỡng cảnh báo"),
            ("Refresh", "Làm mới dữ liệu"),
        ],
        "workflows": [
            {
                "ma": "WF-BI-01",
                "ten": "Phát hành dashboard theo gói license",
                "muc_tieu": "User chỉ thấy KPI module được mua",
                "buoc": [
                    "Xác định module active trên license",
                    "Mở dataset/dashboard tương ứng",
                    "Gán quyền xem theo role",
                    "Cấu hình refresh và alert",
                    "User tiêu thụ báo cáo/xuất file/đăng ký email",
                ],
            }
        ],
        "entities": [
            ("Dataset / DatasetField", "Nguồn phân tích"),
            ("Dashboard / Widget", "Trực quan"),
            ("ReportDefinition", "Báo cáo chuẩn"),
            ("KpiDefinition / AlertRule", "KPI & cảnh báo"),
            ("ScheduledReport", "Lịch gửi"),
        ],
        "business_rules": [
            "BR-BI-01: Không expose dataset của module chưa license.",
            "BR-BI-02: Phân quyền BI không được vượt data scope SYS.",
            "BR-BI-03: Báo cáo tài chính nhạy cảm chỉ role được cấp.",
            "BR-BI-04: Mọi truy cập dataset quan trọng có thể ghi access log.",
        ],
        "nfr": [
            ("Hiệu năng dashboard", "Tải dashboard chuẩn p95 < 5s với cache"),
            ("Freshness", "Refresh gần realtime hoặc định kỳ theo cấu hình"),
        ],
        "integrations": [
            ("Tất cả module", "Sự kiện/dữ liệu nguồn"),
            ("SYS", "License & ACL"),
            ("Email", "Schedule report"),
        ],
        "permissions": [
            "bi.dashboard.view", "bi.report.view", "bi.dataset.manage",
            "bi.alert.manage", "bi.selfservice.use",
        ],
        "kpis": ["Dashboard adoption", "Scheduled report success rate", "Alert response time"],
        "assumptions": ["Mỗi module nghiệp vụ cung cấp view/read-model cho BI."],
        "open_questions": ["Dùng OLTP trực tiếp có read replica hay bắt buộc ODS phase 1?"],
        "default_actors_by_group": {
            "01": "BI Admin", "02": "Executive / Manager", "03": "Manager",
            "04": "BI Admin / Manager", "05": "Analyst", "06": "BI Admin / Analyst",
        },
    },
    "PRT": {
        "ten": "Cổng khách hàng / đối tác (Portal)",
        "ma_tai_lieu": "SRS-PRT-v1.0",
        "phien_ban": "1.0",
        "lop": "Bán hàng & Khách hàng",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["CRM", "LOG", "FIN", "FSM"],
        "tom_tat": (
            "Cổng tự phục vụ cho khách hàng (và tùy gói: NCC/đại lý): tài khoản, đơn hàng, "
            "công nợ, ticket hỗ trợ/bảo hành, tài liệu và cấu hình tính năng theo gói."
        ),
        "muc_tieu": [
            "Giảm tải CSKH/Sales Admin cho tra cứu đơn và công nợ.",
            "Cho phép tạo/theo dõi ticket dịch vụ.",
            "Mở rộng B2B self-service theo gói bán.",
        ],
        "in_scope": ["Portal auth, customer orders/shipments, AR view/pay framework, tickets, content, vendor/dealer portal optional, portal admin."],
        "out_scope": ["CMS marketing website đầy đủ.", "Marketplace đa vendor."],
        "actors": [
            ("Customer User", "Liên hệ phía KH"),
            ("Customer Admin", "Quản lý nhiều liên hệ DN"),
            ("Vendor User", "Người dùng NCC (tùy gói)"),
            ("Portal Admin", "Cấu hình nội dung & feature flags"),
            ("Internal Ops", "Xử lý yêu cầu phát sinh từ portal"),
        ],
        "terms": [
            ("Self-service", "Khách tự thao tác không qua nội bộ"),
            ("Feature flag", "Bật/tắt tính năng portal theo gói"),
            ("Dealer portal", "Cổng đại lý B2B"),
        ],
        "workflows": [
            {
                "ma": "WF-PRT-01",
                "ten": "KH theo dõi đơn và tạo ticket",
                "muc_tieu": "Tự phục vụ sau bán",
                "buoc": [
                    "Đăng ký/liên kết tài khoản với mã KH",
                    "Xem đơn/vận đơn/hóa đơn",
                    "Tạo ticket BH/hỗ trợ; theo dõi trạng thái",
                    "Đánh giá dịch vụ sau đóng ticket",
                ],
            }
        ],
        "entities": [
            ("PortalAccount / PortalContact", "Tài khoản cổng"),
            ("PortalFeatureConfig", "Tính năng theo gói"),
            ("PortalTicket", "Ticket từ cổng (map FSM/CRM)"),
            ("PortalContent", "Nội dung/catalogue"),
        ],
        "business_rules": [
            "BR-PRT-01: User portal chỉ thấy dữ liệu KH/NCC được liên kết.",
            "BR-PRT-02: Tính năng hiển thị theo feature flag gói.",
            "BR-PRT-03: Thao tác tạo ticket/đơn phải rate-limit và audit.",
            "BR-PRT-04: Thanh toán online (nếu bật) phải đối soát với FIN.",
        ],
        "nfr": [
            ("UX", "Mobile-friendly"),
            ("Bảo mật", "Tách bề mặt tấn công khỏi back-office; 2FA tùy cấu hình"),
            ("Uptime", "Cổng public cần HA riêng khi production"),
        ],
        "integrations": [
            ("CRM", "KH, đơn, case"), ("LOG", "Tracking"), ("FIN", "AR/thanh toán"),
            ("FSM", "Ticket BH"), ("PUR", "PO phía NCC"), ("SYS", "Auth/file/thông báo"),
        ],
        "permissions": [
            "prt.account.manage", "prt.order.view", "prt.ar.view",
            "prt.ticket.create", "prt.content.manage", "prt.vendor.access",
        ],
        "kpis": ["Portal MAU", "% ticket tạo từ portal", "% tra cứu đơn self-service", "CSAT portal"],
        "assumptions": ["Mỗi Customer User map 1–n Contact thuộc 1 Customer CRM."],
        "open_questions": [
            "Đăng ký tự do hay chỉ invite từ nội bộ phase 1?",
            "Dealer portal có giá/tồn realtime không?",
        ],
        "default_actors_by_group": {
            "01": "Portal Admin / Customer Admin", "02": "Customer User",
            "03": "Customer User", "04": "Customer User", "05": "Customer User",
            "06": "Vendor User", "07": "Portal Admin",
        },
    },
}
