# -*- coding: utf-8 -*-
"""Metadata nghiệp vụ bổ sung cho sinh SRS — generic, bán theo module."""

from __future__ import annotations

# folder_name relative to 01. Modules
FOLDERS = {
    "SYS": "01. SYS - Hệ thống nền tảng",
    "HRM": "02. HRM - Quản trị nhân sự",
    "LMS": "03. LMS - Đào tạo",
    "CRM": "04. CRM - CRM và Bán hàng",
    "POS": "05. POS - POS bán lẻ",
    "PUR": "06. PUR - Mua hàng",
    "INV": "07. INV - Kho và Tồn kho",
    "LOG": "08. LOG - Giao vận",
    "MFG": "09. MFG - Sản xuất",
    "FSM": "10. FSM - Dịch vụ kỹ thuật",
    "PJM": "11. PJM - Quản lý dự án",
    "FIN": "12. FIN - Tài chính Kế toán",
    "AST": "13. AST - Quản lý tài sản",
    "WF": "14. WF - Công việc và Phê duyệt",
    "BI": "15. BI - Báo cáo và BI",
    "PRT": "16. PRT - Cổng khách hàng",
}

META = {
    "SYS": {
        "ten": "Hệ thống nền tảng (System Platform)",
        "ma_tai_lieu": "SRS-SYS-v1.0",
        "phien_ban": "1.0",
        "lop": "Nền tảng",
        "ban_rieng": "Không — luôn kèm mọi gói",
        "phu_thuoc": [],
        "khuyen_nghi_kem": [],
        "tom_tat": (
            "Module nền tảng cung cấp danh tính, phân quyền, tổ chức đa chi nhánh, license module, "
            "cấu hình dùng chung, thông báo, file, audit và khung tích hợp. Mọi module nghiệp vụ "
            "phải chạy trên SYS; không bán độc lập."
        ),
        "muc_tieu": [
            "Chuẩn hóa xác thực, phân quyền RBAC và phạm vi dữ liệu (data scope).",
            "Cho phép bật/tắt module theo license để bán theo gói.",
            "Cung cấp dịch vụ dùng chung: file, thông báo, import/export, audit, webhook.",
            "Đảm bảo multi-tenant / đa chi nhánh an toàn, có kiểm toán.",
        ],
        "in_scope": [
            "AuthN/AuthZ, user, role, permission, org structure, license, settings, notification, file, audit, integration hub.",
        ],
        "out_scope": [
            "Nghiệp vụ chuyên biệt của HRM/CRM/FIN… (chỉ cung cấp nền).",
            "BI self-service nâng cao (thuộc BI).",
            "Nội dung portal khách hàng (thuộc PRT).",
        ],
        "actors": [
            ("System Admin", "Quản trị toàn tenant: user, role, license, cấu hình"),
            ("Security Admin", "Phân quyền, audit, chính sách mật khẩu/2FA"),
            ("Org Admin", "Quản lý chi nhánh, phòng ban trong phạm vi được giao"),
            ("End User", "Đăng nhập, đổi mật khẩu, nhận thông báo"),
            ("Integration Account", "Gọi API bằng API Key / service account"),
            ("Hệ thống", "Job nền, event bus, gửi thông báo"),
        ],
        "terms": [
            ("Tenant", "Không gian dữ liệu của một khách hàng thuê bao"),
            ("RBAC", "Role-Based Access Control — phân quyền theo vai trò"),
            ("Data scope", "Phạm vi dữ liệu được phép xem/sửa theo org/kho/…"),
            ("License", "Gói quyền sử dụng module / quota user"),
            ("Webhook", "Cơ chế đẩy sự kiện ra hệ thống bên ngoài"),
        ],
        "workflows": [
            {
                "ma": "WF-SYS-01",
                "ten": "Onboard tenant mới",
                "muc_tieu": "Khởi tạo công ty, admin đầu tiên, gói license và cấu hình cơ bản",
                "buoc": [
                    "Tạo tenant / công ty với thông tin pháp lý cơ bản",
                    "Tạo user System Admin đầu tiên và gửi lời mời kích hoạt",
                    "Gán gói license (module + hạn dùng + quota)",
                    "Khởi tạo danh mục dùng chung mặc định (tiền tệ, ĐVT, tỉnh/TP…)",
                    "Cấu hình email/SMS gateway (nếu có)",
                    "Admin đăng nhập, đổi mật khẩu, bật 2FA (khuyến nghị)",
                    "Kiểm tra menu động chỉ hiện module đã license",
                ],
            },
            {
                "ma": "WF-SYS-02",
                "ten": "Cấp quyền người dùng mới",
                "muc_tieu": "User vào hệ thống đúng role và đúng phạm vi dữ liệu",
                "buoc": [
                    "Admin tạo user hoặc gửi invite",
                    "Gán chi nhánh mặc định và các chi nhánh được truy cập",
                    "Gán một/nhiều role",
                    "Hệ thống tính permission + data scope hiệu lực",
                    "User kích hoạt / đăng nhập lần đầu",
                    "Audit ghi nhận tạo user và gán quyền",
                ],
            },
            {
                "ma": "WF-SYS-03",
                "ten": "Thay đổi gói module (upsell/downsell)",
                "muc_tieu": "Bật/tắt module theo hợp đồng mà không phá dữ liệu hiện có",
                "buoc": [
                    "Cập nhật license (thêm/bớt module, đổi hạn)",
                    "Hệ thống ẩn menu + chặn API module bị tắt",
                    "Dữ liệu module cũ được giữ (không xóa) theo chính sách lưu trữ",
                    "Ghi audit và thông báo admin",
                ],
            },
        ],
        "entities": [
            ("Tenant", "Đơn vị thuê bao"),
            ("Company / Branch / Department", "Cây tổ chức"),
            ("User", "Tài khoản đăng nhập"),
            ("Role / Permission", "RBAC"),
            ("UserRole / DataScope", "Gán quyền & phạm vi"),
            ("License / LicenseModule", "Gói và module được phép"),
            ("Setting / Sequence", "Cấu hình & sinh mã"),
            ("NotificationTemplate / NotificationLog", "Thông báo"),
            ("FileObject", "Tài liệu đính kèm"),
            ("AuditLog / LoginLog", "Nhật ký"),
            ("ApiKey / WebhookSubscription", "Tích hợp"),
        ],
        "business_rules": [
            "BR-SYS-01: Không xóa cứng user/role đã phát sinh giao dịch; chỉ soft-disable.",
            "BR-SYS-02: Module nghiệp vụ chỉ accessible khi license active và trong hạn.",
            "BR-SYS-03: Mọi thay đổi phân quyền phải ghi audit (who/when/before/after).",
            "BR-SYS-04: Password phải tuân thủ policy tenant; lưu hash, không lưu plaintext.",
            "BR-SYS-05: API Key có phạm vi quyền tối thiểu (least privilege).",
            "BR-SYS-06: Một user có thể nhiều role; quyền hiệu lực = hợp (union) theo chính sách tenant.",
        ],
        "nfr": [
            ("Bảo mật", "Mã hóa transport TLS; hash mật khẩu; hỗ trợ 2FA; chống brute-force"),
            ("Hiệu năng", "Đăng nhập p95 < 2s; phân quyền cache được; audit ghi async"),
            ("Sẵn sàng", "Dịch vụ auth là single point — cần HA khi triển khai production"),
            ("Audit", "Lưu audit tối thiểu 12 tháng (cấu hình được)"),
            ("Đa ngôn ngữ", "Hỗ trợ VI làm mặc định; EN tùy gói"),
        ],
        "integrations": [
            ("Outbound", "Email SMTP/ESP, SMS gateway, Webhook sự kiện user/role/license"),
            ("Inbound", "OIDC/OAuth SSO, API quản trị tenant"),
            ("Internal events", "UserCreated, UserDisabled, RoleChanged, LicenseChanged, NotificationRequested"),
        ],
        "permissions": [
            "sys.user.manage", "sys.role.manage", "sys.permission.assign",
            "sys.org.manage", "sys.license.manage", "sys.setting.manage",
            "sys.file.manage", "sys.audit.view", "sys.integration.manage",
        ],
        "kpis": [
            "Số user active / theo license quota",
            "Số lần đăng nhập thất bại / khóa tài khoản",
            "Thời gian phản hồi auth",
            "Số thay đổi phân quyền theo kỳ",
        ],
        "assumptions": [
            "Mỗi khách hàng = một tenant (hoặc multi-company trong một tenant theo cấu hình).",
            "Module nghiệp vụ tự đăng ký permission catalog vào SYS khi được cài.",
        ],
        "open_questions": [
            "Có bắt buộc multi-tenant isolation mức database riêng từ phase 1 không?",
            "Chính sách lưu dữ liệu module khi khách hủy license: giữ bao lâu?",
        ],
        "default_actors_by_group": {
            "01": "End User / System Admin",
            "02": "System Admin",
            "03": "Security Admin",
            "04": "Org Admin / System Admin",
            "05": "System Admin",
            "06": "System Admin",
            "07": "Hệ thống / End User",
            "08": "End User / System Admin",
            "09": "System Admin",
            "10": "Security Admin",
            "11": "System Admin / Integration Account",
            "12": "System Admin",
        },
    },
    "HRM": {
        "ten": "Quản trị nhân sự (Human Resource Management)",
        "ma_tai_lieu": "SRS-HRM-v1.0",
        "phien_ban": "1.0",
        "lop": "Nhân sự & Đào tạo",
        "ban_rieng": "Có",
        "phu_thuoc": ["SYS"],
        "khuyen_nghi_kem": ["WF", "FIN", "LMS"],
        "tom_tat": (
            "Module HRM quản lý vòng đời nhân sự: tổ chức, hồ sơ, hợp đồng, tuyển dụng, "
            "onboarding, xếp ca, chấm công, nghỉ phép, điều động, lương/phụ cấp, offboarding "
            "và báo cáo nhân sự. Thiết kế generic cho doanh nghiệp đa chi nhánh."
        ),
        "muc_tieu": [
            "Số hóa hồ sơ và biến động nhân sự end-to-end.",
            "Chấm công – xếp ca – nghỉ phép chính xác, có kiểm soát duyệt.",
            "Tính lương theo kỳ từ dữ liệu công và rule cấu hình.",
            "Cung cấp số liệu headcount, chi phí nhân sự, tuân thủ hợp đồng.",
        ],
        "in_scope": [
            "Org HR, employee master, contract, recruitment, onboarding/probation, staffing & shift, attendance, leave, transfer/secondment, payroll, discipline/reward, offboarding, HR reports.",
        ],
        "out_scope": [
            "Nội dung đào tạo chi tiết (LMS).",
            "Hạch toán kế toán đầy đủ (FIN nhận bút toán lương).",
            "Quản lý tài sản chi tiết khi bàn giao (AST; HRM chỉ checklist).",
        ],
        "actors": [
            ("HR Admin", "Cấu hình master HR, rule lương/phép"),
            ("HR Officer", "Vận hành hồ sơ, tuyển dụng, công, lương"),
            ("Line Manager", "Duyệt nghỉ/đổi ca, xem đội nhóm, đánh giá"),
            ("Employee", "Self-service: công, phép, phiếu lương, cập nhật thông tin hạn chế"),
            ("Payroll Accountant", "Chốt kỳ lương, xuất chi lương"),
            ("Recruiter", "Quản lý tin tuyển và ứng viên"),
            ("Hệ thống", "Nhắc hạn HĐ/thử việc, tính công/lương"),
        ],
        "terms": [
            ("Headcount", "Định biên / số lượng nhân sự"),
            ("Timesheet", "Bảng công theo kỳ"),
            ("Payroll", "Kỳ và bảng tính lương"),
            ("Probation", "Thời gian thử việc"),
            ("Secondment", "Điều động hỗ trợ đơn vị khác"),
        ],
        "workflows": [
            {
                "ma": "WF-HRM-01",
                "ten": "Tuyển dụng → Onboarding → Chính thức",
                "muc_tieu": "Từ nhu cầu tuyển đến nhân sự chính thức có hồ sơ & hợp đồng",
                "buoc": [
                    "Tạo và duyệt nhu cầu tuyển (PR tuyển)",
                    "Đăng tin / tiếp nhận ứng viên / sơ loại",
                    "Đánh giá và quyết định nhận việc",
                    "Tạo hồ sơ nhân sự + checklist onboarding",
                    "Ký hợp đồng / phụ lục; gán đơn vị – chức danh",
                    "Theo dõi thử việc; chuyển chính thức hoặc chấm dứt",
                ],
            },
            {
                "ma": "WF-HRM-02",
                "ten": "Xếp ca → Chấm công → Khóa công",
                "muc_tieu": "Có bảng công kỳ sạch để tính lương",
                "buoc": [
                    "Khai báo mẫu ca và định biên (nếu dùng)",
                    "Xếp lịch ca; nhân viên xem trên app/web",
                    "Chấm công theo phương thức cấu hình",
                    "Xin–duyệt điều chỉnh công khi sai/thiếu",
                    "Khóa bảng công kỳ; mở khóa có kiểm soát nếu cần",
                ],
            },
            {
                "ma": "WF-HRM-03",
                "ten": "Tính lương theo kỳ",
                "muc_tieu": "Sinh bảng lương và chi trả",
                "buoc": [
                    "Tạo kỳ lương; nạp công đã khóa + phụ cấp/khấu trừ",
                    "Chạy payroll engine theo rule",
                    "HR/Kế toán rà soát, điều chỉnh có audit",
                    "Duyệt và khóa kỳ lương",
                    "Xuất phiếu lương NV + file ngân hàng",
                    "Đẩy bút toán/chi phí sang FIN (nếu có)",
                ],
            },
            {
                "ma": "WF-HRM-04",
                "ten": "Nghỉ việc / Offboarding",
                "muc_tieu": "Chấm dứt quan hệ LĐ có bàn giao và quyết toán",
                "buoc": [
                    "Nhân viên/HR tạo đơn nghỉ việc",
                    "Duyệt theo workflow; kiểm tra báo trước",
                    "Checklist bàn giao quyền/hệ thống/tài sản",
                    "Quyết toán phép – lương cuối",
                    "Khóa hồ sơ; thu hồi truy cập SYS",
                ],
            },
        ],
        "entities": [
            ("OrgUnit / JobTitle / Position", "Tổ chức & vị trí"),
            ("Employee", "Hồ sơ nhân sự"),
            ("EmploymentStatusHistory", "Lịch sử trạng thái"),
            ("Contract / ContractAppendix", "Hợp đồng"),
            ("RecruitmentRequest / Candidate / JobPosting", "Tuyển dụng"),
            ("OnboardingChecklist", "Checklist nhận việc"),
            ("ShiftTemplate / ShiftAssignment", "Ca làm việc"),
            ("AttendancePunch / Timesheet", "Chấm công"),
            ("LeaveType / LeaveBalance / LeaveRequest", "Nghỉ phép"),
            ("PayrollPeriod / Payslip / SalaryRule", "Lương"),
            ("TransferOrder", "Điều động"),
        ],
        "business_rules": [
            "BR-HRM-01: Mã nhân sự duy nhất trong tenant, không tái sử dụng.",
            "BR-HRM-02: Chỉ tính lương từ bảng công đã khóa (trừ điều chỉnh được duyệt).",
            "BR-HRM-03: Quỹ phép không âm trừ khi policy cho phép ứng phép.",
            "BR-HRM-04: Nhân sự nghỉ việc phải hoàn tất checklist offboarding trước khi khóa hồ sơ.",
            "BR-HRM-05: Dữ liệu lương là dữ liệu nhạy cảm — mask theo permission field-level.",
            "BR-HRM-06: Mọi điều chỉnh công/lương sau khóa kỳ phải có lý do + người duyệt.",
        ],
        "nfr": [
            ("Bảo mật", "Mã hóa dữ liệu nhạy cảm; phân quyền field-level cho lương/CCCD"),
            ("Hiệu năng", "Bảng công 5.000 NV khóa kỳ < 5 phút (batch)"),
            ("Mobile", "Employee self-service dùng được trên mobile web/app"),
            ("Tuân thủ", "Lưu hồ sơ/HĐ theo thời hạn pháp lý cấu hình được"),
        ],
        "integrations": [
            ("SYS", "User lifecycle, org master, workflow duyệt, file, thông báo"),
            ("WF", "Duyệt nghỉ / điều chỉnh công / đề xuất tuyển / kỳ lương"),
            ("LMS", "Đồng bộ chứng chỉ đào tạo bắt buộc vào hồ sơ"),
            ("FIN", "Post chi phí lương, tạm ứng, khấu trừ"),
            ("AST", "Checklist thu hồi tài sản khi nghỉ việc"),
            ("Device", "Máy chấm công / geo-fence app"),
        ],
        "permissions": [
            "hrm.employee.manage", "hrm.employee.view", "hrm.contract.manage",
            "hrm.recruitment.manage", "hrm.attendance.manage", "hrm.attendance.approve",
            "hrm.leave.approve", "hrm.payroll.run", "hrm.payroll.view_all",
            "hrm.payslip.view_self", "hrm.report.view",
        ],
        "kpis": [
            "Headcount theo đơn vị/trạng thái",
            "Tỷ lệ đi trễ / quên chấm",
            "Thời gian fill vị trí tuyển dụng",
            "Chi phí lương / doanh thu (khi có FIN)",
            "Tỷ lệ nghỉ việc (turnover)",
        ],
        "assumptions": [
            "Chính sách lương/phụ cấp cấu hình được theo tenant, không hard-code ngành.",
            "Có thể dùng HRM độc lập với LMS; chứng chỉ thủ công nếu chưa mua LMS.",
        ],
        "open_questions": [
            "Phase 1 có gồm đánh giá hiệu suất đầy đủ hay chỉ checklist cơ bản?",
            "Phạm vi tích hợp máy chấm công cụ thể theo hãng nào ở triển khai?",
        ],
        "default_actors_by_group": {
            "01": "HR Admin",
            "02": "HR Officer",
            "03": "HR Officer",
            "04": "HR Officer",
            "05": "Line Manager / HR Officer",
            "06": "Recruiter / HR Officer",
            "07": "HR Officer / Line Manager",
            "08": "HR Admin / Line Manager",
            "09": "Line Manager / HR Officer",
            "10": "HR Officer / Line Manager",
            "11": "HR Admin",
            "12": "Employee / Line Manager",
            "13": "HR Officer / Line Manager",
            "14": "Employee / Line Manager",
            "15": "HR Officer",
            "16": "HR Officer / Employee",
            "17": "HR Admin / Payroll Accountant",
            "18": "Payroll Accountant / HR Officer",
            "19": "Line Manager / HR Officer",
            "20": "HR Admin / Line Manager",
        },
    },
}
