#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sinh bộ tài liệu Tích hợp liên module v1.0 (MD + Word chuyên nghiệp)."""
from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES_TOOLS = Path(__file__).resolve().parents[2] / "01. Modules" / "_tools"
sys.path.insert(0, str(MODULES_TOOLS))

from build_srs_docx_pro import build, extract_meta_from_md  # noqa: E402

TODAY = date.today().strftime("%d/%m/%Y")

MODULES = [
    ("SYS", "Hệ thống nền tảng"),
    ("HRM", "Quản trị nhân sự"),
    ("LMS", "Đào tạo"),
    ("CRM", "CRM & Bán hàng"),
    ("POS", "POS bán lẻ"),
    ("PUR", "Mua hàng"),
    ("INV", "Kho & Tồn kho"),
    ("LOG", "Giao vận"),
    ("MFG", "Sản xuất"),
    ("FSM", "Dịch vụ kỹ thuật"),
    ("PJM", "Quản lý dự án"),
    ("FIN", "Tài chính – Kế toán"),
    ("AST", "Quản lý tài sản"),
    ("WF", "Công việc & Phê duyệt"),
    ("BI", "Báo cáo & BI"),
    ("PRT", "Cổng khách hàng"),
]


def header(doc_code: str, title: str, subtitle: str) -> list[str]:
    return [
        f"# {doc_code} — {title}",
        "",
        f"> **{subtitle}**",
        "> Bộ tài liệu *Tích hợp liên module* — ERP bán theo module.",
        f"> Phiên bản **1.0** · Ngày {TODAY} · Trạng thái: **Chờ duyệt nghiệp vụ / Solution**.",
        "> Generic — không gắn khách hàng hay ngành cụ thể.",
        "",
        "---",
        "",
        "## 0. Thông tin tài liệu",
        "",
        "| Thuộc tính | Giá trị |",
        "|---|---|",
        f"| Mã tài liệu | `{doc_code}` |",
        f"| Tên | {title} |",
        "| Phiên bản | 1.0 |",
        f"| Ngày | {TODAY} |",
        "| Phân loại | Tích hợp liên module (BA / Solution) |",
        "| Định dạng bàn giao | Microsoft Word (`.docx`) |",
        "| Phụ thuộc | Bộ SRS module v1.1 |",
        "",
        "| Ver | Ngày | Mô tả | Trạng thái |",
        "|---|---|---|---|",
        f"| 1.0 | {TODAY} | Khởi tạo bộ tích hợp liên module | Chờ duyệt |",
        "",
        "---",
        "",
    ]


def write(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {path.name} ({len(lines)} lines)")


# ---------------------------------------------------------------------------
# INT-01
# ---------------------------------------------------------------------------
def doc_int_01() -> list[str]:
    a: list[str] = []
    a += header(
        "INT-01-v1.0",
        "Tổng quan kiến trúc tích hợp liên module",
        "Integration Architecture Overview",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "### 1.1. Mục đích",
        "Tài liệu mô tả **nguyên tắc và mô hình tích hợp** giữa 16 module ERP, làm căn cứ chung trước khi thiết kế API/Event và cấu trúc source.",
        "",
        "### 1.2. Phạm vi",
        "- Tích hợp **nội bộ** giữa các module sản phẩm (qua SYS).",
        "- Khung tích hợp **bên ngoài** (SSO, email/SMS, thanh toán, 3PL, HĐĐT) — mức logic.",
        "- Không mô tả chi tiết UI từng màn hình (thuộc SRS module).",
        "",
        "### 1.3. Đối tượng đọc",
        "- Solution Architect, Tech Lead",
        "- Business Analyst (chốt journey E2E)",
        "- Presales (giải thích gói bán kèm module)",
        "",
        "---",
        "",
        "## 2. Bản đồ sản phẩm",
        "",
        "```text",
        "                         +------------------+",
        "                         |   Clients Web    |",
        "                         |  (Shell + packs) |",
        "                         +--------+---------+",
        "                                  |",
        "                         +--------v---------+",
        "                         |       SYS        |",
        "                         | Auth RBAC License|",
        "                         | Org File Notify  |",
        "                         |   Event Bus      |",
        "                         +--------+---------+",
        "                                  |",
        "     +------------+-------+-------+--------+-----------+",
        "     |            |       |       |        |           |",
        "   HRM/LMS     CRM/POS  PUR/INV  MFG/FSM  FIN/AST    WF/BI/PRT",
        "               LOG/PJM",
        "```",
        "",
        "| Lớp | Module | Vai trò tích hợp |",
        "|---|---|---|",
        "| Nền tảng | SYS | Identity, quyền, license, bus, file, thông báo |",
        "| Ngang | WF, BI, PRT | Duyệt / phân tích / cổng ngoài — nối nhiều module |",
        "| Nhân sự | HRM, LMS | Vòng đời người & năng lực |",
        "| Thương mại | CRM, POS, PRT | Bán hàng & trải nghiệm KH |",
        "| Chuỗi cung ứng | PUR, INV, LOG, MFG | Mua – kho – giao – sản xuất |",
        "| Tài sản & tiền | FIN, AST, FSM, PJM | Tiền, tài sản, dịch vụ, dự án |",
        "",
        "---",
        "",
        "## 3. Nguyên tắc tích hợp (bắt buộc)",
        "",
        "| # | Nguyên tắc | Mô tả |",
        "|---:|---|---|",
        "| P1 | SYS-first | Mọi module bắt buộc phụ thuộc SYS; không tự auth/RBAC riêng. |",
        "| P2 | Event over hard-call | Module không gọi API nội bộ module khác trực tiếp (trừ đọc master qua contract SYS/shared). Ưu tiên publish/subscribe. |",
        "| P3 | Single owner | Mỗi master data có đúng một module sở hữu; module khác chỉ reference ID. |",
        "| P4 | License gate | Middleware SYS chặn API/UI khi license module tắt; dữ liệu không bị xóa. |",
        "| P5 | Data scope | Mọi truy vấn xuyên module tôn trọng data scope (chi nhánh/kho/đơn vị). |",
        "| P6 | Idempotent consumer | Consumer sự kiện xử lý được trùng lặp an toàn (ít nhất một lần giao). |",
        "| P7 | Audit & trace | Sự kiện nghiệp vụ trọng yếu có correlation id + audit. |",
        "| P8 | Degrade gracefully | Module phụ thuộc mềm thiếu license → ẩn tính năng, không làm sập module chính. |",
        "",
        "---",
        "",
        "## 4. Mô hình giao tiếp",
        "",
        "### 4.1. Ba kênh chuẩn",
        "",
        "| Kênh | Khi nào dùng | Ví dụ |",
        "|---|---|---|",
        "| **Command / API đồng bộ** | Cần kết quả ngay, cùng transaction biên | Reserve tồn khi xác nhận SO |",
        "| **Domain Event (async)** | Thông báo đã xảy ra, fan-out nhiều subscriber | `PayrollPosted` → FIN tạo bút toán |",
        "| **Shared read model** | Tra cứu master ổn định, ít thay đổi | CustomerId, ItemId, EmployeeId |",
        "",
        "### 4.2. Vai trò Event Bus (SYS)",
        "1. Module nguồn **publish** sự kiện sau khi commit giao dịch thành công.",
        "2. SYS lưu **Outbox** (đảm bảo không mất event).",
        "3. Subscriber nhận, xử lý idempotent, ghi **Inbox/Processed**. ",
        "4. Lỗi → retry có backoff + Dead Letter + cảnh báo vận hành.",
        "",
        "### 4.3. Đồng bộ vs bất đồng bộ (gợi ý)",
        "| Tình huống | Kiểu |",
        "|---|---|",
        "| Kiểm tra ATP / trừ tồn tại quầy | Đồng bộ |",
        "| Post lương sang FIN | Bất đồng bộ + đối soát |",
        "| Gửi thông báo duyệt | Bất đồng bộ |",
        "| Tạo lệnh giao từ đơn | Đồng bộ tạo chứng từ + event trạng thái |",
        "",
        "---",
        "",
        "## 5. Ranh giới trách nhiệm SYS",
        "",
        "| Khả năng | SYS cung cấp | Module nghiệp vụ |",
        "|---|---|---|",
        "| Đăng nhập / phiên | Có | Không tự quản |",
        "| Permission catalog | Đăng ký & enforce | Khai báo mã quyền của mình |",
        "| Sequence / mã chứng từ | Cấp số | Định nghĩa pattern nghiệp vụ |",
        "| File đính kèm | Lưu & ACL | Gắn metadata nghiệp vụ |",
        "| Thông báo | Template + kênh | Trigger nội dung |",
        "| Workflow duyệt | Không bắt buộc sở hữu | Có thể dùng WF hoặc duyệt nội bộ |",
        "| Event Bus | Hạ tầng | Publish / subscribe business events |",
        "",
        "---",
        "",
        "## 6. Master data — chủ sở hữu",
        "",
        "| Thực thể | Module sở hữu | Module tham chiếu chính |",
        "|---|---|---|",
        "| Tenant / User / Role / Org | SYS | Tất cả |",
        "| Employee / Contract | HRM | LMS, FIN, PJM, AST |",
        "| Customer / Lead / Opportunity | CRM | POS, LOG, FIN, FSM, PRT |",
        "| Vendor | PUR | FIN (AP), INV (GRN) |",
        "| Item / UoM / Warehouse | INV *(hoặc master hàng hóa chung thuộc INV)* | POS, PUR, LOG, MFG, CRM |",
        "| Chart of Accounts / Period | FIN | HRM, AST, CRM, PUR |",
        "| Asset | AST | FIN, HRM, PUR |",
        "| Project | PJM | FIN, INV, HRM, CRM |",
        "| Course / Certificate | LMS | HRM |",
        "| Ticket / Work Order | FSM | CRM, INV, PRT |",
        "",
        "> Quy tắc: **cấm nhân bản lệch** — khi cần hiển thị, đọc theo ID hoặc projection chỉ đọc.",
        "",
        "---",
        "",
        "## 7. License & đóng gói bán",
        "",
        "### 7.1. Hard dependency",
        "- Mọi module nghiệp vụ: **SYS**.",
        "- LOG: khuyến nghị cứng **INV** (xuất/nhập giao).",
        "- MFG: khuyến nghị cứng **INV** (NVL/TP).",
        "",
        "### 7.2. Soft dependency (tính năng E2E)",
        "Ví dụ: HRM chạy được thiếu FIN (không post bút toán); CRM chạy được thiếu LOG (không tạo chuyến).",
        "Chi tiết ma trận: tài liệu **INT-02**.",
        "",
        "---",
        "",
        "## 8. An toàn & tuân thủ tích hợp",
        "",
        "- Mọi API liên module đi qua auth SYS + permission + license.",
        "- Field nhạy cảm (lương, CCCD, giá vốn) không lộ qua event thô nếu subscriber thiếu quyền.",
        "- Webhook outbound (SYS) ký secret; không nhúng credential module vào event payload.",
        "- CorrelationId bắt buộc trên event nghiệp vụ trọng yếu để QA/trace.",
        "",
        "---",
        "",
        "## 9. Truy vết tài liệu",
        "",
        "| Artifact | Vị trí |",
        "|---|---|",
        "| SRS từng module | `../01. Modules/**/SRS_*_v1.1.docx` |",
        "| Chuẩn tích hợp | `00_CHUAN_TAI_LIEU.md` |",
        "| Ma trận phụ thuộc | `INT-02` |",
        "| Catalog sự kiện | `INT-03` |",
        "| Luồng E2E | `INT-04` |",
        "| Đồng bộ & lỗi | `INT-05` |",
        "",
        "---",
        "",
        "*Hết INT-01-v1.0.*",
        "",
    ]
    return a


# ---------------------------------------------------------------------------
# INT-02
# ---------------------------------------------------------------------------
def doc_int_02() -> list[str]:
    a: list[str] = []
    a += header(
        "INT-02-v1.0",
        "Ma trận phụ thuộc & đóng gói liên module",
        "Module Dependency Matrix & Packaging",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "### 1.1. Mục đích",
        "Chốt **phụ thuộc bắt buộc / khuyến nghị** giữa module để Presales đóng gói đúng và Solution thiết kế không gãy E2E.",
        "",
        "### 1.2. Ký hiệu",
        "| Ký hiệu | Nghĩa |",
        "|---|---|",
        "| **H** | Hard — không bán/triển khai thiếu |",
        "| **S** | Soft — module chạy được nhưng thiếu tính năng E2E |",
        "| **R** | Read — chỉ đọc master/projection |",
        "| **—** | Không phụ thuộc trực tiếp |",
        "",
        "---",
        "",
        "## 2. Phụ thuộc cứng theo module",
        "",
        "| Module | Hard dependency | Ghi chú |",
        "|---|---|---|",
        "| SYS | — | Nền tảng |",
        "| HRM | SYS | |",
        "| LMS | SYS | Soft: HRM |",
        "| CRM | SYS | Soft: INV, LOG, FIN, WF, PRT |",
        "| POS | SYS | Soft: INV, FIN, CRM |",
        "| PUR | SYS | Soft: INV, FIN, WF |",
        "| INV | SYS | Soft: PUR, LOG, POS, MFG, FIN |",
        "| LOG | SYS, **INV** | Soft: CRM, FIN |",
        "| MFG | SYS, **INV** | Soft: PUR, FIN, HRM, CRM |",
        "| FSM | SYS | Soft: CRM, INV, FIN, PRT |",
        "| PJM | SYS | Soft: CRM, INV, FIN, HRM, WF |",
        "| FIN | SYS | Soft: CRM, PUR, INV, POS, HRM, AST, LOG |",
        "| AST | SYS | Soft: FIN, HRM, PUR |",
        "| WF | SYS | Soft: mọi module phát sinh duyệt |",
        "| BI | SYS | Soft: dataset theo license module nguồn |",
        "| PRT | SYS | Soft: CRM, LOG, FIN, FSM, PUR |",
        "",
        "---",
        "",
        "## 3. Ma trận tương tác (hàng = nguồn / cột = đích tiêu biểu)",
        "",
        "> Ô ghi kênh chính: `E` = Event, `A` = API đồng bộ, `R` = Read master, `W` = Workflow.",
        "",
        "| Từ \\ Đến | SYS | HRM | CRM | INV | FIN | WF | PRT |",
        "|---|---|---|---|---|---|---|---|",
        "| SYS | — | E/R | E/R | E/R | E/R | E/R | E/R |",
        "| HRM | A/R | — | — | — | E | W | — |",
        "| LMS | A/R | E | — | — | E | — | — |",
        "| CRM | A/R | — | — | A/E | E | W | E |",
        "| POS | A/R | — | E/R | A | E | — | — |",
        "| PUR | A/R | — | — | A/E | E | W | E |",
        "| INV | A/R | — | R | — | E | — | — |",
        "| LOG | A/R | — | E/R | A/E | E | — | E |",
        "| MFG | A/R | R | R | A/E | E | — | — |",
        "| FSM | A/R | — | E/R | A | E | — | E |",
        "| PJM | A/R | R | R | A | E | W | — |",
        "| FIN | A/R | R | R | R | — | W | E |",
        "| AST | A/R | E | — | — | E | — | — |",
        "| WF | A/R | E | E | — | E | — | — |",
        "| BI | A/R | R | R | R | R | — | — |",
        "| PRT | A/R | — | A/E | — | A/E | — | — |",
        "",
        "---",
        "",
        "## 4. Gói bán E2E gợi ý (presales)",
        "",
        "### 4.1. Gói Nhân sự số",
        "| Thành phần | Vai trò |",
        "|---|---|",
        "| SYS + HRM | Bắt buộc |",
        "| WF | Duyệt phép/công/tuyển |",
        "| LMS | Đào tạo bắt buộc onboarding |",
        "| FIN | Post chi phí lương |",
        "| AST | Thu hồi tài sản khi nghỉ |",
        "",
        "### 4.2. Gói Bán hàng & phân phối",
        "| Thành phần | Vai trò |",
        "|---|---|",
        "| SYS + CRM | Bắt buộc |",
        "| INV + LOG | ATP, giao hàng |",
        "| FIN | Công nợ / doanh thu |",
        "| WF | Duyệt chiết khấu / hạn mức |",
        "| PRT | KH tự phục vụ |",
        "",
        "### 4.3. Gói Bán lẻ",
        "| Thành phần | Vai trò |",
        "|---|---|",
        "| SYS + POS | Bắt buộc |",
        "| INV | Trừ tồn realtime |",
        "| FIN | Doanh thu ca / quỹ |",
        "| CRM | KM, loyalty, KH |",
        "",
        "### 4.4. Gói Mua hàng – Kho – Sản xuất",
        "| Thành phần | Vai trò |",
        "|---|---|",
        "| SYS + PUR + INV | Trục chính |",
        "| MFG | Lệnh SX, NVL/TP |",
        "| FIN | AP & giá thành |",
        "| WF | Duyệt PR/PO |",
        "",
        "### 4.5. Gói Dịch vụ & dự án",
        "| Thành phần | Vai trò |",
        "|---|---|",
        "| SYS + FSM / PJM | Theo nghiệp vụ |",
        "| CRM | KH / HĐ |",
        "| INV | Linh kiện / vật tư |",
        "| FIN | Doanh thu – chi phí |",
        "| PRT | Ticket self-service |",
        "",
        "---",
        "",
        "## 5. Ma trận ảnh hưởng khi tắt license",
        "",
        "| Module bị tắt | Ảnh hưởng tức thì | Hành vi bắt buộc |",
        "|---|---|---|",
        "| SYS | Toàn hệ thống | Không cho tắt khi còn module khác active |",
        "| INV | POS/LOG/MFG/PUR E2E gãy phần tồn | Chặn API INV; cảnh báo dependency |",
        "| FIN | Không post sổ | Module nguồn giữ chứng từ “Pending post” |",
        "| WF | Duyệt treo | Fallback duyệt nội module hoặc escalation admin |",
        "| CRM | PRT/LOG thiếu ngữ cảnh KH-đơn | Ẩn journey liên quan |",
        "| HRM | LMS gán NV theo vị trí hạn chế | LMS vẫn chạy khóa public/internal khác |",
        "",
        "---",
        "",
        "## 6. Checklist chốt gói với khách",
        "",
        "1. Liệt kê module Must theo nghiệp vụ cốt lõi.",
        "2. Map soft dependency → quyết định mua kèm Phase 1 hay Phase 2.",
        "3. Xác nhận có dùng WF tập trung hay duyệt nội module.",
        "4. Xác nhận master hàng hóa / KH / NV lấy từ đâu (tránh 2 nguồn).",
        "5. Ký biên bản phụ thuộc (hard) trước khi kickoff kỹ thuật.",
        "",
        "---",
        "",
        "*Hết INT-02-v1.0.*",
        "",
    ]
    return a


# ---------------------------------------------------------------------------
# INT-03
# ---------------------------------------------------------------------------
def doc_int_03() -> list[str]:
    a: list[str] = []
    a += header(
        "INT-03-v1.0",
        "Catalog sự kiện & hợp đồng dữ liệu liên module",
        "Event Catalog & Logical Data Contracts",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "### 1.1. Mục đích",
        "Chuẩn hóa **tên sự kiện, publisher, subscriber và payload logic** để các module tích hợp thống nhất — mức BA/Solution (chưa phải schema JSON kỹ thuật cuối).",
        "",
        "### 1.2. Quy ước đặt tên",
        "- Format: `{BoundedContext}{Entity}{PastAction}` — ví dụ `HrmEmployeeTerminated`, `CrmSalesOrderConfirmed`.",
        "- Dùng **quá khứ** (đã xảy ra), không dùng mệnh lệnh.",
        "- Version payload: `payloadVersion` (int), tăng khi breaking change.",
        "",
        "### 1.3. Envelope sự kiện (chung)",
        "",
        "| Trường | Bắt buộc | Mô tả |",
        "|---|---|---|",
        "| `eventId` | Có | UUID duy nhất |",
        "| `eventType` | Có | Tên sự kiện |",
        "| `occurredAt` | Có | UTC timestamp |",
        "| `tenantId` | Có | Tenant |",
        "| `correlationId` | Có | Trace xuyên suốt journey |",
        "| `causationId` | Không | Event/command gốc |",
        "| `producer` | Có | Mã module (HRM, CRM…) |",
        "| `payloadVersion` | Có | Phiên bản hợp đồng |",
        "| `payload` | Có | Dữ liệu nghiệp vụ tối thiểu |",
        "",
        "---",
        "",
        "## 2. Catalog sự kiện theo miền",
        "",
        "### 2.1. SYS (nền)",
        "| Event | Publisher | Subscriber tiêu biểu | Payload tối thiểu |",
        "|---|---|---|---|",
        "| `SysUserCreated` | SYS | HRM, PRT, tất cả | userId, orgIds, roles |",
        "| `SysUserDisabled` | SYS | Tất cả | userId, reason |",
        "| `SysRoleChanged` | SYS | Audit, BI | userId, rolesBefore/After |",
        "| `SysLicenseChanged` | SYS | Tất cả module | modules[], effectiveFrom |",
        "| `SysOrgUnitChanged` | SYS | HRM, INV, CRM | orgUnitId, path |",
        "| `SysNotificationRequested` | Mọi module→SYS | Email/SMS gateway | template, to, data |",
        "",
        "### 2.2. HRM ↔ liên module",
        "| Event | Publisher | Subscriber | Mục đích |",
        "|---|---|---|---|",
        "| `HrmEmployeeHired` | HRM | LMS, SYS(user link), AST | Onboarding, cấp tài khoản |",
        "| `HrmEmployeeTerminated` | HRM | SYS, AST, LMS, FIN | Thu hồi quyền, tài sản, quyết toán |",
        "| `HrmTimesheetLocked` | HRM | FIN (payroll prep) | Khóa công sẵn sàng tính lương |",
        "| `HrmPayrollPosted` | HRM | FIN | Chi phí lương / phải trả |",
        "| `HrmLeaveApproved` | HRM | INV/POS?(optional staffing) | Cập nhật lịch vắng |",
        "| `LmsCertificateIssued` | LMS | HRM | Ghi chứng chỉ vào hồ sơ |",
        "",
        "### 2.3. CRM / POS / PRT",
        "| Event | Publisher | Subscriber | Mục đích |",
        "|---|---|---|---|",
        "| `CrmLeadQualified` | CRM | WF, BI | Pipeline |",
        "| `CrmQuoteApproved` | CRM/WF | CRM | Cho phép tạo SO |",
        "| `CrmSalesOrderConfirmed` | CRM | INV, LOG, FIN, PRT | Reserve / giao / công nợ |",
        "| `CrmSalesOrderCancelled` | CRM | INV, LOG, FIN | Nhả reserve, hủy giao |",
        "| `PosSaleCompleted` | POS | INV, FIN, CRM | Trừ tồn, doanh thu, loyalty |",
        "| `PosShiftClosed` | POS | FIN | Đối soát ca |",
        "| `PrtTicketCreated` | PRT | FSM/CRM | Tiếp nhận CSKH |",
        "",
        "### 2.4. PUR / INV / LOG / MFG",
        "| Event | Publisher | Subscriber | Mục đích |",
        "|---|---|---|---|",
        "| `PurPurchaseRequestApproved` | PUR/WF | PUR | Cho tạo PO |",
        "| `PurPurchaseOrderConfirmed` | PUR | INV, PRT(NCC), FIN | Kỳ vọng nhận hàng / AP |",
        "| `PurGoodsReceived` | PUR/INV | INV, FIN | Nhập kho, tạm nhập AP |",
        "| `InvStockReserved` | INV | CRM/POS | Giữ hàng |",
        "| `InvStockIssued` | INV | FIN, LOG, MFG | Xuất kho |",
        "| `InvStockReceived` | INV | FIN, MFG | Nhập kho |",
        "| `InvStockCountPosted` | INV | FIN | Điều chỉnh tồn |",
        "| `LogShipmentDispatched` | LOG | CRM, PRT, FIN | Tracking, COD |",
        "| `LogShipmentDelivered` | LOG | CRM, FIN, PRT | Hoàn tất giao / thu COD |",
        "| `MfgWorkOrderReleased` | MFG | INV | Xuất NVL |",
        "| `MfgWorkOrderCompleted` | MFG | INV, FIN | Nhập TP, giá thành |",
        "",
        "### 2.5. FIN / AST / FSM / PJM / WF / BI",
        "| Event | Publisher | Subscriber | Mục đích |",
        "|---|---|---|---|",
        "| `FinPeriodClosed` | FIN | Tất cả chứng từ nguồn | Chặn post sai kỳ |",
        "| `FinPaymentReceived` | FIN | CRM, PRT, LOG | Cập nhật công nợ |",
        "| `FinPaymentMade` | FIN | PUR | Thanh toán NCC |",
        "| `AstAssetAssigned` | AST | HRM | Gắn tài sản NV |",
        "| `AstAssetReturned` | AST | HRM | Offboarding |",
        "| `AstDepreciationPosted` | AST | FIN | Bút toán KH |",
        "| `FsmWorkOrderClosed` | FSM | FIN, CRM, PRT | Phí dịch vụ / CSAT |",
        "| `PjmProjectClosed` | PJM | FIN, FSM, AST | Quyết toán / BH |",
        "| `WfTaskApproved` | WF | Module nguồn | Tiếp tục vòng đời |",
        "| `WfTaskRejected` | WF | Module nguồn | Trả về chỉnh sửa |",
        "| `BiDatasetRefreshRequested` | BI/SYS | ETL | Làm mới dữ liệu |",
        "",
        "---",
        "",
        "## 3. Hợp đồng dữ liệu logic (tham chiếu chéo)",
        "",
        "### 3.1. CustomerRef",
        "| Trường | Nguồn | Ghi chú |",
        "|---|---|---|",
        "| `customerId` | CRM | Khóa chính |",
        "| `code`, `name` | CRM | Snapshot cho chứng từ |",
        "| `taxCode` | CRM | Hóa đơn |",
        "",
        "### 3.2. ItemRef",
        "| Trường | Nguồn | Ghi chú |",
        "|---|---|---|",
        "| `itemId` | INV | Khóa chính |",
        "| `sku`, `name`, `uom` | INV | Snapshot |",
        "| `itemType` | INV | Goods/Service/Recipe… |",
        "",
        "### 3.3. EmployeeRef",
        "| Trường | Nguồn | Ghi chú |",
        "|---|---|---|",
        "| `employeeId` | HRM | Khóa chính |",
        "| `userId` | SYS | Liên kết đăng nhập |",
        "| `orgUnitId` | SYS/HRM | Phạm vi |",
        "",
        "### 3.4. MoneyAmount",
        "| Trường | Mô tả |",
        "|---|---|",
        "| `amount`, `currency` | Số tiền |",
        "| `exchangeRate` | Nếu đa tiền tệ |",
        "| `taxAmount` | Thuế (nếu tách) |",
        "",
        "---",
        "",
        "## 4. Quyền publish / subscribe",
        "",
        "| Vai trò | Được phép |",
        "|---|---|",
        "| Module sở hữu aggregate | Publish event của aggregate đó |",
        "| Module khác | Subscribe; **không** giả mạo publisher |",
        "| Integration account | Chỉ event/API trong scope API Key |",
        "| BI | Subscribe/read projection; không publish nghiệp vụ |",
        "",
        "---",
        "",
        "## 5. Phiên bản & tương thích",
        "",
        "1. Thêm field optional → tăng `payloadVersion` minor (cùng major tương thích).",
        "2. Đổi nghĩa / xóa field → major; chạy dual-publish tạm thời.",
        "3. Mọi breaking change ghi vào lịch sử INT-03 và thông báo Tech Lead các module subscribe.",
        "",
        "---",
        "",
        "## 6. Truy vết SRS",
        "Mỗi event nên ánh xạ ít nhất một UC nguồn (ví dụ `HrmPayrollPosted` ← UC tính/chốt lương HRM).",
        "",
        "---",
        "",
        "*Hết INT-03-v1.0.*",
        "",
    ]
    return a


# ---------------------------------------------------------------------------
# INT-04
# ---------------------------------------------------------------------------
def doc_int_04() -> list[str]:
    a: list[str] = []
    a += header(
        "INT-04-v1.0",
        "Luồng nghiệp vụ end-to-end liên module",
        "Cross-Module End-to-End Journeys",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "### 1.1. Mục đích",
        "Mô tả các **hành trình nghiệp vụ xuyên module** để BA/QA/Dev thống nhất điểm nối, sự kiện và tiêu chí hoàn tất.",
        "",
        "### 1.2. Cách đọc",
        "- Mỗi journey: mục tiêu → module tham gia → các bước → sự kiện chính → tiêu chí xong.",
        "- Chi tiết màn hình/UC nằm trong SRS module tương ứng.",
        "",
        "---",
        "",
        "## 2. E2E-01 — Lead to Cash (Bán hàng có giao & công nợ)",
        "",
        "**Module:** SYS, CRM, INV, LOG, FIN, WF*(opt)*, PRT*(opt)*",
        "",
        "| Bước | Module | Hành động | Event / tương tác |",
        "|---:|---|---|---|",
        "| 1 | CRM | Tạo Lead → Qualify | `CrmLeadQualified` |",
        "| 2 | CRM + WF | Báo giá & duyệt chiết khấu | `CrmQuoteApproved` |",
        "| 3 | CRM | Xác nhận Sales Order | `CrmSalesOrderConfirmed` |",
        "| 4 | INV | Reserve / kiểm ATP | `InvStockReserved` (API đồng bộ) |",
        "| 5 | LOG | Tạo & điều phối chuyến giao | `LogShipmentDispatched` |",
        "| 6 | LOG | Giao thành công / COD | `LogShipmentDelivered` |",
        "| 7 | FIN | Ghi nhận doanh thu & công nợ / thu tiền | `FinPaymentReceived` |",
        "| 8 | PRT | KH theo dõi đơn & thanh toán | Read models |",
        "",
        "**Hoàn tất khi:** Đơn Delivered/Closed; tồn khớp; công nợ phản ánh đúng; có audit xuyên suốt `correlationId`.",
        "",
        "---",
        "",
        "## 3. E2E-02 — Mua hàng đến thanh toán NCC",
        "",
        "**Module:** SYS, PUR, INV, FIN, WF*(opt)*, PRT*(NCC opt)*",
        "",
        "| Bước | Module | Hành động | Event / tương tác |",
        "|---:|---|---|---|",
        "| 1 | INV/PUR | Nhu cầu tồn min / tạo PR | — |",
        "| 2 | WF/PUR | Duyệt PR | `PurPurchaseRequestApproved` |",
        "| 3 | PUR | Tạo & xác nhận PO | `PurPurchaseOrderConfirmed` |",
        "| 4 | INV/PUR | Nhận hàng GRN | `PurGoodsReceived` / `InvStockReceived` |",
        "| 5 | FIN | Khớp hóa đơn NCC / AP | — |",
        "| 6 | FIN | Thanh toán NCC | `FinPaymentMade` |",
        "",
        "**Hoàn tất khi:** Tồn tăng đúng PO; AP清零或正确; 3-way match (PO–GRN–Invoice) đạt rule.",
        "",
        "> Sửa: Hoàn tất khi tồn tăng đúng PO; AP phản ánh đúng; khớp 3 chứng từ theo rule.",
        "",
        "---",
        "",
        "## 4. E2E-03 — Bán lẻ trong ca (POS)",
        "",
        "**Module:** SYS, POS, INV, FIN, CRM*(opt)*",
        "",
        "| Bước | Module | Hành động | Event / tương tác |",
        "|---:|---|---|---|",
        "| 1 | POS | Mở ca | — |",
        "| 2 | POS+INV | Bán hàng / trừ tồn (đồng bộ) | `PosSaleCompleted` |",
        "| 3 | CRM | Tích điểm / gắn KH | Subscribe sale |",
        "| 4 | POS | Đóng ca, đối quỹ | `PosShiftClosed` |",
        "| 5 | FIN | Post doanh thu / quỹ | Subscribe shift/sale |",
        "",
        "**Hoàn tất khi:** Tồn khớp bán; ca đóng; sổ quỹ/doanh thu nhận đủ chứng từ.",
        "",
        "---",
        "",
        "## 5. E2E-04 — Sản xuất chuẩn (Make to Stock/Order)",
        "",
        "**Module:** SYS, MFG, INV, PUR*(opt)*, FIN, CRM*(opt)*",
        "",
        "| Bước | Module | Hành động | Event / tương tác |",
        "|---:|---|---|---|",
        "| 1 | CRM/MFG | Nhu cầu / kế hoạch | — |",
        "| 2 | MFG | Release Work Order | `MfgWorkOrderReleased` |",
        "| 3 | INV | Xuất NVL | `InvStockIssued` |",
        "| 4 | PUR | PR thiếu NVL (nếu cần) | — |",
        "| 5 | MFG | Hoàn thành + QC | `MfgWorkOrderCompleted` |",
        "| 6 | INV | Nhập TP | `InvStockReceived` |",
        "| 7 | FIN | Giá thành / bút toán | Subscribe WO completed |",
        "",
        "**Hoàn tất khi:** NVL/TP khớp BOM & số lượng; giá thành có thể tái lập.",
        "",
        "---",
        "",
        "## 6. E2E-05 — Hire to Retire (Nhân sự)",
        "",
        "**Module:** SYS, HRM, LMS, WF, FIN, AST",
        "",
        "| Bước | Module | Hành động | Event / tương tác |",
        "|---:|---|---|---|",
        "| 1 | HRM+WF | Tuyển dụng & duyệt | — |",
        "| 2 | HRM | Tạo hồ sơ / HĐ | `HrmEmployeeHired` |",
        "| 3 | SYS | Cấp user & quyền | Subscribe hire |",
        "| 4 | LMS | Gán đào tạo bắt buộc | Subscribe hire |",
        "| 5 | HRM | Chấm công → khóa công | `HrmTimesheetLocked` |",
        "| 6 | HRM | Payroll | `HrmPayrollPosted` → FIN |",
        "| 7 | HRM | Nghỉ việc | `HrmEmployeeTerminated` |",
        "| 8 | AST+SYS | Thu hồi tài sản & quyền | Subscribe terminate |",
        "",
        "**Hoàn tất khi:** Hồ sơ Closed; user disabled; tài sản thu hồi; quyết toán lương/phép xong.",
        "",
        "---",
        "",
        "## 7. E2E-06 — Dịch vụ hiện trường & cổng KH",
        "",
        "**Module:** SYS, FSM, CRM, INV, FIN, PRT",
        "",
        "| Bước | Module | Hành động | Event / tương tác |",
        "|---:|---|---|---|",
        "| 1 | PRT/CRM | Tạo ticket | `PrtTicketCreated` |",
        "| 2 | FSM | Điều phối kỹ thuật viên | — |",
        "| 3 | INV | Xuất linh kiện | `InvStockIssued` |",
        "| 4 | FSM | Đóng WO | `FsmWorkOrderClosed` |",
        "| 5 | FIN | Phí dịch vụ / bảo hành | Subscribe |",
        "| 6 | PRT | KH xem tiến độ & đánh giá | Read |",
        "",
        "---",
        "",
        "## 8. E2E-07 — Dự án đến quyết toán",
        "",
        "**Module:** SYS, PJM, CRM, INV, HRM, FIN, WF, FSM*(BH)*",
        "",
        "| Bước | Module | Hành động | Event / tương tác |",
        "|---:|---|---|---|",
        "| 1 | CRM→PJM | Ký HĐ / mở dự án | — |",
        "| 2 | WF | Duyệt kickoff / CR | `WfTaskApproved` |",
        "| 3 | INV/HRM | Cấp vật tư & nhân sự | — |",
        "| 4 | PJM | Theo dõi tiến độ / chi phí | — |",
        "| 5 | FIN | Ghi nhận doanh thu–chi phí | — |",
        "| 6 | PJM | Đóng dự án | `PjmProjectClosed` |",
        "| 7 | FSM | Bàn giao bảo hành | Subscribe |",
        "",
        "---",
        "",
        "## 9. E2E-08 — Khóa sổ tháng (FIN hub)",
        "",
        "**Module:** FIN (+ mọi module phát sinh chứng từ tài chính)",
        "",
        "| Bước | Module | Hành động |",
        "|---:|---|---|",
        "| 1 | CRM/POS/LOG/PUR/INV/HRM/AST/MFG | Hoàn tất chứng từ kỳ |",
        "| 2 | FIN | Đối soát & xử lý treo |",
        "| 3 | FIN | Khóa kỳ | `FinPeriodClosed` |",
        "| 4 | Tất cả | Chặn post sai kỳ; điều chỉnh qua chứng từ điều chỉnh |",
        "",
        "---",
        "",
        "## 10. Ma trận journey ↔ module",
        "",
        "| Journey | SYS | HRM | LMS | CRM | POS | PUR | INV | LOG | MFG | FSM | PJM | FIN | AST | WF | BI | PRT |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
        "| E2E-01 Lead to Cash | ● | | | ● | | | ● | ● | | | | ● | | ○ | ○ | ○ |",
        "| E2E-02 Procure to Pay | ● | | | | | ● | ● | | | | | ● | | ○ | | ○ |",
        "| E2E-03 POS Shift | ● | | | ○ | ● | | ● | | | | | ● | | | | |",
        "| E2E-04 Make | ● | ○ | | ○ | | ○ | ● | | ● | | | ● | | | | |",
        "| E2E-05 Hire to Retire | ● | ● | ● | | | | | | | | | ● | ● | ○ | | |",
        "| E2E-06 Field Service | ● | | | ● | | | ● | | | ● | | ● | | | | ● |",
        "| E2E-07 Project | ● | ○ | | ● | | | ● | | | ○ | ● | ● | ○ | ○ | | |",
        "| E2E-08 Period Close | ● | ○ | | ○ | ○ | ○ | ○ | ○ | ○ | ○ | ○ | ● | ○ | | ○ | |",
        "",
        "> ● = tham gia chính · ○ = tùy gói / Phase",
        "",
        "---",
        "",
        "## 11. Tiêu chí nghiệm thu tích hợp (chung)",
        "",
        "1. Mỗi journey chạy demo thành công với module hard dependency.",
        "2. Tắt soft module → journey degrade đúng mô tả INT-02 (không 500 hàng loạt).",
        "3. Event có `correlationId` xuyên suốt; đối soát được số lượng chứng từ.",
        "4. Không nhân bản master; ID tham chiếu resolve được.",
        "5. QA có test case truy vết INT-04 → SRS UC.",
        "",
        "---",
        "",
        "*Hết INT-04-v1.0.*",
        "",
    ]
    # Fix the Chinese leftover I accidentally typed
    text = "\n".join(a)
    text = text.replace(
        "**Hoàn tất khi:** Tồn tăng đúng PO; AP清零或正确; 3-way match (PO–GRN–Invoice) đạt rule.\n\n> Sửa: Hoàn tất khi tồn tăng đúng PO; AP phản ánh đúng; khớp 3 chứng từ theo rule.",
        "**Hoàn tất khi:** Tồn tăng đúng PO; AP phản ánh đúng; khớp 3 chứng từ (PO–GRN–Invoice) theo rule.",
    )
    return text.split("\n")


# ---------------------------------------------------------------------------
# INT-05
# ---------------------------------------------------------------------------
def doc_int_05() -> list[str]:
    a: list[str] = []
    a += header(
        "INT-05-v1.0",
        "Đồng bộ, xử lý lỗi & vận hành tích hợp",
        "Sync, Failure Handling & Integration Operations",
    )
    a += [
        "## 1. Giới thiệu",
        "",
        "Tài liệu quy định cách hệ thống **đồng bộ dữ liệu liên module**, xử lý lỗi, đảm bảo tính nhất quán và vận hành khi sự cố hoặc thay đổi license.",
        "",
        "---",
        "",
        "## 2. Mô hình Outbox / Inbox",
        "",
        "```text",
        " [Module A DB Txn] --write--> Outbox --> (Dispatcher SYS) --> Bus",
        "                                                      |",
        "                                                 Subscriber",
        "                                                      |",
        "                                                 Inbox / Processed",
        "                                                      |",
        "                                               [Module B handler]",
        "```",
        "",
        "| Thành phần | Trách nhiệm |",
        "|---|---|",
        "| Outbox | Cùng transaction với ghi nghiệp vụ nguồn |",
        "| Dispatcher | Publish ít nhất một lần |",
        "| Inbox | Chống xử lý trùng (`eventId`) |",
        "| Dead Letter | Lưu event thất bại quá số lần retry |",
        "",
        "---",
        "",
        "## 3. Idempotency",
        "",
        "1. Consumer **bắt buộc** kiểm tra `eventId` đã xử lý chưa.",
        "2. Thao tác tạo chứng từ từ event dùng `idempotencyKey` = `eventId` hoặc `producer+businessKey`.",
        "3. API đồng bộ (reserve tồn, thu tiền…) nhận header/key idempotency từ client.",
        "",
        "---",
        "",
        "## 4. Chiến lược retry",
        "",
        "| Loại lỗi | Hành vi |",
        "|---|---|",
        "| Lỗi tạm (timeout, 5xx, DB lock) | Retry exponential backoff (ví dụ 15s → 1m → 5m → 30m) |",
        "| Lỗi nghiệp vụ (validate, thiếu master) | Không retry vô hạn; đưa DLQ + thông báo admin module |",
        "| Module đích tắt license | Park event / skip có log; không spam retry |",
        "| Sai schema version | DLQ + alert Solution |",
        "",
        "---",
        "",
        "## 5. Nhất quán dữ liệu",
        "",
        "### 5.1. Strong consistency (đồng bộ)",
        "Dùng khi sai lệch ngay gây mất tiền/hàng: trừ tồn POS, reserve SO, ghi nhận thanh toán tại quầy.",
        "",
        "### 5.2. Eventual consistency (bất đồng bộ)",
        "Dùng khi chấp nhận trễ vài giây–phút: post sổ, thông báo, cập nhật portal, BI.",
        "",
        "### 5.3. Đối soát định kỳ",
        "| Cặp | Đối soát |",
        "|---|---|",
        "| POS sale ↔ INV issue | Số lượng theo ca/ngày |",
        "| SO confirmed ↔ Shipment ↔ AR | Trạng thái đơn vs công nợ |",
        "| Payroll posted ↔ FIN journals | Tổng tiền kỳ |",
        "| GRN ↔ AP invoice | 3-way match ngoại lệ |",
        "",
        "---",
        "",
        "## 6. Hành vi khi tắt / hết hạn module",
        "",
        "| Tình huống | Hành vi chuẩn |",
        "|---|---|",
        "| Tắt module đích | Publisher vẫn ghi outbox; dispatcher đánh dấu `blocked_by_license`; UI nguồn cảnh báo |",
        "| Bật lại module | Replay / reprocess hàng đợi theo policy |",
        "| Hết hạn SYS | Toàn hệ thống theo chính sách license SYS (read-only / block) |",
        "| Xóa dữ liệu | **Không** xóa tự động khi tắt module; chỉ theo job purge có phê duyệt |",
        "",
        "---",
        "",
        "## 7. Quan sát & vận hành",
        "",
        "| Chỉ số | Ngưỡng gợi ý |",
        "|---|---|",
        "| Lag Outbox (p95) | < 30s môi trường chuẩn |",
        "| Tỷ lệ DLQ / ngày | ≈ 0; mọi bản ghi có owner xử lý |",
        "| Thời gian xử lý consumer p95 | Theo SLA từng journey |",
        "| Số event poison | Alert ngay |",
        "",
        "**Log bắt buộc:** `eventId`, `eventType`, `tenantId`, `correlationId`, `consumer`, `result`, `errorCode`.",
        "",
        "---",
        "",
        "## 8. Bảo mật tích hợp",
        "",
        "- Service-to-service: JWT nội bộ hoặc mTLS (quyết định kỹ thuật sau).",
        "- Webhook ngoài: chữ ký HMAC, rotate secret.",
        "- Không đưa PII/lương vào event Broad-cast nếu subscriber không cần; dùng reference + pull có quyền.",
        "- Mọi thay đổi subscription event ghi audit.",
        "",
        "---",
        "",
        "## 9. Sự cố mẫu & cách xử lý",
        "",
        "| Sự cố | Triệu chứng | Xử lý |",
        "|---|---|---|",
        "| Đơn đã giao nhưng AR không tạo | Thiếu consumer FIN / DLQ | Reprocess event `LogShipmentDelivered` / `CrmSalesOrderConfirmed` |",
        "| Bán POS tồn âm | Race reserve | Khóa lạc quan / serialize theo item-warehouse; bù chứng từ |",
        "| Payroll post trùng bút toán | Thiếu idempotency | Chặn bằng `eventId`; đảo bút toán thủ công nếu đã lệch |",
        "| Portal không thấy đơn | Projection trễ | Kiểm tra lag; rebuild read model theo SO id |",
        "",
        "---",
        "",
        "## 10. Checklist go-live tích hợp",
        "",
        "1. Outbox/Inbox bật trên mọi module Phase 1.",
        "2. Danh sách event Phase 1 đã đăng ký (theo INT-03).",
        "3. Test tắt soft module không làm sập hard path.",
        "4. Có dashboard lag + DLQ.",
        "5. Runbook sự cố (mục 9) đã handover vận hành.",
        "6. Đối soát ngày đầu tiên sau go-live có chữ ký kế toán/ops.",
        "",
        "---",
        "",
        "## 11. Truy vết",
        "",
        "| Liên quan | Tài liệu |",
        "|---|---|",
        "| Kiến trúc | INT-01 |",
        "| Phụ thuộc | INT-02 |",
        "| Event | INT-03 |",
        "| Journey | INT-04 |",
        "| SRS module | `../01. Modules` |",
        "",
        "---",
        "",
        "*Hết INT-05-v1.0.*",
        "",
    ]
    return a


def export_docx(md_path: Path) -> None:
    out = md_path.with_suffix(".docx")
    meta = extract_meta_from_md(md_path)
    meta["org"] = "ERP MODULAR PRODUCT"
    meta["status"] = "Chờ duyệt — Tích hợp liên module"
    meta["classification"] = "Nội bộ dự án — BA / Solution Architecture"
    meta["history"] = [
        ["1.0", TODAY, "BA / Solution", "Khởi tạo bộ tích hợp liên module", "Chờ duyệt"],
    ]
    build(md_path, out, meta=meta)


def main() -> None:
    docs = [
        ("INT-01_Tong_quan_kien_truc_tich_hop.md", doc_int_01),
        ("INT-02_Ma_tran_phu_thuoc_module.md", doc_int_02),
        ("INT-03_Catalog_su_kien_hop_dong_du_lieu.md", doc_int_03),
        ("INT-04_Luong_E2E_lien_module.md", doc_int_04),
        ("INT-05_Dong_bo_loi_van_hanh.md", doc_int_05),
    ]
    for name, fn in docs:
        path = ROOT / name
        write(path, fn())
        export_docx(path)
    print("All INT docs done.")


if __name__ == "__main__":
    main()
